### ISSUE TITLE
Support for Go-To-Def with Yarn PnP

### ISSUE THREAD

**Issue by mmtftr** [zed-industries/zed#10107]
### Check for existing issues

- [X] Completed

### Describe the feature

With Yarn PnP, packages are resolved from a separate location from within zip files. There is @yarnpkg/sdks for language server support. Using the sdks, it's possible to have TSServer resolve packages correctly, however go-to-definition for packages will not work as the file itself is within a zip file. The URL given by the LSP will be a zip url and zed will open an empty buffer when resolving it. 

VSCode supports this workflow with the ZipFS extension. The extension simulates a filesystem for the zip file.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="926" alt="Screenshot 2024-04-03 at 10 58 22" src="https://github.com/zed-industries/zed/assets/13402668/d9b4a004-c3a4-4bb3-a031-84e4ca28ae24">

The file inside the zip archive should be opened instead. It can be read-only if necessary.

**Comment by forresthopkinsa** [comment]
Doesn't seem like this is resolved for Javascript projects?

**Comment by AyoItsYas** [comment]
I'm trying to migrate from vscode to zed the issue still persists or there is very little documentation covering how to configure this properly.

I've gone through : https://zed.dev/docs/languages/yarn and this is what my settings.json looks like,
```json
...
    "typescript-language-server": {
      "initialization_options": {
        "tsserver": {
          "path": "./.yarn/sdks/typescript/lib"
        },
        "preferences": {
          "includeInlayParameterNameHints": "all",
          "includeInlayParameterNameHintsWhenArgumentMatchesName": true,
          "includeInlayFunctionParameterTypeHints": true,
          "includeInlayVariableTypeHints": true,
          "includeInlayVariableTypeHintsWhenTypeMatchesName": true,
          "includeInlayPropertyDeclarationTypeHints": true,
          "includeInlayFunctionLikeReturnTypeHints": true,
          "includeInlayEnumMemberValueHints": true
        }
      }
    },
...
```
