### ISSUE TITLE
Some issues with a french keyboard layout

### ISSUE THREAD

**Issue by bluthej** [zed-industries/zed#11088]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have just started playing around with Zed and I quite like it! Kudos to the Zed team :clap: 

I have encountered a couple of issues related (I think) to my keyboard layout, which is somewhat exotic: it's a french bépo layout (equivalent of Dvorak but for french). Here are the two main issues I have:

- I cannot get dead keys to work, like ^ and ", which are used to type things like ê or ï
- I use vim keybindings, but on french layouts the numbers are not in direct access, we need to press shift to access them, and when I try to to "2yy" for example it only yanks the line I'm on instead of 2 lines. Note that if I press caps lock, hit the number, remove caps lock and then do "yy" it works just fine.

Incidentally, these issues prevent me from using the standard vim "go to start of line" keybindings because ^ is a dead key and 0 is a number :sweat_smile: 

Note that the dead-key issue occurs whether vim mode is enabled or not.

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 15 GiB
Architecture: x86_64

**Comment by Moshyfawn** [comment]
There's already an issue about Dead Keys support in
- #9207

The `shift` keybinds issue feels like
- #9808

Let me know if these make sense to you.

**Comment by bluthej** [comment]
Oh yes, sorry about that I guess when I looked for existing issues I made my search a little bit too specific and didn't find the already open issue on dead keys.

The 2nd issue does sound a bit like what I'm experiencing but I'm not sure that's what's going on for me. My issue is related to digits in vim normal mode specifically, like if I do "2yy" I only get one line yanked, but if I do "#" then I get backward search as expected (both "2" and "#" are on the shift layer in my layout). However in insert mode everything seems to work just fine on my end.
I did find one closed issue (#6281) that sounds like what I'm experiencing, but in my case it's the opposite, for instance I would need to remap "shift-(" to 4, but I can't get that to work.
I tried `"shift-(": ["vim::Number": 4]"` but that doesn't fix it.

**Comment by jansol** [comment]
Dead keys should work now that #11712 is merged

**Comment by mikayla-maki** [comment]
Gonna close this issue for now, feel free to open another if it's broken in a new way!

**Comment by bluthej** [comment]
@mikayla-maki I confirm that dead keys are now working on my end :tada: 

However, I still cannot get numbers to work in vim mode (on french layouts numbers are not in direct access, we have to use shift). Should I open a separate issue for that?
