### ISSUE TITLE
Go test runner does not work with fish shell

### ISSUE THREAD

**Issue by chrnorm** [zed-industries/zed#12617]
### Check for existing issues

- [X] Completed

### Describe the feature

I've just updated and discovered the new Go test runner feature. It looks great but unfortunately does not work by default on my machine. I am a `fish` user and I get the following error when running a test:

```
fish: Variables cannot be bracketed. In fish, please use {$ZED_CUSTOM_GO_P…}.
go test ${ZED_CUSTOM_GO_PACKAGE} -run $ZED_SYMBOL
         ^

⏵ Task `go test ./pkg/tokensvc -run Test_Service_Token` finished successfully
⏵ Command: '/Users/chrisnorman/.nix-profile/bin/fish -i -c `go test ./pkg/tokensvc -run Test_Service_Token`'
```

As a workaround I'd be very happy to use `zsh` or `bash` to execute these tests, I am not sure though which setting to change to switch the shell specifically for the Go tests.

**Comment by osiewicz** [comment]
This should be fixed on Wednesday (in a new Preview build).

**Comment by jeloba** [comment]
The bug is still present, this time complaining about a trailing `$`

```
fish: Expected a variable name after this $.
go test $ZED_CUSTOM_GO_PACKAGE -run ^$ZED_SYMBOL$
                                                ^
```
