### ISSUE TITLE
test runner does not work when shell = `nu`

### ISSUE THREAD

**Issue by universalmind303** [zed-industries/zed#12685]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```nu
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[source:1:15]
 1 │ cargo test -p ${ZED_CUSTOM_RUST_PACKAGE} $ZED_SYMBOL -- --nocapture
   ·               ─────────────┬────────────
   ·                            ╰── expected valid variable name
   ╰────


⏵ Task `cargo test -p arrow2 test_primitive_array_eq -- --nocapture` finished with non-zero error code: 1
⏵ Command: 'nu -i -c `cargo test -p arrow2 test_primitive_array_eq -- --nocapture`'
```

related to https://github.com/zed-industries/zed/issues/12617. 

### Environment

Zed: v0.137.6 (Zed)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: aarch64

**Comment by osiewicz** [comment]
That's fixed in latest Preview == it should be fixed on Stable (which you're using) in todays update.

**Comment by universalmind303** [comment]
@osiewicz This is still an issue for `nu` on the latest release

```nu
Error: nu::parser::env_var_not_var

  × Use $env.ZED_CUSTOM_RUST_PACKAGE instead of $ZED_CUSTOM_RUST_PACKAGE.
   ╭─[source:1:15]
 1 │ cargo test -p $ZED_CUSTOM_RUST_PACKAGE $ZED_SYMBOL -- --nocapture
   ·               ────────────┬───────────
   ·                           ╰── use $env.ZED_CUSTOM_RUST_PACKAGE instead of $ZED_CUSTOM_RUST_PACKAGE
   ╰────


⏵ Task `cargo test -p arrow2 test_merge_reversed -- --nocapture` finished with non-zero error code: 1
⏵ Command: 'nu -i -c `cargo test -p arrow2 test_merge_reversed -- --nocapture`'
```

**Comment by bemyak** [comment]
The solution which worked for me is to add this task to a local or global task list:
```json
  {
    "label": "Run Rust tests",
    "command": "cargo test -p $env.ZED_CUSTOM_RUST_PACKAGE $env.ZED_STEM",
    "tags": ["rust-test"],
    "use_new_terminal": true
  }
```

**Comment by bemyak** [comment]
I made this work by adding these tasks to my `~/.config/zed/tasks.json`:
```json
  {
    "label": "Run Rust tests",
    "command": "cargo test -p $env.ZED_CUSTOM_RUST_PACKAGE $env.ZED_SYMBOL -- --nocapture",
    "tags": ["rust-test"]
  },
  {
    "label": "Run Rust mod tests",
    "command": "cargo test -p $env.ZED_CUSTOM_RUST_PACKAGE $env.ZED_SYMBOL",
    "tags": ["rust-mod-test"]
  },
  {
    "label": "Run Rust main function",
    "command": "cargo run -p $env.ZED_CUSTOM_RUST_PACKAGE --bin $env.ZED_CUSTOM_RUST_BIN_NAME",
    "tags": ["rust-main"]
  }
```
