### ISSUE TITLE
TypeScript double/broken autocompletion

### ISSUE THREAD

**Issue by chungweileong94** [zed-industries/zed#12711]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Since v0.139.0, TypeScript/JavaScript/TSX is starting to show double autocomplete suggestions, one good one, one broken one (Please refer to the screen recording below)

I figured if this has something to do with the vtsls LSP, which seems to be enabled by default, there's no way to disable the LSP, even with the settings below:
```json
 "languages": {
    "TSX": {
      "language_servers": ["typescript-language-server", "!vtsls"]
    },
    "TypeScript": {
      "language_servers": ["typescript-language-server", "!vtsls"]
    },
    "JavaScript": {
      "language_servers": ["typescript-language-server", "!vtsls"]
    }
  }
```

### Environment

Zed: v0.139.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/15154097/1a77300d-96a0-491d-ad8e-b2e7fb046fb0

**Comment by chungweileong94** [comment]
It seems like the `vtsls` LSP is not disabled by default for some reason (#12611), in fact, both `vtsls` & `typescript-language-server` cannot be disabled any ways.
![image](https://github.com/zed-industries/zed/assets/15154097/0e8a3bc9-4603-46d3-a985-c755ab491ec1)

**Comment by osiewicz** [comment]
Hey, thanks for jumping in to provide a fix (and sorry for the trouble in the first place). I've released a new Preview version with that change included.

**Comment by chungweileong94** [comment]
> Hey, thanks for jumping in to provide a fix (and sorry for the trouble in the first place). I've released a new Preview version with that change included. Please do reopen this issue if you still run into this.
No worries, happy to help🙂

**Comment by chungweileong94** [comment]
@osiewicz Just downloaded the new preview version `0.139.1`, and it seems like the problem still remains. I don't think it's something to do with the default LSP settings, because setting it manually like `"language_servers": ["typescript-language-server", "!vtsls"]` doesn't work as well.

**Comment by osiewicz** [comment]
Have you restarted your language server after upadting the settings?
If anything, we can hop onto a call if needed.

**Comment by chungweileong94** [comment]
> Have you restarted your language server after updating the settings?

Ah my bad, it's because I have this `"language_servers": ["!biome", "!eslint", "..."]` in my workspace settings, which somehow override all the LSP settings.

**Comment by osiewicz** [comment]
Oh, yeah, I guess if you have custom knobs, then it'll override defaults for other languages as well. In that case you'd have to copy the default over to your settings and modify them as you see fit.

**Comment by Spoutnik97** [comment]
Hi @osiewicz, 
I tried 2 settings : 
```json
  "TSX": {
      "language_servers": ["!typescript-language-server", "vtsls", "..."],
      "formatter": {
        "code_actions": {
          "source.fixAll.eslint": true
        }
      }
    },
```

for the following result
<img width="328" alt="image" src="https://github.com/zed-industries/zed/assets/30442116/9f14af44-66ac-4379-9a05-38703a96cf91">


and 
```json
 "TSX": {
      "formatter": {
        "code_actions": {
          "source.fixAll.eslint": true
        }
      }
    },
```

for the following result 
<img width="332" alt="image" src="https://github.com/zed-industries/zed/assets/30442116/a059ec75-785a-46e9-90fa-28a6330910e4">


It seems that vtsls is faster than typescript-language-server (I have performance issues on my repo). But activating it remove the module from which my component is imported.

Any idea how to fix this ?

**Comment by Spoutnik97** [comment]
Do I need to create an issue to follow progresses ?

**Comment by chungweileong94** [comment]
I think this is somehow related to #12920, or at least part of the progress that needs to be made.

**Comment by Matix-Media** [comment]
I am experiencing the same issue. I only have `vtsls` running. I had deno lsp running before but I uninstalled it in the hopes of fixing it, but that did not help:

<img width="347" height="216" alt="Image" src="https://github.com/user-attachments/assets/f8b3285b-0f80-4e21-95b5-a396231186f4" />

**Comment by yooouuri** [comment]
Same here
