### ISSUE TITLE
Delete files should remove them from buffer

### ISSUE THREAD

**Issue by prestonButton** [zed-industries/zed#12993]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When deleting files from the file navigator, it should automatically close the buffers for those files. This is a problem because with autosave on, if the files stay open in the buffer, when autosave saves the file, it saves the files you thought were deleted, and adds them back to the file navigator.

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by someone13574** [comment]
Yes, this is very annoying when switching between branches where you had created a file in the branch you are leaving.

**Comment by notpeter** [comment]
I can no longer reproduce this and believe it has been fixed in new Zed releases.
When I delete a file from the project panel it automatically closes the buffer as well.

Thanks for reporting.

**Comment by JulienLecoq** [comment]
I still have this issue personally, when I delete a file and navigate using vim motions, I still find the buffer of the file.

**Comment by notpeter** [comment]
@JulienLecoq  It's possible that there was a regression or you're hitting a different code path which is triggering a similar issue.

If you reliably reproduce, can you provide complete step-by-step instructions to reproduce from an empty folder in a clean issue?

Thanks.
