### ISSUE TITLE
Opening Zed after the latest release opens a blank window alongside the editor window.

### ISSUE THREAD

**Issue by luka-hash** [zed-industries/zed#13018]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```sh
$ pacman -Q zed
zed 0.139.3-1
$ mkdir demo && zeditor demo/
```
![image](https://github.com/zed-industries/zed/assets/132906710/d9984509-2d45-4ff0-ba15-fc1ca6a60961)

---

Alternatively, when started via launcher (wofi), the same thing occurs.

Expected behaviour: Zed opens only one window - the editor window.

Note:
When hovering over the 'weird' window, cursor is not properly rendered, but instead there is a 'zoomed' cursor.

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 7.1 GiB
Architecture: x86_64
---
```sh
$ pacman -Q hyprland
hyprland 0.41.0-1
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/user-attachments/files/15829664/Zed.log)

**Comment by ConradIrwin** [comment]
@luka-hash We made some changes to window placement in 0.141. please let us know if it's still happening for you.

**Comment by luka-hash** [comment]
Still there.
It works (meaning there are no additional windows opened, just zed editor window) if I start it with the '--foreground' flag. Let me know if I can provide any additional info/help.

**Comment by ConradIrwin** [comment]
I suspect that we're interacting badly with your window manager. What window manager are you using, and are you using X11 or Wayland?

I think the black square in this case is the app as being managed by your window manager, and the app is our GPU context. In theory they should coincide, but due to the way linux works it's possible for timing to affect that.

That said, it's a bit surprising that using `--foreground` fixes it. The only change that should make is whether the main zed process is a child of your terminal or not (though I guess it could also affect timing subtly...)

**Comment by luka-hash** [comment]
> ```shell
> $ pacman -Q hyprland
> hyprland 0.41.0-1

I'm on Wayland, Hyprland 0.41.2-1 (latest).

**Comment by BenAlexanderAU** [comment]
I still have the same issue (Wayland+Sway on Arch).

When opening zed from menu or command line, a blank window is opened as well (I believe I have seen the window title 'wlroots' assigned to this unwanted window)

With `--foreground` it loads as expected (no extra window created).

**Comment by luka-hash** [comment]
@BenAlexanderAU Are you on the latest version?

**Comment by BenAlexanderAU** [comment]
```
pacman -Q zed sway wayland
zed 0.143.7-2
sway 1:1.9-5
wayland 1.23.0-1
```

**Comment by ConradIrwin** [comment]
@BenAlexanderAU Is this specific to sway? If so, it's likely that we're doing something it's not expecting (or vice versa), and lets refactor this issue title to be about that.

One thing we do that is relatively unusual is create a GPU canvas; in theory that should be positioned over the top of our window, but window managers have been known to ignore our positioning requests.

**Comment by nikita-vanyasin** [comment]
Hi! I'm on Arch+Sway. Seeing same behavior: when executing zededitor, new instance of wlroots is started, causing new instance of sway to appear:
```
~> ps xwa | grep sway
   1400 tty1     Ssl+  10:26 sway
   1444 ?        S      0:00 swayidle -w timeout 900 swaylock -f -c 000000 timeout 1500 systemctl suspend before-sleep swaylock -f -c 000000 after-resume swaymsg input type:keyboard xkb_switch_layout 0
  45717 tty1     S+     0:00 swaybg -o * -c #000000 -o HDMI-A-1 -c #000000
  45719 tty1     Sl+    0:08 swaybar -b bar-0
  96808 ?        Sl     0:00 sway
  96832 ?        S      0:00 swaybg -o * -c #000000
  96859 ?        S      0:00 swayidle -w timeout 900 swaylock -f -c 000000 timeout 1500 systemctl suspend before-sleep swaylock -f -c 000000 after-resume swaymsg input type:keyboard xkb_switch_layout 0
  98788 ?        Sl     0:00 sway
  98823 ?        S      0:00 swaybg -o * -c #000000
  98843 ?        Sl     0:00 swaybar -b bar-0
  98851 ?        S      0:00 swayidle -w timeout 900 swaylock -f -c 000000 timeout 1500 systemctl suspend before-sleep swaylock -f -c 000000 after-resume swaymsg input type:keyboard xkb_switch_layout 0
```
 
With --foreground it works as expected.

**Comment by treeshateorcs** [comment]
i'm affected too. `--foreground` helps, but this new sway window opens other instances of swaybg, swaybar, swayidle, and swaylock. and it happens everytime i open a new zed window or project, so it becomes very difficult to work because of the cpu strain

**Comment by jm355** [comment]
I get this too. Happened when I opened zed via the desktop file, and when I did Ctrl+, to open the settings. Opens a whole new instance of sway with a bar, as well as runs startup scripts like launching my vpn and initialize my theme

**Comment by treeshateorcs** [comment]
the issue is still relevant

**Comment by SleepyYui** [comment]
Same issue here running hyprland:
```
❯ pacman -Q hyprland
hyprland 0.47.2-2
❯ zeditor -v
Zed 0.176.3 – /usr/lib/zed/zed-editor
```
`--foreground` doesn't help either.

**Comment by luka-hash** [comment]
This is still happening. From my understanding, the cause must be in the way zed interacts with wayland/hyprland(wm). Also, in my experience, running it from terminal `--foreground` works fine. Moreover, if I open it from wofi (just a wayland launched) (which uses .desktop file), I get the black window, and then if I open a folder from here, I get another black window :). Additionally (even if this might be a duplicate of some other issue, I think it is possibly connected), running it from .desktop file breaks lsp functionality (and iirc every functionality that spawns additional processes), but running it from a terminal with `--foreground` flag works fine.

**Comment by xab3r** [comment]
It is happening in macOS too

**Comment by danc86** [comment]
I came to this issue because I noticed a problem similar to some previous commenters. Invoking `zeditor` would start Zed but also open a new nested compositor (titled wlroots) would appear beside it. In my case I'm using River (another tiling Wayland compositor), autostarted from my `~/.zlogin` like this:

```
if [[ "$XDG_VTNR" -eq 1 ]] ; then
    river
fi
```

This is a pretty commonly recommended technique for autostarting Wayland compositors without a display manager. It's likely there are a lot of Sway/Hyprland/River users out there with a configuration like this.

But if I start a new login shell inside my River session (`zsh -l`) the shell will spawn a new nested instance of River.

So I think the bug is that something inside Zed is invoking a login shell in order to do something. Login shells are supposed to be only invoked by the login process, a program like Zed should not be starting login shells.

For now I have worked around it (or fixed it) by adding a condition on SHLVL in my `~/.zlogin`, to avoid nesting instances of River:

```
if [[ "$XDG_VTNR" -eq 1 && "$SHLVL" -eq 1 ]] ; then
    river
fi
```

**Comment by danc86** [comment]
I guess it's probably this one, which intentionally spawns an *interactive login shell* to grab environment variables: https://github.com/zed-industries/zed/blob/60ec55b1799d5d898921a230464ae361bfae85d9/crates/util/src/util.rs#L330

From what I can see this is skipped for `zeditor --foreground` which is why that works around the problem.

If Zed really needs to spawn an interactive login shell to grab environment variables like this, maybe it should start it from an empty environment, so that variables like `XDG_VTNR` are not inherited from the parent environment.

**Comment by treeshateorcs** [comment]
@danc86 nice debugging skills! but your workaround doesn't work for me for some reason. the only differences in my setup is that i have

```zsh
[[ -z $DISPLAY && $XDG_VTNR -eq 1 && $SHLVL -eq 1 ]] && exec sway 2> ~/.config/sway/sway.log
```

at the end of my ~/.zprofile

**Comment by kennylevinsen** [comment]
What Zed is doing is inappropriate: environments are inherited, and there is no appropriate way to "look up" or otherwise probe what an environment *should* be other than what was given at startup. An interactive shell should only be started when the shell is presented to the user to directly interact with. A *login* shell should only be started when the user directly logged into that shell (e.g., by `login(1)` or `sshd(1)`). It's a bug for Zed to start an interactive login shell in the background.

> p.p.s. apparently it has to do with how sway runs its bindsym commands

Sway runs `exec` commands the appropriate way, using `/bin/sh -c $CMD`. However, you are not testing for a login shell, and you're not testing for *wayland* display presence (`WAYLAND_DISPLAY`), only X11 display presence (`DISPLAY`), and you are not testing for the kernel console.

If you want to check that the shell is connected to the first kernel console TTY, the easiest check is to see if `tty` returns `/dev/tty1`. This will return either `not a tty` if there is no terminal attached, `/dev/pts/N` if there is a psuedo-terminal attached (e.g., terminal emulator or `sshd(1)`), or `/dev/ttyN` where N is something other than 1 if on another VT.

This should make any other tests unnecessary - none of them would be reliable anyway.

Just to clarify a few things:
1. A login shell is solely a shell run with `argv[0]` set to `-`, or with the `-l` argument, and should only be run if the user logs into said shell. It can be tested for with `shopt login_shell`.
2. An interactive shell is a shell started with no positional arguments and no `-c` argument, or the `-i` argument, and should only be run if the user is to interactively use said shell. It can be tested for by looking for `i` in `$-`.
3. `$SHLVL` is just the value of `$SHLVL` at the start of the shell +1. It has no special meaning, and if a shell is started in an environment that does *not* contain `$SHLVL` it will default to 1. If for example you use systemd system or user services to launch applications or display servers (including use of `systemd-run`), these will not have `SHLVL` set.

**Comment by ConradIrwin** [comment]
It sounds like we could probably avoid most of the problems by running the shell without any DISPLAY/WAYLAND_DISPLAY variables? 

I think we're out of luck on "just run the environment you're given" as many developer tools instruct people to "put this in your ~/.bashrc". This works if you run a terminal but if you launch Zed from your window manager, (which was started outside of the shell) then your PATH inside Zed is incorrect.

That said, I'm open to ideas that make Zed work more like opening gnome-terminal (or your favorite terminal editor).

**Comment by kennylevinsen** [comment]
> This works if you run a terminal but if you launch Zed from your window manager, (which was started outside of the shell) 

This is not generally true, most login managers will source profile, pam_env is active for any login manager when enabled, and setups using systemd user services will load whatever you want into env. This means that PATH is generally correct.

On the other hand, profile and rc files have never been written to run outside interactive login shells, and will in the best case mess up the environment a bit with duplicate entries, worst case launch duplicate applications and corrupt environment variables.

(`.bashrc` has never been an appropriate place to set PATH and numerous proper places exist, nor will the current code load that as it is shell dependent - so such code pasted from the net won't always work anyway)

> It sounds like we could probably avoid most of the problems by running the shell without any DISPLAY/WAYLAND_DISPLAY variables?

Hmm, it won't fix that profiles and rc files end up executing twice, messing up the environment or running other things that correctly assume that an interactive login shell is... Well, an interactive login shell.

Not to mention that the code also assumes the user-configured she'll is POSIX compliant, taking those exact arguments and having an `env` command giving output in a specific format, which also doesn't hold - plenty of shells that don't behave anything like that.

If this is needed for some users, making it optional, possibly with a default value triggered by `XDG_CURRENT_DESKTOP` being equal to gnome as GDM is the main login manager I can think of not sourcing profile, is probably the right solution. Additionally, moving away from trying to read the environment and instead prepending commands with sourcing the profile in a single `/bin/sh` instantiation *without* acting as an interactive login shell and without trying to call the possibly incompatible user she'll might be better. Or even better, allow specifying an arbitrary script to source for convenience.

(For the exact scripts shared above, a minor adjustment can work around the Zed bug, so making hacks specific for those doesn't give much.)

**Comment by ConradIrwin** [comment]
Thanks for clarifying. It looks like the login shell came from https://github.com/zed-industries/zed/commit/9407d86ce615fd13589f264e4c595a328effa0f1. If we can get less broken behavior by using a non-login shell it sounds like that would probably also fix most issues like this?

We do need to spawn a shell to get the environment (otherwise processes spawned from within Zed launched from the window manager don't act like processes spawned from a terminal), but not certain that login shell is needed.

**Comment by rossampro** [comment]
I am also getting this same issue while running hyprland on Gentoo. I opened this [ticket](https://github.com/zed-industries/zed/issues/30903) to log it along with my system information and it got closed as a duplicate of this ticket. Has there been any movement here?

**Comment by rossampro** [comment]
Alright quick update here, I was able to adjust my `.zprofile` to adapt to Zed launching a login shell. Here's what I did for my zprofile:

```bash
# Only start Hyprland if we're on TTY1 and it's not already running
if [ "$(tty)" = "/dev/tty1" ] && ! pgrep -x Hyprland >/dev/null; then
  exec dbus-run-session Hyprland
fi
```

Before it looked like this:
```bash
dbus-run-session Hyprland
```

Which I imagine is why another Hyprland session just launched on its own when Zed launched its login shell.

For my other hyprland users, if your login shell looked anything like mine, try giving my workaround a try. I still agree that Zed launching a login shell is prob not the best way to inherit environment variables, but this seemed to resolve the issue for me.

**Comment by notpeter** [comment]
I believe this may have been fixed.

We changed how we are inheriting environment variables when spawned from the cli (we aren't) and on startup we explicitly spawn a new login shell, cd into your project directory (to trigger direnv, etc) and to capture the environment on a per-workspace basic.

If you are still seeing this, please comment and I'm happy to reopen.
Thanks for reporting.

**Comment by ghost** [comment]
The issue is still present. I'm running `Zed 0.195.5 – /usr/lib/zed/zed-editor`. I'll take a look soon to see if there is something wrong with my environment (i.e. something new), and will share my findings as soon as possible. Sorry for the delayed response, and thanks for helping! 😅

**Comment by kyoduke** [comment]
This issue still happening on latest version

**Comment by ghost** [comment]
I'm currently on bspwm and when I was in awesomewm, this issue did not exist there. I think, it's happening because how different window manager handles a GUI application.

This blank screen is only available on the first 2-3 startups and it immediately goes away if I move the mouse or click on the keyboard. I'm using Zed 0.213.4 – /usr/lib/zed/zed-editor
