### ISSUE TITLE
margin padding on Linux

### ISSUE THREAD

**Issue by mwotton** [zed-industries/zed#13845]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Running Linux at commit c8b106245c7e62353e0cd595213b166e03378130 

there are margins around the window now, as shown in the screenshot. I'm running Xmonad as a window manager, if that's relevant.

I ran a git bisect, and the problem was introduced in this commit

➜ git bisect good
47aa761ca9dee79852056897090480ff7f5ba7a9 is the first bad commit
commit 47aa761ca9dee79852056897090480ff7f5ba7a9
Author: Mikayla Maki <mikayla@zed.dev>
Date:   Wed Jul 3 11:28:09 2024 -0700

### Environment

Zed: v0.144.0 (Zed Dev c8b106245c7e62353e0cd595213b166e03378130)
OS: Linux X11 linuxmint 21
Memory: 125.6 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![margins](https://github.com/zed-industries/zed/assets/68482/a47be209-a8ed-46da-ba08-ca6e5e347912)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by mwotton** [comment]
GTK_CSD=0 also fixes it but it's rather a large hammer.

**Comment by mwotton** [comment]
(possibly this is just CSD running as designed but if anyone knows how to turn it off, I'd be very grateful)

**Comment by apricotbucket28** [comment]
This should be fixed by https://github.com/zed-industries/zed/pull/13822

**Comment by mwotton** [comment]
confirm fixed at d01d76482d00e8388f68177f42e4c072f15f40a9 (current HEAD)

**Comment by eddy-geek** [comment]
I'm still seeing it on **zed 0.150.4** (auto-updated after intall from `install.sh`). Is it expected ?

*System: X11, KDE Neon, Plasma 6.1 on top of Ubuntu 22.04, kwin-x11 6.1.4*
