### ISSUE TITLE
CapsLock not working: Linux

### ISSUE THREAD

**Issue by cdelv** [zed-industries/zed#13936]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I installed Zed today (Jul 8) following the instructions for Linux:
rustup update
script/linux
./script/install-linux

After testing some things (This is my first time trying Zed) I noticed that CapsLock does not work. With or without Vim mode enable. Shift + Key works for Caps.

### Environment

Zed: v0.144.0 (Zed Dev c617d48e16c17a041d98dbe33a967dd1c1a35d13)
OS: Linux X11 pop 22.04
Memory: 27.1 GiB
Architecture: x86_64

Kernel: 6.9.3-76060903-generic
CPU: AMD Ryzen 9 6900HS Creator Editi 
GPU: NVIDIA GeForce RTX 3050 Mobile 
GPU: AMD ATI 04:00.0 Rembrandt

I can't tell if it's using the dedicated GPU or not.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by algo7** [comment]
In my case, I can't toggle and have to continuously hold down the `capslock` or  the `shift` button to be able to type upper case characters. I don't know if it's an intended behavior and can be customized or a bug.

### Environment
Zed: v0.144 via `curl https://zed.dev/install.sh | ZED_CHANNEL=preview sh`
OS: Ubuntu 22.04.2 LTS
Desktop Environment: X11
Memory: 64 GiB
Architecture: x86_64

Kernel: 6.5.0-41-generic
CPU: AMD Ryzen 9 5900x
GPU: Nvidia GeForce RTX 3080

**Comment by SHREYAS290601** [comment]
Temp fix: use shift + capslock, works on ubuntu zed 0.143

**Comment by inteltank1** [comment]
Hello, I believe this issue has been fixed on branch #14466 . If so, this issue can be closed.

Thanks.

**Comment by aztrock** [comment]
@SHREYAS290601 he is right

**Comment by theurzil** [comment]
Still experiencing this bug on Zed 0.196.7.
Caps Lock doesn't work at all - pressing it has no effect. Shift + key works fine for caps.
Environment:

OS: Ubuntu 24.04
Kernel: 6.11.0-2
WM: i3
CPU: Intel i5-9500
