### ISSUE TITLE
Linux: Zed cannot find user fonts

### ISSUE THREAD

**Issue by rpbaptist** [zed-industries/zed#14324]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

My fonts are in `$HOME/.local/share/fonts`, but Zed cannot see them.

When I try to set my font to one of these I see an error and it states all the fonts it found on my system, but my user fonts are missing.

### Environment

Zed: v0.143.7 (Zed)
OS: Linux X11 ubuntu 24.04
Memory: 31 GiB
Architecture: x86_64

**Comment by florenzthedev** [comment]
I think I have run into this issue as well and wanted to provide more insight. Zed is only missing some but not all of the fonts installed to `$HOME/.local/share/fonts` for me. I have several fonts installed there, Atkinson Hyperlegible is detected and can be used but Intel One Mono is completely missing. Both fonts show up in other programs and in `fc-list`, both fonts are OTF not TTF. 

### Environment
Zed: v0.146.5
OS: Linux Wayland Debian 12
Memory: 16GB
Architecture: x86_64

**Comment by florenzthedev** [comment]
It looks like this was an issue with cosmic-text and is fixed in the newest release of cosmic-text. I have created a pull request to update cosmic-text: PR [#15748](https://github.com/zed-industries/zed/pull/15748)

**Comment by notpeter** [comment]
Here's the upstream issue I think we're waiting on:
- https://github.com/pop-os/cosmic-text/pull/296

**Comment by not-a-cowfr** [comment]
issue still exists for me

Zed: v1.8.2+stable (Zed) 
OS: Linux Wayland nixos 26.11
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-U) || Intel open-source Mesa driver || Mesa 26.1.2

| Font List | Zed Error |
|--------|--------|
| <img width="334" height="725" alt="Image" src="https://github.com/user-attachments/assets/ebbe8bcd-33de-46d3-8447-9efa50daf5d6" />  |  Value is not accepted. Valid values: ".SystemUIFont", ".ZedMono", ".ZedSans", "Adwaita Sans", "Arial", "Cantarell", "DejaVu Math TeX Gyre", "DejaVu Sans", "DejaVu Sans Mono", "DejaVu Serif", "FreeMono", "FreeSans", "FreeSerif", "Helvetica", "IBM Plex Sans", "Liberation Mono", "Liberation Sans", "Liberation Serif", "Lilex", "Noto Color Emoji", "Noto Sans", "Noto Sans CJK HK", "Noto Sans CJK JP", "Noto Sans CJK KR", "Noto Sans CJK SC", "Noto Sans CJK TC", "Noto Sans Mono CJK HK", "Noto Sans Mono CJK JP", "Noto Sans Mono CJK KR", "Noto Sans Mono CJK SC", "Noto Sans Mono CJK TC", "Noto Serif CJK HK", "Noto Serif CJK JP", "Noto Serif CJK KR", "Noto Serif CJK SC", "Noto Serif CJK TC", "Segoe UI", "TeX Gyre Adventor", "TeX Gyre Bonum", "TeX Gyre Chorus", "TeX Gyre Cursor", "TeX Gyre Heros", "TeX Gyre Heros Cn", "TeX Gyre Pagella", "TeX Gyre Schola", "TeX Gyre Termes", "Ubuntu", "Unifont".  |

**Comment by rvsfirecreeper** [comment]
I also have this issue
Zed v1.11.3
OS: Linux Wayland nixos 26.11
Memory: 32 GB
Architecture: x86_64
GPU: AMD Radeon RX 9070

**Comment by rvsfirecreeper** [comment]
This seems to specifically be an issue with user fonts, potentially having something to do with NixOS not storing fonts in the same place and expecting .local/share/fonts?
