### ISSUE TITLE
Title bar is transparent when the window is out of focus in linux

### ISSUE THREAD

**Issue by jsnjack** [zed-industries/zed#14955]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Title bar of zed editor window is transparent when it is not focused. The issue is happening on both wayland and x11

### Environment

Zed: v0.145.1 (Zed Preview)
OS: Linux Wayland fedora 40
Memory: 31.1 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot from 2024-07-22 12-00-18](https://github.com/user-attachments/assets/0a199e0b-6aff-4af0-8572-0cbe959a34c4)

**Comment by cemoktra** [comment]
As a workaround you can set the background to whatever fits your theme:
```
  "experimental.theme_overrides": {
    "title_bar.inactive_background": "#000000" // <= the color you need
  }
```

**Comment by jsnjack** [comment]
thanks, @cemoktra! definitely helps :+1:

**Comment by olumolu** [comment]
Why bot use gtk4 title bar

**Comment by Yazeed1s** [comment]
This is a theme issue, your theme does not set a color for ` "title_bar.inactive_background"`

**Comment by apricotbucket28** [comment]
This should be fixed now that https://github.com/zed-industries/zed/pull/15709 is merged (starting with version 0.148)

**Comment by msiler** [comment]
This is still happening for me. I'm on Zed version 0.150.4. Using Linux Mint 20, Cinnamon version 4.6.7, which is using x11.

**Comment by maxdeviant** [comment]
> This is still happening for me. I'm on Zed version 0.150.4. Using Linux Mint 20, Cinnamon version 4.6.7, which is using x11.

What theme are you using? And does it define a transparent or opaque color for `title_bar.inactive_background`?

**Comment by msiler** [comment]
I'm using https://github.com/adibhanna/catbox. It does not seem to provide that setting, but the fix mentioned above says it will provide a non-transparent default for that setting, so it seems like it should still work even if the theme doesn't provide this.
