### ISSUE TITLE
Key bindings do not work in `REPL Sessions` buffer

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#15135]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Open the `REPL Sessions` buffer
- Use the key binding of `pane::CloseActiveItem` to close it, or other key bindings

### Environment

Zed: v0.146.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by rgbkrk** [comment]
Not sure if this is already fixed, but I can't reproduce this.

**Comment by failable** [comment]
@rgbkrk This still happens to me in 

```
Zed: v0.147.2 (Zed Preview)
OS: macOS 14.6.0
Memory: 32 GiB
Architecture: x86_64
```

For example, the below key binding does not work for me in the `REPL Sessions` buffer

```
{
    "context": "Pane",
    "bindings": {
      "ctrl-x k": "pane::CloseActiveItem"
    }
  }
```

**Comment by rgbkrk** [comment]
Ah that might help me. I only tried with my default keybinding of `cmd-w` and triggering it via the command palette.

**Comment by failable** [comment]
Still exits.

**Comment by failable** [comment]
Still exits.

**Comment by failable** [comment]
Still here

```
Zed: v1.9.0+preview.313.0a64bc9d6dfa30e429767f2f62d0eb12efb7defa (Zed Preview) 
OS: macOS 26.5.1
Memory: 64 GiB
Architecture: aarch64
```
