### ISSUE TITLE
Deprecate Ctrl + O shortcut cause it used by nano!

### ISSUE THREAD

**Issue by tripolskypetr** [zed-industries/zed#15770]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`git config --global core.editor "nano"`

`git commit`

Ctrl + O, Ctrl + X

the spam appears

### Environment

![Screenshot from 2024-08-04 19-22-20](https://github.com/user-attachments/assets/4d865c70-c087-4127-95c8-65bfc628fe4f)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by XandrCopyrighted** [comment]
You can just open a terminal window and use nano there rather than in Zed

**Comment by tripolskypetr** [comment]
@XandrCopyrighted In that case, remove build in terminal from Zed...

This is defenitely the bug of Zed editor cause in future you would like to override <kbd>Ctrl</kbd> + <kbd>C</kbd> and this will make `webpack dev server` unstopable. The terminal should stop propagation of all keypress events to main window cause they should be sent to `stdin` of current terminal process if focused

**Comment by XandrCopyrighted** [comment]
> In that case, remove build in terminal from Zed...

Good comeback, ggs

**Comment by tripolskypetr** [comment]
Zed editor: Productive coding starts from learning vim

![image](https://github.com/user-attachments/assets/e392945b-8737-4ee6-8d43-95d000f146b7)

**Comment by XandrCopyrighted** [comment]
but I wouldn't "deprecate" the command in this case, I would just disable it

**Comment by tripolskypetr** [comment]
@XandrCopyrighted I just started to use Zed cause i tired from visual studio code auto updates. For example, they forced github sign in modal request which crashed vscode on my linux distro

All I want is a code editor which simple works out of a box without any extra configuration. So, deprecating or disabling by default does not matter

**Comment by XandrCopyrighted** [comment]
> They forced github sign in modal request...

Expected, I mean it's Microsoft

**Comment by apricotbucket28** [comment]
You can fix this by setting a custom keyboard shorcut: https://zed.dev/docs/key-bindings#forward-keys-to-terminal

**Comment by tripolskypetr** [comment]
@m4saurabh Looks nice, could you merge It to the repo?

**Comment by m4saurabh** [comment]
@tripolskypetr I don't think this is the best solution to the problem 😕, just like you I don't want to change every keymap used by the workspace to `null` in the terminal context. It should just work as expected by default.

> The proper solution would be the terminal should not inherit `"ctrl-*"` key maps but it can inherit `"ctrl-shift-*"` the same behaviour for the `alt` key

**Comment by twz123** [comment]
It's _very_ hard to come up with a comprehensive list of all the possible shortcuts of all the TUIs I use, so that II cann add those to my Zed config.

I think it'd be nice to have a seeting to reverse the shortcut behavior for the terminal view: As long as the terminal is focused, let it handle all the shortcuts, except the "whitelisted" ones, which will then be processed by Zed. Another approach could be an "escape" shortcut, to ask Zed to explicitly process the next shortcut, or something along those lines ...

**Comment by JonGretar** [comment]
Should this task be closed @JosephTLyons and marked as #wontfix or something.
This clearly won't be done. And the issue list is getting a bit unwieldy.

**Comment by tripolskypetr** [comment]
@JonGretar 
Actually monitoring this issue cause Zed Terminal UI/UX is weird.

May be it a super fast clean code solution. But, untill the terminal is unusable, I am going to continue using super slow ditry code VSCode :-)

**Comment by notpeter** [comment]
Sorry this stayed open so long.
This is really one-line fix and sane user-friendly default fixed by:
- https://github.com/zed-industries/zed/pull/26479

It'll be available in Zed v0.178.0 (out in 2wks) and in the meantime you can use the following workaround in your local keymap:

```
  {
    "context": "Terminal",
    "bindings": {
      "ctrl-o": ["terminal::SendKeystroke", "ctrl-o"]
    }
  }
```

Thanks!

**Comment by tripolskypetr** [comment]
The fake fix still appear

https://github.com/zed-industries/zed/issues/26018
