### ISSUE TITLE
Tasks ignoring trap signals

### ISSUE THREAD

**Issue by Emc2356** [zed-industries/zed#16590]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

i am using this header file to programmatically break into the debugger https://github.com/scottt/debugbreak/blob/master/debugbreak.h
when i run that program from the terminal or the integrated terminal and i hit a debug break and i am not running the debugger it says `Trace/breakpoint trap (core dumped)` but when i run the same program from the tasks it just hangs.
running from tasks:
![image](https://github.com/user-attachments/assets/270438aa-55bb-4f7d-b5d4-f785eb0f6630)
running from integrated terminal:
![image](https://github.com/user-attachments/assets/a46cef1f-570e-4b4e-b0a5-b86b6efe1a24)

### Environment

Zed: v0.150.0 (Zed Preview)
OS: Linux X11 endeavouros unknown
Memory: 7.6 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 620 (WHL GT2) || Intel open-source Mesa driver || Mesa 24.1.6-arch1.1

**Comment by SomeoneToIgnore** [comment]
The last one is supposedly fixed by https://github.com/zed-industries/zed/pull/16847 and comes with the next Preview this Wednesday.

**Comment by Emc2356** [comment]
Closing this as it seams to have been resolved by pull #16847

**Comment by fitz123** [comment]
`Zed Preview 0.153.4`
Looks like issue is still here, can't terminate task(
