### ISSUE TITLE
Bad kerning in integrated terminal

### ISSUE THREAD

**Issue by lixiaoyan** [zed-industries/zed#16869]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="317" alt="image" src="https://github.com/user-attachments/assets/cb535dbc-8ff6-40c6-ab28-350006e56ed1">

⬆️ Vanilla Alacritty
⬇️ Integrated terminal in Zed

Zed config:
```json
{
  "buffer_font_family": "Iosevka Fixed",
  "buffer_font_size": 11
}
```

Alacritty config:
```toml
[font]
normal = { family = "Iosevka Fixed" }
size = 11
```

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 13.6.9
Memory: 32 GiB
Architecture: x86_64

**Comment by lixiaoyan** [comment]
It appears to be related to non-integral character coordinates. The font in my screenshot, Iosevka, has an exact aspect ratio of 1:2. That is why characters are grouped in twos.

<img width="90" alt="image" src="https://github.com/user-attachments/assets/b06d0558-6a2b-4b40-a4c1-ee8bc72fc4e5">

⬆️ When the font size is set to 11, the y positions for each character are 0, 5.5, 11, 16.5,...

<img width="98" alt="image" src="https://github.com/user-attachments/assets/8e2f795b-8463-464f-8333-fe07319f8bb0">

⬆️ This problem does not occur when the font size is set to an even number.

**Comment by edwloef** [comment]
I can confirm this using Cascadia Code, which has an aspect ratio of 1200:2048 (75:128), at a font size of 16. This is very apparent when drawing box characters, such as when running [dust](https://github.com/bootandy/dust):
![image](https://github.com/user-attachments/assets/f0c04ca1-93dd-4311-9151-7bfae5b3834b)

**Comment by edwloef** [comment]
This is still reproducible.

**Comment by ConradIrwin** [comment]
Fixed by #33345  I think

**Comment by lixiaoyan** [comment]
@ConradIrwin Unfortunately, there is still an issue with the character placement. Should I raise another issue?

https://github.com/user-attachments/assets/e36163ce-0614-4680-9fc1-72b0fb327aba

Zed Preview 0.195.0, Font: Iosevka, Size: 15

**Comment by ConradIrwin** [comment]
@alisinabh do you know if we could use a single span for rebase in this case?

**Comment by alisinabh** [comment]
@ConradIrwin I think [this is](https://github.com/zed-industries/zed/blob/main/crates/terminal_view/src/terminal_element.rs#L130) the culprit. We should remove flooring that value.

I have removed it locally and this seems to be fixing the case @lixiaoyan mentioned.
