### ISSUE TITLE
Mouse Pointer wrong size (Linux)

### ISSUE THREAD

**Issue by mosenturm** [zed-industries/zed#17771]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I build zed from github repo. Since about commit f92d0de the mouse pointer is more than double size in the zed window.

### Environment

```
            .-/+oossssoo+/-.               andreas@AK-TUXEDO
        `:+ssssssssssssssssss+:`           -----------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.4 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: TUXEDO Aura 15 Gen1
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.8.0-101041-tuxedo
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 2 hours, 14 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3176 (dpkg), 22 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 42.9
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Nordic-darker-v40 [GTK2/3]
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: WhiteSur-dark [GTK2/3]
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: WezTerm
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: AMD Ryzen 7 4700U with Radeon Graphics (8) @ 2.000GHz
    .ossssssssssssssssssdMMMNysssso.       GPU: AMD ATI 05:00.0 Renoir
      -+sssssssssssssssssyyyssss+-         Memory: 13799MiB / 31458MiB (43%)
        `:+ssssssssssssssssss+:`           Battery0: 72% [Not charging]
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![IMG_20240910_160010](https://github.com/user-attachments/assets/59b2faf5-748e-4f78-977d-446304fd70db)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by inluxc** [comment]
Having the same issues

**Comment by notpeter** [comment]
I think this is possibly the PR responsible for the regression:
- https://github.com/zed-industries/zed/pull/17496

Which was a fix for:
- https://github.com/zed-industries/zed/issues/13258

**Comment by inluxc** [comment]
> I think this is possibly the PR responsible for the regression:
> 
> * [Fix blurry cursor on Wayland at a scale other than 100% #17496](https://github.com/zed-industries/zed/pull/17496)
> 
> Which was a fix for:
> 
> * [Blurry mouse pointer on Wayland #13258](https://github.com/zed-industries/zed/issues/13258)

Nop, not Blurry BUT BIGGGGGG

And I'm running the latest version...

**Comment by mosenturm** [comment]
> I think this is possibly the PR responsible for the regression:
> 
> * [Fix blurry cursor on Wayland at a scale other than 100% #17496](https://github.com/zed-industries/zed/pull/17496)
> 
> Which was a fix for:
> 
> * [Blurry mouse pointer on Wayland #13258](https://github.com/zed-industries/zed/issues/13258)

This commit does the error. The last working commit is: f92d0de.

**Comment by finnar-bin** [comment]
Experiencing the same issue on linux with wayland. Weird workaround I found was to start the gnome screen recorder, stop the recorder then the cursor goes back to the normal size lol. But when opening a new zed window, I'll have to do those steps again to "fix" it.

**Comment by Megadash452** [comment]
Having same issue.

> Experiencing the same issue on linux with wayland. Weird workaround I found was to start the gnome screen recorder, stop the recorder then the cursor goes back to the normal size lol. But when opening a new zed window, I'll have to do those steps again to "fix" it.

This did not work for me.

**Comment by sausir1** [comment]
Same here with very big mouse. After upgrading to 153.6 the cursor gets really big, first noticed it on `Preview` release, but now it's also in a stable oneSame here with very big mouse. After upgrading to 153.6 the cursor gets really big

**Comment by mosenturm** [comment]
> Experiencing the same issue on linux with wayland. Weird workaround I found was to start the gnome screen recorder, stop the recorder then the cursor goes back to the normal size lol. But when opening a new zed window, I'll have to do those steps again to "fix" it.

Have tried, but did not work for me. 
Zed was a good editor but since the assistant is first prio, everything else takes a backseat. Unfortunately, for me Zed has been unusable for the past 10 days..

**Comment by sausir1** [comment]
Don't really know, but this seems to be the issue:
![image](https://github.com/user-attachments/assets/2ddf8111-397a-4859-9fe5-2e23a5967a39)
 It sets the scale to 2, without doing any checks for the zoom/scale level

**Comment by inluxc** [comment]
I don't think so, were is the list of available setting in ZED

https://github.com/zed-industries/zed/blob/main/assets/settings/default.json

**Comment by sausir1** [comment]
@inluxc I meant to add a setting for cursor scale, that should fix the problem

**Comment by inluxc** [comment]
> @inluxc I meant to add a setting for cursor scale, that should fix the problem

That's one way to go

**Comment by juliancervos** [comment]
> @inluxc I meant to add a setting for cursor scale, that should fix the problem

+1

I'm having the same issue. I was just checking if there is any config property that could be related to this, but all the cursor-related ones are about the editor or terminal cursor, not the mouse cursor: `cursor_shape`, `cursor_blink`... (see [Configuring Zed](https://zed.dev/docs/configuring-zed)).

In any case, it seems like the natural place to go to try and fix the problem.

**Comment by aiden3c** [comment]
Same issue, kinda funny but also annoying lol

**Comment by ruskiiamov** [comment]
Same issue. Ubuntu 22.04 with Wayland

**Comment by MartinGamesCZ** [comment]
Same, firstly noticed on beta, now even in stable

**Comment by renevisser** [comment]
Same here. HUGE pointer on Wayland.

**Comment by MartinGamesCZ** [comment]
Tried changing the cursor size to half (12), that worked. I wanted to add setting for it and maybe even create PR, but i couldn't figure out how to get App context (for reading settings) inside WaylandClient (where Cursor::new is called)

**Comment by RSeidelsohn** [comment]
![grafik](https://github.com/user-attachments/assets/67b4c327-f9ec-492a-a6a5-0529464b5668)
Turning on "Fractional scaling" on my Ubuntu 22.04 fixed the issue for me.

**Comment by MartinGamesCZ** [comment]
Can confirm, also works for me.

Maybe adding some condition for that would fix the issue? I don't have enough experience with rust tho

**Comment by mosenturm** [comment]
> Turning on "Fractional scaling" on my Ubuntu 22.04 fixed the issue for me.

Can also confirm.

**Comment by zsnero** [comment]
This worked for me.

`gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`

**Comment by inluxc** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/870515/369696234-67b4c327-f9ec-492a-a6a5-0529464b5668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzc5ODksIm5iZiI6MTcyNzA3NzY4OSwicGF0aCI6Ii84NzA1MTUvMzY5Njk2MjM0LTY3YjRjMzI3LWY5ZWMtNDkyYS1hNmE1LTA1Mjk0NjRiNTY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwNzQ4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2EwMTRmMWYyNzdiYWE1Yjc5NjNkNGNhODg1NmMyZTNiYjZjYWQxMGRhYzlmMmQ2ODY0MmIxZTRlNTY1ZjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.glDtFbgGw1v6ULobrNMKE6z0aEqdfNbpmtov8GHMMGg) Turning on "Fractional scaling" on my Ubuntu 22.04 fixed the issue for me.

Yep its works

**Comment by aiden3c** [comment]
Don't have that option on Debian Bookworm, but zsnero's command solution worked.

**Comment by mullr** [comment]
I'm seeing a small cursor. KDE on Wayland, Debian Bookworm, AMD.

**Comment by tunnckoCore** [comment]
Same here. Arch Wayland KDE on AMD. Not using any specific scaling. Any solutions for KDE?

Just updated to 153.7 and the issue remains.

**Comment by leninrkb** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/870515/369696234-67b4c327-f9ec-492a-a6a5-0529464b5668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTk5NjMsIm5iZiI6MTcyNzMxOTY2MywicGF0aCI6Ii84NzA1MTUvMzY5Njk2MjM0LTY3YjRjMzI3LWY5ZWMtNDkyYS1hNmE1LTA1Mjk0NjRiNTY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwMzAxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yzc4MzRlZDM1OWU0MzA1MDY0NWE1ZmExN2QyZTE3OTc4ZTgxYjc0N2Y2NjgzZWQ0N2Q0Y2M4NGJjMjExNzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2eanrc2mwKGwEznaJ3HYkOTC8n5cMQjZf7NxfDktO04) Turning on "Fractional scaling" on my Ubuntu 22.04 fixed the issue for me.

YUUPP it works for me as well !!!! THX <3

**Comment by inneroot** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/870515/369696234-67b4c327-f9ec-492a-a6a5-0529464b5668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NzY4NDcsIm5iZiI6MTcyNzY3NjU0NywicGF0aCI6Ii84NzA1MTUvMzY5Njk2MjM0LTY3YjRjMzI3LWY5ZWMtNDkyYS1hNmE1LTA1Mjk0NjRiNTY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwNjA5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjcyZGE1NjRlZGM1M2FlMjViN2ZhZTEyYWQ2MzFlODJmYjgwNDliYzAwOGIxM2NhNmVkZWNiMjUyNzA1Mzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ljgy8ZuRCV9NRYVLj_iP57vSxmNj4wowEtS8y3GOpFg) Turning on "Fractional scaling" on my Ubuntu 22.04 fixed the issue for me.

Unfortunately there is no such setting in Debian 12 GNOME 43.9

**Comment by aiden3c** [comment]
> Unfortunately there is no such setting in Debian 12 GNOME 43.9

Try zsnero's solution, worked for me using Debian 12 Gnome

**Comment by tunnckoCore** [comment]
funny thing is.. it's getting smaller LOL

**Comment by garcia-andy** [comment]
Enabling "Fractional Scaling" worked for me, but until now I've been using the WAYLAND_DISPLAY="" environment variable to force it to use X11, and it worked for me too

**Comment by inneroot** [comment]
> > Unfortunately there is no such setting in Debian 12 GNOME 43.9
> 
> Try zsnero's solution, worked for me using Debian 12 Gnome

tried and it not worked. Tried again today and it worked :D, may be done something wrong first time.

**Comment by JosephTLyons** [comment]
Does this need to be reopened @mikayla-maki?

**Comment by mikayla-maki** [comment]
This one was fixed by the recent revert :)

**Comment by kdipto1** [comment]
> This one was fixed by the recent revert :)

But the issue is still there in my system. 
System OS: Zorin os 17.2 core

**Comment by diegorchaves** [comment]
> This worked for me.
> 
> `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`

Tried on debian 12, but i get the error: 

failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY

Does anyone know how to solve it?
