### ISSUE TITLE
Zed only starts when forced to use XWayland

### ISSUE THREAD

**Issue by tancop** [zed-industries/zed#18570]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm on KDE with Wayland as the display server. Zed doesn't open when I start it as a native Wayland app. Running `~/.local/zed.app/libexec/zed-editor` exits with code 1 and prints this:
```
Zed failed to open a window: NoSupportedDeviceFound. See https://zed.dev/docs/linux for troubleshooting steps.
```
If I run it with `env -u WAYLAND_DISPLAY zed` it works just fine. `Zed.log` has ` x11: compositor present: true, gtk_frame_extents_supported: true` as one of the first lines so Zed crashes before it can overwrite the log from a previous successful run.

### Environment

Zed: v0.154.3 (Zed)
OS: Linux X11 arch unknown
Memory: 15 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1650 || NVIDIA || 560.35.03

**Comment by jansol** [comment]
Hmm, works fine for me in a Wayland session on Ubuntu and a slightly older card. However I had to force Zed to use the NVIDIA GPU with VK_ICD_FILENAMES since the main GPU that is running the Wayland session is a Radeon with the open source driver - not sure if this is relevant.

Zed: v0.156.0 (Zed Dev 7ce8797d78794f5a53e7a7d113e4c14a65e6297f)
OS: Linux Wayland ubuntu 24.04
Memory: 31.3 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1060 3GB || NVIDIA || 550.107.02

### Another  thing to check

Is your user part of the `render` group? I've seen the NVIDIA driver logging some errors and missing some functionality if you are not part of that group since means you don't have access to certain kernel interfaces for controlling the GPU.

**Comment by jansol** [comment]
Hmm that's interesting. Still works fine on my NixOS build from just a couple of days earlier than yours:

```
zeditor: /nix/store/wslhcisvnslqgjwyrkrnkjkd14cylxsv-zed-editor-0.154.1/bin/zeditor
Zed: v0.154.1 (Zed)
OS: Linux Wayland nixos 24.11
Memory: 125.7 GiB
Architecture: x86_64
GPU: AMD Radeon RX 7900 XTX (RADV NAVI31) || radv || Mesa 24.2.2
```

I wonder if it's some race condition related to wayland surfaces? 

Would you two mind trying to run zed with `RUST_LOG=debug zeditor --foreground` and posting the output? Or at least just the interesting part (should be the end of it), since it can be quite verbose.

**Comment by tancop** [comment]
I tried the rust log thing and the only part that mentions graphics is this:
```
[2024-10-02T10:14:09+02:00 INFO  blade_graphics::hal::init] Adapter: "NVIDIA GeForce GTX 1650"
[2024-10-02T10:14:09+02:00 DEBUG isahc::handler] Host api.zed.dev:443 was resolved.
[2024-10-02T10:14:09+02:00 WARN  blade_graphics::hal::init] Rejected for not presenting to the window surface
[2024-10-02T10:14:09+02:00 DEBUG isahc::handler] IPv6: 2606:4700:20::681a:b50, 2606:4700:20::ac43:49a9, 2606:4700:20::681a:a50
[2024-10-02T10:14:09+02:00 DEBUG isahc::handler] IPv4: 104.26.11.80, 104.26.10.80, 172.67.73.169
[2024-10-02T10:14:09+02:00 DEBUG isahc::handler]   Trying [2606:4700:20::681a:b50]:443...
[2024-10-02T10:14:09+02:00 DEBUG isahc::handler] Hostname 'api.zed.dev' was found in DNS cache
[2024-10-02T10:14:09+02:00 DEBUG isahc::handler]   Trying [2606:4700:20::681a:b50]:443...
Zed failed to open a window: NoSupportedDeviceFound. See https://zed.dev/docs/linux for troubleshooting steps.
```
The rest is debug spam from `cranelift_codegen` and `wasmtime_cranelift`. Looks like zed doesn't set up the wayland surface correctly so the compositor never creates a window.

**Comment by prinzhoefte** [comment]
> Hmm that's interesting. Still works fine on my NixOS build from just a couple of days earlier than yours:

It was working for me a few days ago as well. Some dependency probably broke it in the last two days at max.

**Comment by tancop** [comment]
Looks like this is fixed in [preview 0.156.0](https://github.com/zed-industries/zed/releases/tag/v0.156.0-pre). Zed opens and works like normal with `WAYLAND_DISPLAY=wayland-0`.

**Comment by quantum9Innovation** [comment]
I am running Zed 0.162.5 and I still have this issue with `WAYLAND_DISPLAY=wayland-1`.
Output from `zeditor --foreground` is:

```
wp_linux_drm_syncobj_manager_v1#43: error 0: Surface already has a syncobj attached
[2024-11-28T21:35:06-05:00 ERROR zed::reliability] {
  "thread": "main",
  "payload": "called `Result::unwrap()` on an `Err` value: ERROR_SURFACE_LOST_KHR",
  "location_data": {
    "file": "/build/zed-editor-0.162.5-vendor/blade-graphics-0.5.0/src/vulkan/init.rs",
    "line": 930
  },
  "backtrace": [
    "core::panicking::panic_fmt",
    "core::result::unwrap_failed",
    "blade_graphics::hal::init::<impl blade_graphics::hal::Context>::resize",
    "gpui::platform::blade::blade_renderer::BladeRenderer::new",
    "gpui::platform::linux::wayland::window::WaylandWindow::new",
    "<gpui::platform::linux::wayland::client::WaylandClient as gpui::platform::linux::platform::LinuxClient>::open_window",
    "gpui::platform::linux::platform::<impl gpui::platform::Platform for P>::open_window",
    "gpui::window::Window::new",
    "gpui::app::async_context::AsyncAppContext::open_window",
    "workspace::Workspace::new_local::{{closure}}::{{closure}}",
    "async_task::raw::RawTask<F,T,S,M>::run",
    "<gpui::platform::linux::wayland::client::WaylandClient as gpui::platform::linux::platform::LinuxClient>::run",
    "gpui::platform::linux::platform::<impl gpui::platform::Platform for P>::run",
    "gpui::app::App::run",
    "zed::main",
    "std::sys::backtrace::__rust_begin_short_backtrace",
    "std::rt::lang_start::{{closure}}",
    "std::rt::lang_start_internal",
    "main",
    "__libc_start_call_main",
    "__libc_start_main_alias_2",
    "_start"
  ],
  "app_version": "0.162.5",
  "release_channel": "Zed",
  "os_name": "Linux Wayland",
  "os_version": "nixos 25.05",
  "architecture": "x86_64",
  "panicked_on": 1732847706037,
}
```

I am running this on my integrated GPU, but Zed works fine on Wayland if I run this on my NVIDIA GPU. It also works fine if I run it without Wayland on my integrated GPU, but the display resolution is extremely low and there are many visual artifacts.
