### ISSUE TITLE
`Unexpected end of file` errors when launching terminal after self-updating (Linux)

### ISSUE THREAD

**Issue by Jeff-SearchPilot** [zed-industries/zed#18614]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

this is related to zed updating itself...

    - install zed using the install script (`https://zed.dev/install.sh`)
        all ok, no errors when launching a terminal
    - let zed update itself. Open a terminal..

![Screenshot from 2024-10-02 09-17-09](https://github.com/user-attachments/assets/f7b29d95-2b03-444c-b206-fc085b8923e3)

    - rerun install script and relaunch zed. Open a terminal and the errors no longer appear

Running Fedora 40, with zsh and others have reported similar issues in #14179 (which is similar but apparently unrelated)

### Environment

Zed: v0.155.2 (Zed Preview)
OS: Linux Wayland fedora 40
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) Xe Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 24.1.7

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment]
Curious what your default shell is (`getent passwd $USER`) as those errors show `/bin/sh` and most folks use `bash` or `zsh`.  Can you paste the complete set of errors shown when you open a clean terminal? (a new release should be out shortly today which will trigger an auto-update).

**Comment by notpeter** [comment]
> No idea what's calling `/usr/bin/sh`, I assume its something internal to zed since it only occurs after it self-updates

There's no explicit mention of `/usr/bin/sh` in the zed repo so Zed is discovering that shell specified somewhere on your system (perhaps incorrectly).

1. Does the issue only occur when Zed relaunches itself after automatic update?
2. Does it also occur if you quit Zed and spawn from the command line?
3. Does it also occur if you quit Zed and spawn it from the desktop shortcut?

On Fedora 40 `/usr/bin/sh` is a symlink to `/usr/bin/bash`.  I wonder if you have something inside your `.profile` or `/etc/profile` which is zsh-specific and causing bash to puke. 

My apologies for what might sound patronizing by asking again, can you confirm your default shell is actually zsh by running `chsh` and seeing what it says there?  I only ask again because I have previously encountered people who were using zsh but had not configured as their default shell (just being launched as a subprocess from .bashrc or whatever) and I want to explicitly rule that out.

Could you also try explicitly defining your [Terminal Shell](https://zed.dev/docs/configuring-zed#terminal-shell) in zed settings?
```
{
  "terminal": {
    "shell": {
      "program": "zsh"
    }
  }
}
```

1. Can you see if that helps?
2. Does setting it to `bash` trigger than issue again?

**Comment by Jeff-SearchPilot** [comment]
Oddly enough, I've noticed this morning that the error has disappeared without me having to rerun the install script. So it could well be related to that initial run after the update. I'll do some more testing when the next update is pushed out and have set the shell to `zsh` as suggested.

**Comment by Jeff-SearchPilot** [comment]
Confirmed that the issue only occurs the first time zed runs after an auto-update. Closing and relaunching results in normal behaviour with no errors. Launching from terminal/desktop shortcut doesnt make a difference.

Also double checked and confirmed zed is 100% my shell. Setting the terminal shell in zed settings also had no affect.

**Comment by Jeff-SearchPilot** [comment]
This appears to have resolved itself in one of the recent releases. I'll double check when the next release is made but i think this can be closed.

**Comment by Jeff-SearchPilot** [comment]
:disappointed: still there in 0.161.1. Can you re-open @notpeter?

**Comment by notpeter** [comment]
I can. Can you remove ~/.local/zed.app, downloading a old release binary from our GitHub releases page (make sure not to download -pre releases, those are Preview), manually unpacking it a launching.

It should then find an update and install it. If then the issue recurs on restart it means we can  reliably reproduce the issue.

If you have a way to reproduce on demand perhaps then we can see if we can isolate the issue (e.g. try with an empty .profile, hop on a screen share, etc).

**Comment by Jeff-SearchPilot** [comment]
Ok, can shed a little more light on this now. Firstly - it is reproducible following your instructions (although I *am* using the preview versions, so downloaded that). After auto-updating from an older version, the errors appear until I completely quit all zed instances and restart - then the errors disappear. I also noticed that the same error appeared in a zed shell when running some other commands. 

If I compare the output of `env` between a working and broken instance these lines appear at the top in the broken session..

```
 __lmod_my_status=$?;
 if [ -n "${__lmod_sh_dbg:-}" ]; then
 echo "Shell debugging restarted" 1>&2;
 set -$__lmod_sh_dbg;
 fi;
 unset __lmod_sh_dbg;
 return $__lmod_my_status
}
 __lmod_sh_dbg='x'
 ;;
 esac;
 fi;
 if [ -n "${__lmod_sh_dbg:-}" ]; then
 set +$__lmod_sh_dbg;
 echo "Shell debugging temporarily silenced: export LMOD_SH_DBG_ON=1 for Lmod's output" 1>&2;
 fi;
 eval "$($LMOD_CMD shell "$@")" && eval "$(${LMOD_SETTARG_CMD:-:} -s sh)";
```

and further down..

```
BASH_FUNC_ml%%=() {  eval "$($LMOD_DIR/ml_cmd "$@")"
}
BASH_FUNC_module%%=() {  if [ -z "${LMOD_SH_DBG_ON+x}" ]; then
 case "$-" in 
 *v*x*)
```


the top bit seems a bit odd - theres a `esac` without an opening `case`. I have no idea where this is coming from - presumably zed?

**Comment by Jeff-SearchPilot** [comment]
I just re-read the error...

```
/usr/bin/sh: module: line 3: syntax error: unexpected end of file
```

` module` in this case is the function declared in the `BASH_FUNC_module` env var (:vomiting_face:)

I'm wondering if that first section in my previous comment actually belongs to the BASH_FUNC_module definition. Anyway - I have checked all files in $HOME and cannot find any reference to it

**Comment by Jeff-SearchPilot** [comment]
Fixed it! There is some kind of conflict between the `Lmod` package which provides a function called `module` (what a silly name!). In my case I didnt need it so just removed it.

```
Name           : Lmod
Epoch          : 0
Version        : 8.7.53
Release        : 1.fc41
Architecture   : x86_64
Download size  : 272.5 KiB
Installed size : 1.3 MiB
Source         : Lmod-8.7.53-1.fc41.src.rpm
Repository     : updates
Summary        : Environmental Modules System in Lua
URL            : https://www.tacc.utexas.edu/tacc-projects/lmod
License        : MIT AND LGPL-2.0-only
Description    : Lmod is a Lua based module system that easily handles the MODULEPATH
               : Hierarchical problem.  Environment Modules provide a convenient way to
               : dynamically change the users' environment through modulefiles. This includes
               : easily adding or removing directories to the PATH environment variable.
               : Modulefiles for library packages provide environment variables that specify
               : where the library and header files can be found.
Vendor         : Fedora Project
```

I have no idea why auto-updates cause this issue (maybe its doing something odd when `$SHLVL` is bigger?) but I dont think is a zed problem. Closing (again)

**Comment by lamyergeier** [comment]
I don't have lmod installed on Fedora 40, but still facing the error!

**Comment by kylelee** [comment]
Still facing same error

**Comment by notpeter** [comment]
See:
- https://github.com/zed-industries/zed/issues/27601
