### ISSUE TITLE
Remote development stops working unexpectedly

### ISSUE THREAD

**Issue by aevsai** [zed-industries/zed#19463]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I connect to my remote it starts fine, but then stops responding and freezes window controls so I have to close and reopen it from Dock -> Zed -> Close

### Environment

Zed: v0.157.5 (Zed)
OS: macOS 14.6.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-10-19T18:45:53.990279+03:00 [INFO] setting state to 'reconnecting'
2024-10-19T18:45:53.990663+03:00 [INFO] Trying to reconnect to ssh server... Attempt 1
2024-10-19T18:45:54.979617+03:00 [ERROR] Working directory: /home/artem/einclient Shell command: `zsh -i`, IOError: Failed to spawn command 'zsh': No such file or directory (os error 2)

Caused by:
    Failed to spawn command 'zsh': No such file or directory (os error 2)
2024-10-19T18:45:55.40714+03:00 [WARN] timed out waiting for formatting
2024-10-19T18:45:56.291218+03:00 [INFO] uploading remote development server (13574kb)
2024-10-19T18:45:56.991819+03:00 [WARN] timed out waiting for formatting
2024-10-19T18:46:01.231258+03:00 [WARN] timed out waiting for formatting
2024-10-19T18:46:03.153094+03:00 [INFO] uploaded remote development server in 6.86208275s
2024-10-19T18:46:04.260345+03:00 [INFO] Initializing default prettier with plugins {}
2024-10-19T18:46:04.260753+03:00 [ERROR] send failed because receiver is gone
2024-10-19T18:46:04.26081+03:00 [INFO] Initializing default prettier with plugins {}
2024-10-19T18:46:04.261225+03:00 [INFO] Initializing default prettier with plugins {}
2024-10-19T18:46:04.261659+03:00 [INFO] Initializing default prettier with plugins {}
2024-10-19T18:46:04.282804+03:00 [WARN] request completed with error: failed to connect to the server
2024-10-19T18:46:04.318888+03:00 [ERROR] no worktrees when constructing LocalLspAdapterDelegate
2024-10-19T18:46:04.427675+03:00 [INFO] language server 1: unregistered workspace/DidChangeWatchedFiles capability with id efb3576e-fff8-4c53-8b36-b3ee909e5829
2024-10-19T18:46:05.860035+03:00 [ERROR] (remote) proxy: attempted to reconnect, but no server running
2024-10-19T18:46:05.864664+03:00 [ERROR] failed to reconnect because server is not running
2024-10-19T18:46:05.865109+03:00 [INFO] setting state to 'server not running'
2024-10-19T18:46:06.296822+03:00 [WARN] timed out waiting for formatting
2024-10-19T18:46:06.31178+03:00 [WARN] timed out waiting for formatting
2024-10-19T18:46:22.514559+03:00 [ERROR] failed to send message: send failed because receiver is gone
2024-10-19T18:46:22.514676+03:00 [ERROR] failed to send message: send failed because receiver is gone
2024-10-19T18:46:22.5148+03:00 [ERROR] failed to send message: send failed because receiver is gone
</pre></details>

<details><summary>Zed.log</summary><pre>
2024-10-19T19:46:05.219162+03:00 [ERROR] (remote) proxy: failed to forward messages: proxy: failed to read message from stdout

Caused by:
    unexpected end of file

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   2: async_executor::Executor::spawn_inner::{{closure}}
   3: async_task::raw::RawTask<F,T,S,M>::run
   4: async_io::driver::block_on
   5: std::sys::backtrace::__rust_begin_short_backtrace
   6: core::ops::function::FnOnce::call_once{{vtable.shim}}
   7: std::sys::pal::unix::thread::Thread::new::thread_start
   8: start_thread
             at ./nptl/pthread_create.c:442:8
   9: thread_start
             at ./misc/../sysdeps/unix/sysv/linux/aarch64/clone.S:79, terminating...
2024-10-19T19:46:05.246231+03:00 [ERROR] proxy process terminated unexpectedly
</pre></details>

<details><summary>Zed.log</summary><pre>
2024-10-19T20:06:57.359038+03:00 [ERROR] Missed last 5 heartbeats. Reconnecting...
2024-10-19T20:06:57.359324+03:00 [INFO] setting state to 'reconnecting'
2024-10-19T20:06:57.359435+03:00 [INFO] Trying to reconnect to ssh server... Attempt 1
2024-10-19T20:06:59.139651+03:00 [INFO] uploading remote development server (13574kb)
2024-10-19T20:07:00.402936+03:00 [ERROR] Working directory: /home/artem/einclient Shell command: `<system defined shell>`, IOError: Failed to spawn command '/usr/bin/login': No such file or directory (os error 2)

Caused by:
    Failed to spawn command '/usr/bin/login': No such file or directory (os error 2)
2024-10-19T20:07:02.301109+03:00 [ERROR] Working directory: /home/artem/einclient Shell command: `<system defined shell>`, IOError: Failed to spawn command '/usr/bin/login': No such file or directory (os error 2)

Caused by:
    Failed to spawn command '/usr/bin/login': No such file or directory (os error 2)
</pre></details>

[zed-3.log](https://github.com/user-attachments/files/17446331/zed-3.log)

**Comment by aevsai** [comment]
oops, this may be caused by something else, got this error again
now with following logs
```
2024-10-19T19:46:05.219162+03:00 [ERROR] (remote) proxy: failed to forward messages: proxy: failed to read message from stdout

Caused by:
    unexpected end of file

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   2: async_executor::Executor::spawn_inner::{{closure}}
   3: async_task::raw::RawTask<F,T,S,M>::run
   4: async_io::driver::block_on
   5: std::sys::backtrace::__rust_begin_short_backtrace
   6: core::ops::function::FnOnce::call_once{{vtable.shim}}
   7: std::sys::pal::unix::thread::Thread::new::thread_start
   8: start_thread
             at ./nptl/pthread_create.c:442:8
   9: thread_start
             at ./misc/../sysdeps/unix/sysv/linux/aarch64/clone.S:79, terminating...
2024-10-19T19:46:05.246231+03:00 [ERROR] proxy process terminated unexpectedly
```

**Comment by aevsai** [comment]
happened again, most recent logs is
```
2024-10-19T20:06:57.359038+03:00 [ERROR] Missed last 5 heartbeats. Reconnecting...
2024-10-19T20:06:57.359324+03:00 [INFO] setting state to 'reconnecting'
2024-10-19T20:06:57.359435+03:00 [INFO] Trying to reconnect to ssh server... Attempt 1
2024-10-19T20:06:59.139651+03:00 [INFO] uploading remote development server (13574kb)
2024-10-19T20:07:00.402936+03:00 [ERROR] Working directory: /home/artem/einclient Shell command: `<system defined shell>`, IOError: Failed to spawn command '/usr/bin/login': No such file or directory (os error 2)

Caused by:
    Failed to spawn command '/usr/bin/login': No such file or directory (os error 2)
2024-10-19T20:07:02.301109+03:00 [ERROR] Working directory: /home/artem/einclient Shell command: `<system defined shell>`, IOError: Failed to spawn command '/usr/bin/login': No such file or directory (os error 2)

Caused by:
    Failed to spawn command '/usr/bin/login': No such file or directory (os error 2)
```

**Comment by mrnugget** [comment]
Can you try running Zed like this, connecting to your remote, and paste the logs?

```
RUST_LOG=debug,cranelift_codegen=error,h2=error,hyper_util=error,wasmtime=error,globset=error zed --foreground ssh://user@host/~/path-to-folder
```

**Comment by ConradIrwin** [comment]
Also, please update to 0.159.5 before trying this! We have fixed a very large number of bugs over the last two weeks.

**Comment by aevsai** [comment]
I have updated Zed to 0.159.5 and tested for a couple hours and it works fine! I would test more at this weekends and tell if issue still present. Thanks!

**Comment by ConradIrwin** [comment]
Great! Please reopen if you see problems.
