### ISSUE TITLE
zed disregards `file_scan_exclusions` at startup and deep-scans directories that were excluded

### ISSUE THREAD

**Issue by eric-seppanen** [zed-industries/zed#21040]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have been developing a fuse filesystem, and during development testing, I often mount to a path `mnt` right in my development tree. I added `mnt` to my `file_scan_exclusions` setting (and verified it disappears from the left pane as a result).

However, when I (re)start Zed (manually or because of an update), I can see in my fuse filesystem logs that Zed is deep-scanning the entire tree inside my fuse filesystem. Because this is a virtual filesystem that is arbitrarily large, this manifests as a blank editor window with an empty left pane and little functionality (e.g. I can't browse my project's files).

If I close the malfunctioning Zed window, the filesystem scanning continues: there is a `zed-editor` process in the background that keeps running until I unmount the fuse filesystem.

I can see (from my fuse filesystem logs) that it is traversing every directory and repeatedly trying to access `.git` and `.gitignore` in every possible path.

If I start the fuse filesystem after Zed is running, everything works normally.

I'm not sure how to share steps to reproduce this because running a fuse filesystem in the development tree is a bit exotic. My guess is that even without fuse, something like `strace` would be able to confirm that Zed is ignoring `file_scan_exclusions` and scanning excluded paths during some phase of startup? I'm open to ideas for gathering data that would help.

### Environment

Zed: v0.162.5 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-P) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.2

### If applicable, attach your Zed.log file to this issue.

Unfortunately, when this scan/hang occurs nothing is printed to `Zed.log`.

**Comment by notpeter** [comment]
I am able to reproduce:

```
cd /tmp
git clone git@github.com:zed-industries/extensions.git
cd extensions
git submodule init
git submodule update
mkdir -p .zed/
echo '{ "file_scan_exclusions": ["extensions"] }' > .zed/settings.json
zed .
```

It will take multiple seconds for Zed to load (scanning the excluded `extensions/`), then it will briefly show the project panel tree with the extensions folder before hiding it.

Note: this becomes less reproducible if you try and repeat this (I assume because the 15GB of submodules stick around in the file cache). But you should be able to reliably reproduce if you clone into a new directory.

Thank you for reporting.

**Comment by mgsloan** [comment]
The repro doesn't trigger a bug for me.  Maybe it got fixed by some other change to this code?  If I run with `RUST_LOG=debug` I see this in the logs:

> [2025-02-17T15:46:28-07:00 DEBUG worktree] skipping excluded child entry "extensions"

**Comment by eric-seppanen** [comment]
I just re-tested this on Zed 0.173.11 and it's still broken for me.

I would re-open this issue but I don't have permissions?

**Comment by eric-seppanen** [comment]
@mgsloan The `file_scan_exclusions` setting always hid the directories from *some* parts of the editor: for example, it's hidden from the left pane. Perhaps the log message is from that part?

I also tried `RUST_LOG=debug zed .` with no other editor windows running, but I didn't get debug logs. I see `using project environment variables from CLI. PATH="<my path>"` but `RUST_LOG` isn't shown.

**Comment by eric-seppanen** [comment]
Here's another way to see what's happening: run e.g. `inotifywatch -v -r extensions -t 30` to collect stats on what files are being accessed. (I was using the "extensions" example from above, but this should work on any directory.) With `inotifywatch` running, start `zed` in the parent directory, with a settings file that has the target directory `extensions` excluded.

When I do this, I see `inotifywatch` print a long dump of every directory being accessed by zed.

**Comment by mgsloan** [comment]
@eric-seppanen To see the logs in the terminal `--foreground` is needed, so `RUST_LOG=debug zed . --foreground`.

I tried `inotifywatch` with Peter's repro and I get "No events occurred".  I'm running with current zed nightly (0.176.0 535ba75bc795662ecc8d54fd7d5355ba7cf4d561)

**Comment by eric-seppanen** [comment]
It's still reproducible for me on Zed 0.174.8.

I had deleted the old git repo, so I created just a few directories and files to test:
```text
mkdir extensions
mkdir -p extensions/1/2/3
mkdir -p extensions/a/b/c
touch extensions/1/2/3/README
touch extensions/a/b/c/Cargo.toml
```

and then I tried with `RUST_LOG=debug` and I see this:
```text
[2025-02-25T15:54:57-08:00 DEBUG worktree] scanning directory ""
[2025-02-25T15:54:57-08:00 DEBUG worktree] scanning directory ".zed"
[2025-02-25T15:54:57-08:00 DEBUG worktree] scanning directory "extensions"
[2025-02-25T15:54:57-08:00 DEBUG worktree] scanning directory "extensions/1"
[2025-02-25T15:54:57-08:00 DEBUG worktree] scanning directory "extensions/a"
[2025-02-25T15:54:57-08:00 DEBUG worktree] scanning directory "extensions/1/2"
[2025-02-25T15:54:57-08:00 DEBUG worktree] scanning directory "extensions/a/b"
[2025-02-25T15:54:57-08:00 DEBUG worktree] scanning directory "extensions/1/2/3"
[2025-02-25T15:54:57-08:00 DEBUG worktree] scanning directory "extensions/a/b/c"
... (lots of other output) ...
[2025-02-25T15:54:57-08:00 DEBUG worktree] skipping excluded child entry "extensions"
```

And the `inotifywatch` confirms:
```text
total  access  close_nowrite  open  filename
12     6       3              3     extensions/
8      4       2              2     extensions/1/2/
8      4       2              2     extensions/1/
8      4       2              2     extensions/a/b/
8      4       2              2     extensions/a/
4      2       1              1     extensions/1/2/3/
4      2       1              1     extensions/a/b/c/
```


I can re-test when a 0.176 binary comes out, if we think it might be fixed...

**Comment by eric-seppanen** [comment]
I retested with zed 0.176.3 and the problem is still there. It has the same log output as I copied in the previous comment, and the same accesses are detected by `inotifywatch` (as in the previous comment).

Also, I notice that at some point recently, `RUST_LOG=debug zed . --foreground >test.log` stopped working: I used to be able to redirect the output to a file but now I just get an empty file. I tried using `RUST_LOG_STYLE=never` but that had no effect.

**Comment by probably-neb** [comment]
Investigated this a bit myself. It seems that we are following the project local exclude directories settings... once they get loaded.

As far as I can tell, we kick off the worktree scan during startup, and then shortly after when settings finish parsing we restart the scan based on a settings updated event with the user provided exclude dirs rather than the default ones. When this happens, we remove the ignored "extensions" dir as well as all of it's descendants. 

@eric-seppanen it seems from the logs you most recently provided that this is happening for you as well. Would you mind confirming that after a short period we stop indexing the files in the excluded dirs?

If I'm correct and this is what is happening, I personally think we should keep it that way, as the alternative is to delay starting the worktree index until after settings are fully parsed and loaded. This isn't ideal because of the wide variety of places in Zed that depend on the worktree scan to work properly such as the file tree and workspace search. Delaying the start of the worktree scan would conceivably make it so the file tree took longer to show up on screen leading to a worse user experience. 

The only time I can see this eager parse + cleanup later strategy being a problem is when an excluded dir is something like a networked file system where the user likely does not want to use their internet bandwidth to scan the networked drive especially if it is in their list of explicitly excluded files. But I don't think cases like that would be difficult to detect and wait for settings to load. That being said, I may be missing some other cases where the eager strategy is a problem.

**Comment by eric-seppanen** [comment]
@probably-neb:
> it seems from the logs you most recently provided that this is happening for you as well. Would you mind confirming that after a short period we stop indexing the files in the excluded dirs?

I could read that question a couple of ways:

1. After a certain amount of wall-clock time, does Zed stop reading files in an excluded directory? **No.**

    Using a huge network filesystem mounted inside my project directory, I can see that it scans forever (observing logs from the network filesystem daemon).

    The editor UI is available, but at the bottom it says "Roots Scanned (99%): ..." and stays there indefinitely. Source files can be opened, but I can't use "Go To Definition" or any other features. This is an improvement since the time when I filed this bug (back then most of the UI was blank).

2. After Zed has finished startup (and completed one scan of the excluded directory), does it stop monitoring activity in that directory? **Mostly.**

    I ran a separate experiment without the network filesystem; like in my [comment](https://github.com/zed-industries/zed/issues/21040#issuecomment-2683559950) above, I started Zed with an excluded directory, then created new directories and files in the excluded directory:
    ```plaintext
    extensions$ mkdir hello
    extensions$ echo "world" >hello/world
    ```
    Zed's debug logs show it's still receiving events for the excluded directory, but doesn't act on them (`inotifywatch` reports only my shell activity.)
    ```plaintext
    [2025-03-11T11:06:10-07:00 DEBUG worktree] ignoring event "extensions/hello" within unloaded directory
    ```

**Comment by notpeter** [comment]
Apologies for the delayed reply.
I think what you're seeing @eric-seppanen may be a rust-analyzer issue -- `Roots Scanned (99%)` is coming from rust-analyzer, not zed.  Unlike most LSPs, rust-analyzer does it's own file system scanning and thus maintains it's own exclusion lists. I wonder if this might help:

> [rust-analyzer.files.exclude](https://rust-analyzer.github.io/book/configuration#files.exclude)
> 
> Default: []
> 
> These paths (file/directories) will be ignored by rust-analyzer. They are relative to the workspace root, and globs are not supported. You may also need to add the folders to Code's files.watcherExclude.

Can you try this and see if it helps:
```json
{
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "exclude": {
          "files": ["repo/folder1"]
        }
      }
    }
  }
}
```

Separately, that function was largely broken (and had a different name) prior to https://github.com/rust-lang/rust-analyzer/pull/18998 (merged 2025-02-11).

If this works, I would love to get this added to the [Zed Rust Docs](https://zed.dev/docs/languages/rust) and add a reference in the [file-scan-exclusions](https://zed.dev/docs/configuring-zed#file-scan-exclusions) docs as well.

**Comment by ericseppanen** [comment]
Unfortunately, that didn't make any difference in my testing.

I mounted a slow fuse filesystem under a rust project directory (in a subdirectory called `subdir`) and used the following `.zed/settings.json`:
```json
{
  "file_scan_exclusions": ["subdir"],
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "exclude": {
          "files": ["subdir"]
        }
      }
    }
  }
}
```

I then launched zed and still see it get stuck while displaying a "Roots Scanned (87%) 14/16 ..." message, while the fuse filesystem logs indicate that something is searching the filesystem (looking for `.git` in every subdirectory).

Would rust-analyzer be searching for `.git` directories? That seems a bit surprising.

**Comment by ericseppanen** [comment]
I re-tested on Zed 0.218.5. The editor opens and basic GUI functionality is there, but it displays "Roots Scanned (0%) 0/14" forever.

I did some more investigating and found a few new things.

As previously suspected, it's not the zed process doing this: it's rust-analyzer. We can exclude the directory but the syntax we tried previously was wrong (it's `files.exclude` not `exclude.files`):

```json
{
  "file_scan_exclusions": ["subdir"],
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "files": {
          "exclude": ["subdir"]
        }
      }
    }
  }
}
```

After fixing that, I noticed there is another process deep-scanning the excluded directory. Zed has spawned a `git` process that is deep-scanning the tree (`/usr/bin/git --no-optional-locks status --porcelain=v1 --untracked-files=all --no-renames -z . .`). That git process keeps running even after I close the editor. If I add my excluded directory to `.gitignore` then this behavior stops as well.
