### ISSUE TITLE
Projects using Python language server polluted with .ropeproject folders.

### ISSUE THREAD

**Issue by karimbenbourenane** [zed-industries/zed#22085]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening a file in a project that uses the Python language server, zed will create a directory called `.ropeproject`. It looks like the intention based on rope's configuration in zed was for this folder to *not* be created, but it is created nonetheless. Please see ` "ropeFolder": null` in `crates/languages/src/python.rs`. I think the problem here may be that the incorrect name is being used for `ropefolder`; it should be all lowercase, as the Project class in Rope is looking for an argument called `ropefolder`, not `ropeFolder`.

### Environment

Zed: v0.165.4 (Zed)
OS: macOS 15.1.1
Memory: 96 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by osiewicz** [comment]
We already have a [PR upstream](https://github.com/python-lsp/python-lsp-server/pull/604/files) upstream to fix this. The problem is with pylsp incorrectly handling null value in the first place.

**Comment by notpeter** [comment]
Closing as an upstream issue.

**Comment by osiewicz** [comment]
This issue has now been resolved with `pylsp` version 0.12.1

**Comment by MDNSSKNGHT** [comment]
> This issue has now been resolved with `pylsp` version 0.12.1

Hi, zed still creates .ropeproject folder for me, any suggestion?

**Comment by fatezi404** [comment]
> > This issue has now been resolved with `pylsp` version 0.12.1
> 
> Hi, zed still creates .ropeproject folder for me, any suggestion?

Hi. Manually configure your project.py file in ~/.local/lib/python3.10/site-packages/rope/ lib and set ropefolder to None.

`class Project(_Project):
    """A Project containing files and folders"""

    def __init__(self, projectroot, fscommands=None,
                 ropefolder=None, **prefs):`

**Comment by expora** [comment]
> > > This issue has now been resolved with `pylsp` version 0.12.1
> > 
> > 
> > Hi, zed still creates .ropeproject folder for me, any suggestion?
> 
> Hi. Manually configure your project.py file in ~/.local/lib/python3.10/site-packages/rope/ lib and set ropefolder to None.
> 
> ```
> class Project(_Project):
>     def __init__(self, projectroot, fscommands=None,
>                  ropefolder=None, **prefs):`
> ```

I'm also getting the `.ropeproject` in my python projects. I'm using Zed 0.174.6 and I tried following your suggestion but I have no such directory. Would `~/Library/Application\ Support/Zed/languages/pylsp/pylsp-venv/lib/python3.12/site-packages/rope/base/project.py` work?

**Comment by fatezi404** [comment]
> > > > This issue has now been resolved with `pylsp` version 0.12.1
> > > 
> > > 
> > > Hi, zed still creates .ropeproject folder for me, any suggestion?
> > 
> > 
> > Hi. Manually configure your project.py file in ~/.local/lib/python3.10/site-packages/rope/ lib and set ropefolder to None.
> > ```
> > class Project(_Project):
> >     def __init__(self, projectroot, fscommands=None,
> >                  ropefolder=None, **prefs):`
> > ```
> 
> I'm also getting the `.ropeproject` dir in my python projects. I'm using Zed 0.174.6 and I tried following your suggestion but I have no such directory. Would `~/Library/Application\ Support/Zed/languages/pylsp/pylsp-venv/lib/python3.12/site-packages/rope/base/project.py` work?

Well, if it's the one and only folder, then yes, it will work for you. You can simply check it:
`
import inspect
import rope

print(inspect.getfile(rope))
`
When you're in the right folder,  you should find the 'base' folder and project.py inside.

**Comment by expora** [comment]
> > > > > This issue has now been resolved with `pylsp` version 0.12.1
> > > > 
> > > > 
> > > > Hi, zed still creates .ropeproject folder for me, any suggestion?
> > > 
> > > 
> > > Hi. Manually configure your project.py file in ~/.local/lib/python3.10/site-packages/rope/ lib and set ropefolder to None.
> > > ```
> > > class Project(_Project):
> > >     def __init__(self, projectroot, fscommands=None,
> > >                  ropefolder=None, **prefs):`
> > > ```
> > 
> > 
> > I'm also getting the `.ropeproject` dir in my python projects. I'm using Zed 0.174.6 and I tried following your suggestion but I have no such directory. Would `~/Library/Application\ Support/Zed/languages/pylsp/pylsp-venv/lib/python3.12/site-packages/rope/base/project.py` work?
> 
> Well, if it's the one and only folder, then yes, it will work for you. You can simply check it:
> 
> ```
> import inspect
> import rope
> print(inspect.getfile(rope))
> ```
> 
> When you're in the right folder, you should find the 'base' folder and project.py inside.

Thank you. Maybe I misunderstood. The only thing I have under `~/.local/` are a couple of dirs `share` and `state`. Is `lib` created by zed? I thought maybe it's created by some python installation? I use pyenv to manage different python versions but I don't think I have `rope` under their `site-packages` dirs. I've never installed it. I don't have it in my python projects either. That's why I thought about editing the file under Application Support. Excuse my ignorance on these topics. It seems to have worked, I haven't seen `.ropefolder` again.

**Comment by fatezi404** [comment]
> > > > > > This issue has now been resolved with `pylsp` version 0.12.1
> > > > > 
> > > > > 
> > > > > Hi, zed still creates .ropeproject folder for me, any suggestion?
> > > > 
> > > > 
> > > > Hi. Manually configure your project.py file in ~/.local/lib/python3.10/site-packages/rope/ lib and set ropefolder to None.
> > > > ```
> > > > class Project(_Project):
> > > >     def __init__(self, projectroot, fscommands=None,
> > > >                  ropefolder=None, **prefs):`
> > > > ```
> > > 
> > > 
> > > I'm also getting the `.ropeproject` dir in my python projects. I'm using Zed 0.174.6 and I tried following your suggestion but I have no such directory. Would `~/Library/Application\ Support/Zed/languages/pylsp/pylsp-venv/lib/python3.12/site-packages/rope/base/project.py` work?
> > 
> > 
> > Well, if it's the one and only folder, then yes, it will work for you. You can simply check it:
> > ```
> > import inspect
> > import rope
> > print(inspect.getfile(rope))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When you're in the right folder, you should find the 'base' folder and project.py inside.
> 
> Thank you. Maybe I misunderstood. The only thing I have under `~/.local/` are a couple of dirs `share` and `state`. Is `lib` created by zed? I thought maybe it's created by some python installation? I use pyenv to manage different python versions but I don't think I have `rope` under their `site-packages` dirs. I've never installed it. I don't have it in my python projects either. That's why I thought about editing the file under Application Support. Excuse my ignorance on these topics. It seems to have worked, I haven't seen `.ropefolder` again.

It's not default folder as far as I know, but some of Python packages may create it and use it as their default folder. It worked for me and that's the place where I found rope. Probably, you should try to make a config.py file in your project to ensure if .ropefolder is really gone, because that's the only way I've been getting this folder for me.

**Comment by wigging** [comment]
This is not fixed. I am using Zed 0.176.3 on macOS 15.3.1 and Zed still creates a `.ropeproject` folder in my Python projects.

**Comment by sgarg26** [comment]
I still have this issue as well, `.ropeproject` folder is still created on Zed 0.176.3 on mac and Windows.

**Comment by wigging** [comment]
I created a [discussion](https://github.com/zed-industries/zed/discussions/26628) where people can share their Python settings for Zed. Maybe it will help people configure Zed for a better Python experience.

**Comment by osiewicz** [comment]
Could you try clearing out your pylsp install? It could be that it's not being updated correctly.
That'd be: `rm -rf ~/Library/Application\ Support/Zed/languages/pylsp` on Mac.

**Comment by sgarg26** [comment]
That seems to have done the trick for Mac. Deleting the `pylsp` folder on Windows does not work however. I have configured pyright as my LSP, but every time I open a Python project, Zed goes ahead and installs pylsp anyways. I know Windows is on a back seat compared to Mac and Linux, so I'd understand if it's not being worked on. Thank you!

**Comment by danielefranceschi** [comment]
With Zed 0.177.8, editing `~/Library/Application\ Support/Zed/languages/pylsp/pylsp-venv/lib/python3.1*/site-packages/rope/base/project.py` as suggested by @fatezi404 works:
```python
def __init__(self, projectroot, fscommands=None,
             ropefolder=None, **prefs):
```
instead of `ropefolder='.ropeproject'`.

**Comment by supergoku1028** [comment]
> With Zed 0.177.8, editing `~/Library/Application\ Support/Zed/languages/pylsp/pylsp-venv/lib/python3.1*/site-packages/rope/base/project.py` as suggested by [@fatezi404](https://github.com/fatezi404) works:
> 
> def __init__(self, projectroot, fscommands=None,
>              ropefolder=None, **prefs):
> instead of `ropefolder='.ropeproject'`.
> 
> Clean with `find . -type d -name '.ropeproject' | xargs -r rm -rf`

it does work

**Comment by Altair-Bueno** [comment]
> Could you try clearing out your pylsp install? It could be that it's not being updated correctly.
> That'd be: rm -rf ~/Library/Application\ Support/Zed/languages/pylsp on Mac.

Linux users should run `rm -fr ~/.local/share/zed/languages/pylsp`

**Comment by karimbenbourenane** [comment]
@osiewicz: As of 0.180.3 this issue is still happening. Something as simple as opening a project with a python file in it and just *viewing* the file creates an empty .ropeproject directory. Is this the expected behavior? Why is a folder being created when it's not used to store anything? 

It would make sense to create this directory if some state data needs to be stored, but since it's not doing that just by viewing a python file it seems like aggressive pollution of project directories that doesn't need to happen.

**Comment by karimbenbourenane** [comment]
To add, if this issue was fixed in a previous version of Zed, it appears that it may have been reintroduced.

**Comment by osiewicz** [comment]
As I mentioned in my previous comment, we're not upgrading existing pylsp installation correctly. The issue with .ropeproject was fixed by us in pylsp itself.
I've opened a PR to fix the update process for pylsp; give it a go tomorrow (when it's on Preview): https://github.com/zed-industries/zed/pull/28338

**Comment by Dunravin** [comment]
for me the project.py was located in 

`.local/share/zed/languages/pylsp/pylsp-venv/lib/python3.13/site-packages/rope/base/`

after following @fatezi404 advise I no longer get the `.ropeproject` folder created

**Comment by 0xwuchuan** [comment]
This is not fixed for me yet on Zed 0.181.7, I have also tried clearing out your pylsp install with rm -rf ~/Library/Application\ Support/Zed/languages/pylsp on Mac.

**Comment by NeilsC** [comment]
I just started using Zed this week and am experiencing this issue. Running version 0.189.5 on Linux with a project targeting python 3.13. 

I tried these steps without resolution:

1. close Zed
2. delete the `.ropeproject` directory from my project root
3. delete Zed's `pylsp` directory with `rm -rf ~/.local/share/zed/languages/pylsp`
4. start Zed and open the project
5. The errant directory was created again.

**Comment by wigging** [comment]
@NeilsC As I mentioned earlier, I use pyright instead of pylsp with Zed and this gets rid of the annoying `.ropeproject` directory.

**Comment by mafiefa02** [comment]
Any update on this issue? This is still happening on Zed 0.191.9 running in macOS 15.5

**Comment by nickagliano-st** [comment]
> Could you try clearing out your pylsp install? It could be that it's not being updated correctly. That'd be: `rm -rf ~/Library/Application\ Support/Zed/languages/pylsp` on Mac.

On Mac. Running this and restarting Zed worked for me 👍🏻 .

**Comment by akshithio** [comment]
The bug continues to occur for me as of today but I found a fix that worked for me.

I found using `basedpyright` for the language server to work:

```json
  "languages": {
    "Python": {
      "language_servers": ["basedpyright"]
    }
  }
```

Save, then install the extension on Zed. Delete the`.ropeproject` folder, quit Zed and then re-open. It should stop happening.

edit: this obviously comes at the cost of using the stricter default standards of basedpyright though.

**Comment by nickagliano-st** [comment]
> > Could you try clearing out your pylsp install? It could be that it's not being updated correctly. That'd be: rm -rf ~/Library/Application\ Support/Zed/languages/pylsp on Mac.

> 
> On Mac. Running this and restarting Zed worked for me 👍🏻 .

Never mind. It comes back after zed upgrades 😢. Seems like this issue should be reopened?

**Comment by wigging** [comment]
> Never mind. It comes back after zed upgrades 😢. Seems like this issue should be reopened?

I agree this is still an ongoing problem with Zed and needs to be fixed.

**Comment by karimbenbourenane** [comment]
Agreed that this issue should be reopened. I'm the original reporter, and more than half a year later this is still a problem and still hasn't been fixed. @notpeter and @osiewicz
 I think the changes in https://github.com/python-lsp/python-lsp-server/pull/604/files were missing a key component of checking `rope_folder is not None` in addition to `"ropeFolder" in rope_config`. For cases where the ropeFolder is not defined, it will use the default config of having `"ropeFolder": null` which ends up passing the condition of having the `ropeFolder` key being present in the rope_config. I think that may be the problem.

So I think upstream on python-lsp-server that line `if "ropeFolder" in rope_config:` needs to be `if rope_folder is not None:`. I would submit a pull request with exactly that, but I'm unsure how to build and test zed locally with those specific changes to python-lsp-server to verify for certain that would fix things.

Edit: I went ahead and created a pull request for this https://github.com/python-lsp/python-lsp-server/pull/664/files

**Comment by james-yun** [comment]
This problem went away after I updated to version 0.212.6 (perhaps fixed in an earlier version than this).

**Comment by kansson** [comment]
> This is happening to me on 0.230.1 on Windows using ty lsp.

Same on macos with basedpyright.
