### ISSUE TITLE
Strange horizontal scrolling bug in recent commits 

### ISSUE THREAD

**Issue by mocenigo** [zed-industries/zed#22252]
### Summary

Horizontal scroll jank with soft wrap enabled.

### Description

If soft wrap is active, the editing pane should not have horizontal scrolling.
However, in recent commits (since 0.168) when soft wrap is active the content can scroll horizontally a few pixels, which also means that if the display of the horizontal scroll bar is activated, you see a scroll bar.

The proper behaviour would be that of releases (such as 0.166), in other words the content of the pane should not be able to scroll sideways once soft wrap to pane size is active.

This seems to be a minor mistake in the computation of the content width.

### Zed Version and System Specs

Zed: v0.168.0 (Zed Dev d54662e683a45617fb66d32d4391729320b9aba3)
OS: macOS 15.3.0
Memory: 24 GiB
Architecture: aarch64

### If applicable, add screenshots or screencasts of the incorrect state / behavior

<img width="1188" alt="image" src="https://github.com/user-attachments/assets/e658b1de-a914-426b-94cc-e59d7294b087" />

**Comment by apricotbucket28** [comment]
I bisected this issue to ed3e647ed7653fadd9e5ac14a7eaf638a1de9c4d, which is where the horizontal scrollbar got added.

**Comment by mocenigo** [comment]
> I bisected this issue to [ed3e647](https://github.com/zed-industries/zed/commit/ed3e647ed7653fadd9e5ac14a7eaf638a1de9c4d), which is where the horizontal scrollbar got added.
> 
> Adding the following to `settings.json` does hide the scrollbar:
> 
> ```json
> "scrollbar": {
>   "axes": {
>     "horizontal": false
>   }
> }
> ```
> 
> But the buffer can still be scrolled horizontally (by holding shift when moving the mouse wheel).

Yes, I already observed this and know about scrollbar.axes.horizontal. But, I use double finger swipe on my MBs trackpad.

**Comment by Nairou** [comment]
I'm seeing this after updating to 0.167.1. `soft_wrap` is set to `editor_width`, but it appears to be wrapping one character too far. This results in the last character on each row being cut off, requiring a scroll bar.

![image](https://github.com/user-attachments/assets/5f33c3dd-c19b-45a4-be87-4bbe9264761c)

**Comment by slxnxl** [comment]
I observe the same behavior, but only when the application width is reduced to half of the screen or less, or when opening the right panel (e.g., the chat with the assistant).

mac os 15.2 
zed  0.171.6

**Comment by benjaminwelch** [comment]
I believe I'm seeing something similar. For me, it's in the chat window. There's a little margin on the right side. I've disabled the horizontal axes for scrolling. This causes the text on the left side to be slightly hidden. I just want it to stay in place.

![Image](https://github.com/user-attachments/assets/611df213-c7a3-4cca-bb51-d834559d66c9)

Any suggestions or fixed appreciated. I'm probably doing something wrong. :)

**Comment by mocenigo** [comment]
I am not sure it is closed. I am using the latest source, compiled on my machine, and I observe that when the soft wrap is active, it stil soft wraps at 512 and in that case there is also some space on the side.

![Image](https://github.com/user-attachments/assets/f123802d-69f3-4992-a47c-6fbe47863be0)

and if soft wrap is active, it does wrap at the editor pane's width, BUT adds the space on the side and the scroll bar is still there: 

![Image](https://github.com/user-attachments/assets/9c5622e0-d807-4127-97e6-26e1c57b93ed)

I do not know what causes it, but it is weird, there is always extra space after the longerst line, unless the lines are all very short.

Roberto

**Comment by 0xtimsb** [comment]
Do you have git inline blame enabled? Can you try `editor: toggle git blame inline` to check if you still face this.

**Comment by mocenigo** [comment]
> Do you have git inline blame enabled? Can you try `editor: toggle git blame inline` to check if you still face this.

AAAAH that was it. It had to reserve space for the inline git blame!

It seems fine now.

 Roberto

**Comment by AaronFeickert** [comment]
See #24752 for the inline blame issue!

**Comment by benjaminwelch** [comment]
I've updated Zed and toggled `inline git blame` and I'm still seeing this in both the editor and chat panels.

![Image](https://github.com/user-attachments/assets/3cb36d3e-eeb2-4928-8631-67a85e5b979a)

Perhaps I changed the wrong setting by accident. Would love to get this sorted. I don't want any horizontal scroll with soft-wrap enabled. Any help is appreciated.

**Comment by mocenigo** [comment]
> I've updated Zed and toggled `inline git blame` and I'm still seeing this in both the editor and chat panels.
> 
> ![Image](https://github.com/user-attachments/assets/3cb36d3e-eeb2-4928-8631-67a85e5b979a) [ ![Image](https://github.com/user-attachments/assets/3cb36d3e-eeb2-4928-8631-67a85e5b979a) ](https://private-user-images.githubusercontent.com/610197/412924759-3cb36d3e-eeb2-4928-8631-67a85e5b979a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk0NjQxOTIsIm5iZiI6MTczOTQ2Mzg5MiwicGF0aCI6Ii82MTAxOTcvNDEyOTI0NzU5LTNjYjM2ZDNlLWVlYjItNDkyOC04NjMxLTY3YTg1ZTViOTc5YS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxM1QxNjI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmM3OTBmOTY0ODIxMTlkOWYyZjc4YzhiYzZjNWIzZGQ0ZTJlYWRlNmE0ZWY3NTM3MGFjZTQ3MTljOTM4YjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LM4XZ1qIIqv0vY4Kh3YXNIqgchiI_C-vuGFnbCMouP8) [ ](https://private-user-images.githubusercontent.com/610197/412924759-3cb36d3e-eeb2-4928-8631-67a85e5b979a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk0NjQxOTIsIm5iZiI6MTczOTQ2Mzg5MiwicGF0aCI6Ii82MTAxOTcvNDEyOTI0NzU5LTNjYjM2ZDNlLWVlYjItNDkyOC04NjMxLTY3YTg1ZTViOTc5YS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxM1QxNjI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmM3OTBmOTY0ODIxMTlkOWYyZjc4YzhiYzZjNWIzZGQ0ZTJlYWRlNmE0ZWY3NTM3MGFjZTQ3MTljOTM4YjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LM4XZ1qIIqv0vY4Kh3YXNIqgchiI_C-vuGFnbCMouP8)
> 
> Perhaps I changed the wrong setting by accident. Would love to get this sorted. I don't want any horizontal scroll with soft-wrap enabled. Any help is appreciated.

I think you have to compile it to see the fix, for the moment.

**Comment by AaronFeickert** [comment]
It's fixed in the [0.173.6 preview release](https://zed.dev/releases/preview/0.173.6) as well.

**Comment by mocenigo** [comment]
I also disabled in my settings the git blame function. I usually ignore it and I prefer to enable it on command.

Is there a way to change the height of the horizontal scroll bar? Like the bars in the other panes, it should be thinner and a bit rounde. The vertical scroll bar in the editing panes should stay like it is because it is over the breadcrumbs.

**Comment by asopio** [comment]
The soft wrap still doesn't seem to apply when inline git blames are enabled FYI. Fix this guys, it's so janky and ugly.
