### ISSUE TITLE
Spurrious "Failed to load environment" warning

### ISSUE THREAD

**Issue by istathar** [zed-industries/zed#23052]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening a remote project (over SSH) I get a warning in the status bar saying
`Failure to load shell environment in`, the path to the project folder, and `No such file or directory (os error 2)`

This appears to be https://github.com/zed-industries/zed/blob/e08484840b19bae7d28dfaeac6025d7f649e1cb5/crates/project/src/environment.rs#L218 in `load_worktree_shell_environment()`, on the failure branch when `smol::fs::metadata()` doesn't work.

This is all very strange; it's not clear what file it's looking for (the directory exists, obviously, and is readable obviously or the project tree wouldn't load). Clicking on the warning takes me to the Zed.log which ... doesn't have this text in it, nor anything else that appears relevant.

(I'm _not_ using direnv, if that matters)

### Zed Version and System Specs

Zed: v0.168.2 (Zed)
OS: Linux Wayland fedora 41
Memory: 30.9 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (ADL GT2) || Intel open-source Mesa driver || Mesa 24.2.8

### If applicable, add screenshots or screencasts of the incorrect state / behavior

![image](https://github.com/user-attachments/assets/93b06d2f-2459-4edc-8fbf-5ab6458e3d95)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2025-01-13T17:44:27.637691561+11:00 [INFO] Using surface present mode MAILBOX
2025-01-13T17:44:27.637743397+11:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-01-13T17:44:27.638420764+11:00 [INFO] using project environment variables from CLI. PATH="/home/andrew/.cargo/bin:/home/andrew/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin"
```
</details>

**Comment by marcospb19** [comment]
Possibly solved by https://github.com/zed-industries/zed/pull/23138.

**Comment by modulistic** [comment]
This is still happening to me with Zed Preview Zed Preview 0.181.3

**Comment by istathar** [comment]
This went away, but just returned with the update to 0.181.5.

**Comment by Artexety** [comment]
I just updated Zed and now receive the error too.

```
2025-04-13T21:27:41.566752+02:00 [ERROR] error fetching environment for path {}: Failed to load shell environment in {}: No such file or directory (os error 2)
```

**Comment by tdegrunt** [comment]
Do you need any other information or logs? 
Could this cause LSP's not being started? There just seems to be no way I can get the (Ruby) LSP to start  remotely.

**Comment by cole-miller** [comment]
@tdegrunt, we just release v0.181.7 which contains a patch intended to fix this issue; could you try updating and confirming whether it's fixed for you? Thanks!

**Comment by istathar** [comment]
@cole-miller It appears to have gone away? Haven't seen it on two restarts, but I'll keep an eye out!

[also, I didn't see a mention in the release notes so wasn't sure if it not appearing was transient (thus indicating a more insidious cause) or indeed resolved]

**Comment by Artexety** [comment]
@cole-miller Yes, I’m using SSH remote development, but after I updated Zed yesterday, the issue went away.

**Comment by cole-miller** [comment]
Re-closing this as fixed by #28356 and its backports; thanks everyone for the reports and help tracking this down.

**Comment by garymm** [comment]
Seeing this on an SSH remote with Zed 0.198.5. Should I file a new issue?

**Comment by istathar** [comment]
@garymm I'm getting it a lot now too. I suspect the error message is the catchall fallback covering up a lot of sins; it's probably a very different problem this time but {shrug}?
