### ISSUE TITLE
active_line_number color dont work

### ISSUE THREAD

**Issue by ElAv252** [zed-industries/zed#23765]
### Describe the bug / provide steps to reproduce it

Summary:

The color of active_line_number is not work.
The color is just the same color like all the line numbers.

### Zed Version and System Specs

Zed: v0.168.2 (Zed)
OS: macOS 15.2.0
Memory: 16 GiB
Architecture: aarch64

**Comment by bennetbo** [comment]
This was fixed in #23266 and released in v0.171.x (lands on Zed stable this week, already available in Zed Preview)

**Comment by ElAv252** [comment]
> This was fixed in [#23266](https://github.com/zed-industries/zed/pull/23266) and released in v0.171.x (lands on Zed stable this week, already available in Zed Preview)

Ok, thanks!

**Comment by ElAv252** [comment]
@bennetbo 
As you can see, it's still not work ):

[](url)

<img width="496" alt="Image" src="https://github.com/user-attachments/assets/ad8b95bc-4c85-42c1-a700-e3cbf8af6056" />

**Comment by bennetbo** [comment]
@ElAv252 Are you sure that you are using Zed Preview (v0.171.x) (https://zed.dev/releases/preview) and not Zed (v0.170.x)

**Comment by ElAv252** [comment]
Yes I'm sure.

<img width="1796" alt="Image" src="https://github.com/user-attachments/assets/e5b0557a-4829-45ad-9b72-d6d76af4c08e" />
