### ISSUE TITLE
Formatting in Python doesn't work despite running language servers

### ISSUE THREAD

**Issue by marinegor** [zed-industries/zed#25419]
### Summary

Formatting in Python doesn't work despite running language servers (ruff and pyright) in remote dev

Steps to trigger the problem:
1. Open a python file and format it incorrectly (in my case, 5 extra spaces around the `=` sign). For instance: `a =     5`
2. Save, or press Cmd+I, or go to command palette and select "format"

Actual Behavior:
Nothing happens -- file doesn't get formatted

Expected Behavior:
File should be formatted without extra spaces around the `=`

I've also attached my settings file:

[settings.json](https://github.com/user-attachments/files/18930727/settings.json)

### Zed Version and System Specs

Zed: v0.174.6 (Zed) 
OS: macOS 12.7.6
Memory: 16 GiB
Architecture: x86_64

**Comment by quinn-caverly** [comment]
I had this same problem yesterday. I am also using pyright and ruff. Try these things:
- uninstall your pyright and ruff installations via the cli. Zed will install them automatically 
- add py-project.toml pointing to the source code:
```
[tool.pyright]
include = ["src"]
extraPaths = ["src"]
reportMissingImports = true
```
- make sure you have pycache and other similar dirs gitignored so language server doesn't try to analyze them
```
__pycache__/
*.pyc
.pytest_cache/
```
- have a pyrightconfig.json so pyright gets your virtual env:
```
{
  "venvPath": ".",
  "venv": "venv"
}
```

**Comment by marinegor** [comment]
>uninstall your pyright and ruff installations via the cli. Zed will install them automatically

I uninstalled them from the virtual environment that I'm in, and it didn't help.

Cache files are in my gitignore, and modifying pyrightconfig.json / pyproject.toml didn't help

**Comment by bulletmark** [comment]
I see the same issue (on current stable 0.174.8).

Seems Python support in Zed has a few broken bits atm. @JosephTLyons [stated](https://github.com/zed-industries/zed/issues/22266#issuecomment-2660242459) 2 weeks ago that they were going to look at Python issues.

**Comment by probably-neb** [comment]
I'd love to get this fixed for you, but I'm not sure what's going wrong at this point as I'm unable to reproduce. 
Could you please check your zed logs `zed: open log` after formatting fails and let me know if you see any errors related to `ruff` and formatting?

**Comment by marinegor** [comment]
@probably-neb no, the log seems to be empty (see attached). Also the language server logs are totally empty🤷‍♂️

[zed.log](https://github.com/user-attachments/files/19079210/zed.log)

Ruff and pyright servers seem to be running (at least `pgrep -af ruff` and `pgrep -af pyright` are non-empty and contain language server processes -- I don't know if they are connected to zed though.

**Comment by bulletmark** [comment]
"Fails" seems to be the wrong word. There is nothing in the log and the command (either from the menu or using ctrl-shift-i) just seems to be ignored. There is no message anywhere. Same if the line is highlighted.

**Comment by probably-neb** [comment]
Hmm, seems like we need more logging around errors in formatting at base

I'll try to add logs in that area today and play around with the repro example to see if I can get my logs to trigger and figure out what's going wrong here

**Comment by marinegor** [comment]
Also something that might be useful for debugging: the issue persists only in remote development mode. Locally, everything runs just fine.

**Comment by probably-neb** [comment]
That's very important to know! Thanks! Was the issue happening before locally or has it been a remote only issue since the beginning? @bulletmark is this only happening on remote for you as well? Also, are the formatters installed differently on remote vs local?

**Comment by marinegor** [comment]
>Was the issue happening before locally or has it been a remote only issue since the beginning? 

I have a feeling it was working before, and at some point it also felt kinda slow, but then switched off completely.

>Also, are the formatters installed differently on remote vs local?

I honestly have no idea -- I don't think I installed them myself, zed seems to be managing all for me.
But I can say that local and remote are different platforms -- local is my macOS (tried from both arm and x86), and remote is ubuntu on wsl2 (yep).

**Comment by probably-neb** [comment]
Looking at your Zed log again, I'm seeing `timed out waiting for formatting`. The default wait is 5 seconds, does your python project happen to be very large? (where ruff may be taking 5+ seconds to format) or is the server far away? (where server delay may be the issue).

**Comment by marinegor** [comment]
>does your python project happen to be very large

nah, not really -- I'm workign with [MDAnalysis](https://github.com/MDAnalysis/mdanalysis/) codebase, if I run `ruff` in command line, it takes less than a second.

**Comment by probably-neb** [comment]
Actually, I merged https://github.com/zed-industries/zed/pull/24584 3 weeks ago, which made formatters run in serial rather than in parallel because running in parallel meant formatters interfering with each other resulting in junk output in your buffer. This would explain the slowdown you experienced I believe. 

Additionally Max increased the default formatter timeout  [since you opened this issue from 2 seconds to 5 seconds](https://github.com/zed-industries/zed/pull/25129/files?short_path=e741a14#diff-a3da3181e4ab4f73aa1697d7b6dc0caa0c17b2a187fb83b076dfc0234ec91f54L205-R204). If you're not running the latest version of Zed would you please update and see if the issue persists?

Thanks for providing a repo that's very helpful. On my system ruff fix all + sort imports + format takes under 100ms, but I can see how you might still be hitting the 2 second timeout with all of the various overheads involved (network, how Zed handles formatting internally, etc)

**Comment by marinegor** [comment]
> If you're not running the latest version of Zed would you please update and see if the issue persists

I was updated at the moment of submitting the issue (I update every time I re-open zed, cudos for making it very easy and quick). And I have just updated now and checked it -- still doesn't work.

**Comment by bulletmark** [comment]
It is working for me now. I didn't realize that even though I am using ruff, I have to explicitly set up formatting as described [here](https://docs.astral.sh/ruff/editors/setup/#zed). Seems a bug to me that zed just completely ignore the function/keybind and does not even say anything in the log when no formatter is configured. Also, if a user has configured ruff as the LS and enabled the ruff extension etc, wouldn't it be best if zed just used it as the formatter when manually invoking the command rather than require that explicit and messy config?

Every time I have to hand add some explicit config to do a basic function then a little part of me dies :(

**Comment by marinegor** [comment]
@bulletmark can you share part of the config that is related to python?

mine was also copied from the link you provided (you can see the settings.json in the first message), and it still doesn't work.

**Comment by bulletmark** [comment]
@marinegor my config as as stated in that link and seemingly same as you. I am using ruff + pyright LS same as you. Have you got the ruff extension installed?

**Comment by marinegor** [comment]
> Have you got the ruff extension installed

yes, and I even tried re-installing it as well.

**Comment by probably-neb** [comment]
@bulletmark I understand your frustration that the formatters don't just work by default. However, I'm not sure that enabling them by default is a good solution, as there are potentially many competing formatters for the same file type that a user could have installed. 
I agree though, that we could do a better job surfacing this to the user. 
I'd appreciate it if you created an issue saying something like it would be nice to show a popup to user when they install an extension with format support to enable that formatter, and also that having a popup appear saying no formatters are configured when you explicitly try to format a file when no formatters are configured.

**Comment by probably-neb** [comment]
@marinegor, I'm still having trouble reproducing this. Would you try running ruff in the command line on the remote and see if that works ok? If you can use the version installed by Zed on your remote that would be best. 
It would also be nice if you timed the command somehow (especially when there's a bunch of formatting issues that need fixing) to see how long it's taking on the remote.
I'll look into figuring out if there's an easy way to measure the latency with the remote as well so we can try to rule out the timeout problem.

**Comment by marinegor** [comment]
@probably-neb 

I updated zed to 0.177.7, and I'm running ruff 0.9.7 (installed via `uv tool install ruff`). pyright is version 1.1.394. Timings:

```
marin@homepc:~/github/mdanalysis$ time ruff check package/MDAnalysis/analysis/dssp/dssp.py
All checks passed!

real	0m0.019s
user	0m0.011s
sys	0m0.011s
marin@homepc:~/github/mdanalysis$ time ruff format package/MDAnalysis/analysis/dssp/dssp.py
1 file reformatted

real	0m0.035s
user	0m0.007s
sys	0m0.027s

# and the code actually gets formatted, and I see it displayed in zed
```

I'm on an ssh connection on my local network, and all navigation and command line stuff seems almost zero-latency.

Note that on a local machine everything works smoothly.

If there is anything else I can help you with for debugging, please don't hesitate to ask!

**Comment by valmar** [comment]
Having the same problem as @marinegor!, with the same exact versions

**Comment by bulletmark** [comment]
@marinegor you say this works locally for you. Does "organize imports" work for you with rust? It doesn't work for me, even though I have added the [configuration for rust](https://docs.astral.sh/ruff/editors/setup/#zed).

@probably-neb I won't bother raising a bug for that small issue given I am not sure that I agree with what you say and there are plenty of outstanding significant issues related to using zed with python which I would much prefer be addressed.

**Comment by probably-neb** [comment]
Ok @bulletmark , I hear you. Here's what I've done / what my plan is currently. I've created a meta tracking issue for Python support in Zed. 

I would super appreciate if you would leave comments with additional issues that maybe aren't big enough to make an issue for, and also link issues that you think should be included in the list. I've included this one and another issue I could remember off the top of my head to start. If you can add issues as sub issues (I'm not sure if non-members can) go ahead.

My goal here as a first step is to get a better understanding of where the problems are in the current Python experience in Zed, before deciding which issues to tackle first, and what bigger things we could be doing to make the experience truly great.

I'd also be happy to setup a time to talk through discord or in Zed collab. I'm "ben" in the Zed staff on Discord, feel free to reach out to or tag me personally

**Comment by probably-neb** [comment]
In regards to this issue @marinegor. I'm still pretty stuck unfortunately. Those timings + the fact that you're on your local network definitely point towards us doing something wrong and getting in a bad state until we timeout. 

My plan is to, sometime soon, setup a true remote environment on AWS or somewhere rather than testing with local based remoting (running both the headless Zed and actual Zed on the same machine) in the hopes of finally reproducing the issue. I'll also try to add more logging and checks around the formatting so at base we can try to collect more information than we're getting at this point.

**Comment by probably-neb** [comment]
Also, @marinegor, I've learned that we have a separate codepath for handling network communication through proxies that are [configured in Zed](https://zed.dev/docs/configuring-zed#network-proxy), that may be the cause of this issue. By any chance do you have Zed configured to use a proxy?

**Comment by marinegor** [comment]
@probably-neb yep, no proxy in Zed directly.

I'm using tailscale to connect to my machine, yet physically we're on the same network, and it seems to me that the whole traffic goes not go through the "big" internet. I'm happy to test some other configurations though.

**Comment by probably-neb** [comment]
Ok @marinegor, good news and bad news.
Good news: I'm pretty sure I know what the issue is here, and I'm also pretty sure that the PR I just linked fixes it!
Bad news (at least for me): It's entirely my fault :( (introduced in #24584)

In summary I completely broke how the edits made by formatters on the remote server are synced back to the client. I'm not sure why it was so difficult to reproduce this, I can't NOT reproduce it now, I think I might've been using an outdated implementation of the remote server while testing that did have the correct behavior.

I say I'm only pretty sure, as I still can't reproduce the timeout error you got in the logs you gave. But I can reproduce nothing happening when you try to format on a remote buffer. 

Thanks for being so patient and responsive thus far. I'm planning to finish up my PR (it's only a draft right now) tomorrow before the preview release. If my changes don't fix your issue we can reopen the issue and keep trying, but I'm feeling hopeful

**Comment by valmar** [comment]
Thank you @probably-neb !

**Comment by probably-neb** [comment]
Didn't make it into the preview release. I'm going to wait to bump a minor version until I have some other logging improvements in that will hopefully help debug future issues in this area/figure out what's going wrong here if the PR doesn't end up fixing this issue. Happy to reopen and continue working on this if it still isn't working
