### ISSUE TITLE
Mouse Pointer bugs after switching between applications - X11

### ISSUE THREAD

**Issue by arixsnow** [zed-industries/zed#25894]
### Summary

Mouse Pointer bugs after switching between applications in X11.

Steps to trigger the problem:
1. Open any file in Zed
2. Open any other application.
3. Now switch between application (atl+Tab)
4. Return to zed and the mouse pointer glitches.

Actual Behavior:

![Image](https://github.com/user-attachments/assets/8f64fb58-7929-4ca4-b732-2c6392abfeee)

![Image](https://github.com/user-attachments/assets/ceb579bb-7f9f-4601-b656-66a78d188eaa)

Expected Behavior:

![Image](https://github.com/user-attachments/assets/2b67a7e0-2282-4835-ab09-4a657a93aabc)

### Zed Version and System Specs

Zed: v0.175.6 (Zed)
OS: Linux X11 fedora 41
Memory: 15.3 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3050 Laptop GPU || NVIDIA || 565.77

**Comment by probably-neb** [comment]
I've bundled this in with a few other linux mouse pointer related issues. Could you give me more information on what's happening here please? 
- Does this happen every time you alt-tab away from Zed?
- Does it resolve itself after some period or is it stuck as the pointer or hand instead of the text insertion pointer forever once you alt-tab?

**Comment by arixsnow** [comment]
@probably-neb 
- Yeah it does happen every time.
- No it is stuck as the pointer or hand after alt-tab. But when the mouse pointer is taken out of the context window of zed and returned, then it is solved. But again after alt-tab same issue happens.

**Comment by arixsnow** [comment]
@probably-neb any progress/update on this issue?

**Comment by probably-neb** [comment]
Not yet. And unfortunately, it's unlikely this gets worked on soon, as we don't have reproduction steps that are system independent (as in Linux x11 system), and it is a visual bug that I'm sure is annoying, does not completely stop you from being able to use Zed. If you scroll through our open issues you will find many issues that completely stop people from being able to use Zed like crashes or some part of Zed like autocomplete breaking. These issues, as I hope you understand, take higher priority. This issue will stay open as long as we plan on fixing it, but unless you or someone else opens a PR to fix it, we will be comparing it to other existing issues and deciding what is more important for us to spend time doing!

Hope that makes sense, feel free to ping me if you are able to come up with additional information to help us reproduce the issue

**Comment by mikhail-shevtsov-wiregate** [comment]
Just to give a little bit more context for the future.
I have exactly the same problem:
```
Zed: v0.187.5 (Zed) 
OS: Linux X11 ubuntu 24.04
Memory: 62.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2060 with Max-Q Design || NVIDIA || 550.144.03
```

**Comment by ojvribeiro** [comment]
I noticed the cursor goes back to normal if you click the tool bar (lose window focus), then click on Zed window again.

**Comment by arixsnow** [comment]
@ojvribeiro It also goes back to normal even if you hover over the tool bar and bring back the cursor to the buffer area.

**Comment by mgsloan** [comment]
There are good chances this is fixed in https://github.com/zed-industries/zed/pull/32820 and will be included in v0.191 release (probably this coming wednesday).  Please re-open or create a new issue if there's more glitchiness with mouse cursors.

**Comment by arixsnow** [comment]
@mgsloan 
**The issue is still there.**

Zed: v0.191.4 (Zed) 
OS: Linux X11 fedora 42
Memory: 15.3 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3050 Laptop GPU || NVIDIA || 570.153.02

**Comment by mgsloan** [comment]
@arixsnow Dang, thanks for letting me know.  Is there anything about cursors / icons in your logs?  As part of that change I made the logging a bit more informative, should be helpful.

How are you running Zed?  Is the `XCURSOR_PATH` environment variable set?  For me running zed from the alacritty terminal installed via snap breaks cursor icons because it sets this environment variable to a bogus value.  `unset XCURSOR_PATH` in .bashrc fixes it.

**Comment by arixsnow** [comment]
@mgsloan I didn't find anything about cursor/icons in the zed log. Maybe be I have missed something.

I had installed the zed with the shell script provided on the zed official website. After installation I usually run zed from the gnome shell, though I have checked this behavior after running zed from the gnome-terminal. It shows the same bug.

I didn't find `XCURSOR_PATH` env-variable with `printenv`. Although running zed using the command `XCURSOR_PATH='' zed .` definitely breaks the cursor, as it should ig. So, running the zed either from gnome-terminal or gnome-shell definitely sets the `XCURSOR_PATH` value to something. But I didn't find it in the environment variable list of the running zed-process.

[Here is the log](https://gist.github.com/arixsnow/e386ec3c49ac773e7c86f6f4d2aa1c6f)

**Comment by arixsnow** [comment]
I was wondering if this issue might be linked to this #32163 issue.

**Comment by ogau** [comment]
**Zed version:** 207.3
**OS:** Pop!_OS (latest)
**Window Protocol:** X11

**Steps to Reproduce:**
1.  Open Zed.
2.  Hover your mouse over a system-level popup (e.g., the volume slider or calendar dropdown).
3.  Move the cursor *outside* the bounds of that popup and directly into the Zed window.
4.  Click anywhere inside the Zed window.

**Comment by mikhail-shevtsov-wiregate** [comment]
Occasionally I still experience this issue.

---
Zed 0.223.3 
59dfdea1697030fd39de6c92172ff192d013a984

0.223.3+stable.152.59dfdea1697030fd39de6c92172ff192d013a984

**Comment by brandonhs** [comment]
Same issue with Zorin OS 17.3 (ubuntu derivative) and x11. Reproducible occasionally by alt-tabbing and consistently by navigating to a widget (like volume) and clicking back into zed. I have been unable to replicate this issue in other applications. Since this issue has seemingly been around for a while, I don't expect it to be resolved quickly. I may try some debugging later to hopefully determine a root cause.

```
Zed 1.2.6 
Commit: 20b7f31e7dbe8233a198728ccf3c8aa1180c13e4
Version: 1.2.6+stable.280.20b7f31e7dbe8233a198728ccf3c8aa1180c13e4
```

**Comment by mgsloan** [comment]
I haven't looked into this (and might not get around to it).  My current theory is that maybe X11 doesn't keep track of the last mouse that was set by Zed.  So when the mouse re-enters the cursor only gets updated once the mouse moves such that Zed's cursor style differs from the last set style.
