### ISSUE TITLE
Autocomplete doesn't work in vue files.

### ISSUE THREAD

**Issue by sausir1** [zed-industries/zed#26901]
### Summary

Same as the title. After upgrading zed to newest version autocompletion stopped working in .vue files. 

Steps to trigger the problem:
1. Create a new vue project with `pnpm create vite@latest` 
2. see if you can `Go to definition` to any import. Types does not work as well.

Actual Behavior:

Nothing shows up when hovered 

![Image](https://github.com/user-attachments/assets/bc795566-fc67-479a-ad1b-e02de2b7a515)

Expected Behavior:

should show type definitions, be able to jump to definition as well.

![Image](https://github.com/user-attachments/assets/95e02e27-e290-413e-b208-0c3a9ed5bb25)

### Zed Version and System Specs

Zed: v0.177.9 (Zed) 
OS: Linux Wayland ubuntu 24.04
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) Xe Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 24.2.8-1ubuntu1~24.04.1

**Comment by erik-reges** [comment]
it has been this way for over a year. sometimes it works, but most of the time it does not. i think the issue lies with ts lsp and vue lsp together. i've had autocomplete appear and then be unable to recreate it after opening a .ts file

this is keeping at least 2 engineers at my company from switching

**Comment by sausir1** [comment]
> it has been this way for over a year. sometimes it works, but most of the time it does not. i think the issue lies with ts lsp and vue lsp together. i've had autocomplete appear and then be unable to recreate it after opening a .ts file
> 
> this is keeping at least 2 engineers at my company from switching

I wouldn't be so sure, there's probably some issue with your project/os or etc.. It worked for me completely fine until friday (march 14h) and this morning after upgrading zed to newest release it stopped working. Go to definition, type inference was working fine before the update recently

**Comment by notpeter** [comment]
It sounds like there may be both a long standing issue with Vue stability in Zed for some folks and potentially recent regression in Vue as well.  For the former, see:
- https://github.com/zed-industries/zed/issues/12384

@sausir1 I attempted to reproduce with your instructions from this issue but was unsuccessful:
```
pnpm create vite@latest
cd vite-project
pnpm install
zed .
```
Then I opened `src/main.ts`, right clicked on `viteLogo` -> 'Goto Definition' correctly opened `vite-project/node_modules/.pnpm/vite@6.2.2/node_modules/vite/client.d.ts`.

Similarly opening `source/counter.ts`, right clicked on `HTMLButtonElement` -> 'Goto Type definition' correctly opened `vite-project/node_modules/.pnpm/typescript@5.7.3/node_modules/typescript/lib/lib.dom.d.ts`

I'm running on macOS with Zed Nightly.
For reference here are my node versions:
```shell
# pnpm --help |grep Node
Version 9.14.4 (compiled to binary; bundled Node.js v23.9.0)
# ps -ef |grep vtsls   
/opt/homebrew/opt/node@22/bin/node /Users/peter/Library/Application Support/Zed/languages/vtsls/node_modules/@vtsls/language-server/bin/vtsls.js --stdio
```
Are you seeing different behavior with those steps or are there additional steps I need to follow?

**Comment by tednaaa** [comment]
Hey @notpeter ! Tried your same steps and I don't have autocomplete

for templates such as `Vue official starter` and just `Typescript`

here are my specs
- Node version v22.14.0
- Pnpm Version 10.6.3 (compiled to binary; bundled Node.js v20.11.1)
- Zed 0.177.9

Everything was okay with this setup, just 2-3 hours before stopped working lsp in vue files

however for `ps -ef | grep vtsls` I got something strange, maybe it's causing the issue?

![Image](https://github.com/user-attachments/assets/f3e83697-bd82-4053-9e2f-e19ea18f939d)

**Comment by GabrielHangor** [comment]
Same issue...

**Comment by asgerclerk** [comment]
Vue + TS should now work again: https://github.com/zed-extensions/vue/issues/24#issuecomment-2732536745

**Comment by sausir1** [comment]
Can confirm as well, that now autocomplete started to work again. I've also used a typecript plugin before and after it's deletion autocomplete started to work again: 

![Image](https://github.com/user-attachments/assets/77b7fe92-9524-402b-9e2d-eb094c5e7152)

Don't really know if that was just a coincidence or really resolved the issue. Plugin was needed on previous versions for me, so that Zed editor would not scream at me that some imported `.vue` file did not exist.

**Comment by fazulk** [comment]
Still can't get this to function correctly without the `@vue/typescript-plugin` from inside .ts files . Would love to not need it. Zed is the only editor needs it from what i can tell. 

![Image](https://github.com/user-attachments/assets/63b029b7-a758-4efd-ac48-1c8fe53a06ff)

**Comment by smitbarmase** [comment]
Seems like original issue of autocomplete is caused by upstream (more here https://github.com/zed-extensions/vue/issues/24#issuecomment-2732536745) which is now fixed, so I'm closing this issue. Please comment if you feel otherwise.

@fazulk @sausir1 Built-in plugin support for extensions is being worked on (https://github.com/zed-industries/zed/pull/27407). After which, you won’t see these import errors or have to manually install or specify the plugin.

**Comment by fazulk** [comment]
this is working now :)
