### ISSUE TITLE
Git pane doesn't refresh when files change

### ISSUE THREAD

**Issue by ion-elgreco** [zed-industries/zed#27088]
### Summary

Git pane doesn't auto refresh

Steps to trigger the problem:
1. Open git pane
2. Change file
3. Discard change
4. Git panel shows still the change
5. Click on the file, and then it suddenly disappears from pane

Actual Behavior:
Refreshes only when you interact with it

Expected Behavior:
Should refresh when a file is changed

### Zed Version and System Specs

Zed 0.177.11

**Comment by auralluring** [comment]
I've also noticed that after I push to a remote, it still says it has unpushed changes until I get it to do a different operation like a fetch or pull (a commit would probably do the trick as well, since it has to update the number). that was really confusing the first couple times it happened.

**Comment by cole-miller** [comment]
Closing this as I believe the original issue is no longer present in recent versions of Zed---please open a new issue if you see it still coming up!

@auralluring this was fixed by #28394!

**Comment by ion-elgreco** [comment]
@cole-miller seems to work indeed, however I was able to break it, sometimes it would still show a vacant file that doesn't exists, only clicking fetch clears it up aagain

**Comment by cole-miller** [comment]
@ion-elgreco Thanks, doesn't sound good, could you post a screen recording showing the issue?

**Comment by ion-elgreco** [comment]
@cole-miller yes, see below

https://github.com/user-attachments/assets/ba3bd082-4d67-47fd-83df-fdefbcd027cb
