### ISSUE TITLE
Stale buffers should be removed from search multibuffer

### ISSUE THREAD

**Issue by chrs-b** [zed-industries/zed#28398]
### Summary

If project search has matches in an unsaved buffer and the unsaved buffer is closed first, closing the project search pane asks again.

### Description

Steps to reproduce:
1. create a new buffer and paste some text
2. run project search (cmd-shift-f) with a match in new file but also existing file(s)
3. close the new buffer (step 1), when prompted, don't save

The search multi-buffer still contains the closed file.
When you close the multi-buffer it prompts you a second time.

Ideally when an untitled buffer is closed/not saved it should be removed from the multibuffer. 

Same issue applies to files that have been deleted. The project search multi-buffer keeps a stale reference to those files -- and even if you re-search, but match the same files the stale results stick around.  

### Zed Version and System Specs

Zed: v0.180.3 (Zed) 
OS: macOS 15.3.1
Memory: 128 GiB
Architecture: aarch64

**Comment by injust** [comment]
Another result of this bug: Run repro steps 1 and 2, then run the "workspace: reload" command. You will get the error: "This buffer contains unsaved edits. Do you want to save it?", despite a reload persisting unsaved files.

**Comment by notpeter** [comment]
@binChris I believe the issue preventing the search multi-buffer from closing has been fixed, so I have edited your description to reflect the fact that it is unintuitive to be prompted multiple times to save a buffer -- no means no -- just because there was a stale reference in a search multi-buffer.

Thanks for reporting.

**Comment by chrs-b** [comment]
Thanks for coming back on this @notpeter 

Unfortunately, the bug is still present (0.191.9), as you will see when following the 3 steps in the description.

The search multi-buffer cannot be closed. The unsaved indicator is shown. When trying to close the buffer, nothing happens. Searching again still finds text in the closed buffer, even if the underlying file was closed.

A work-around is changing the search to something that is not contained in the closed buffer. When this is done, the superfluous closed buffer disappears and the search multi-buffer can be closed.

**Comment by arguiot** [comment]
Issue is still existing. Just had this problem on latest version:

Zed: v0.196.6 (Zed)
OS: macOS 15.5.0
Memory: 24 GiB
Architecture: aarch64

**Comment by bottlenecked** [comment]
This is still ongoing I guess. I'm not sure I've seen the particular bug described in this ticket, and maybe it's rare enough that the ticket has not been prioritized. But its sibling ticket [Deleting files doesn't refresh project search #30933](https://github.com/zed-industries/zed/issues/30933) that has been closed as a duplicate of this one happens all the time. Today during a big refactoring it became annoying enough to merit looking it up to see if it's only me that struggles with this behavior 😅 - so I just wanted to bring it up again for some extra visibility

**Comment by chrs-b** [comment]
> This is still ongoing I guess.

Yes, the bug is still present in v0.208.6 and can be reproduced by following the 3 steps in my [initial post](https://github.com/zed-industries/zed/issues/28398#issue-2981385225) in terms of the closed buffers surviving in the find-all pane.
The impact is lower tho, because there is now a "Close without Saving" option.

I'd still consider showing the closed buffers in find-all a bug.

**Comment by mg-christian-esser** [comment]
Issue still present in Zed 0.221.4

**Comment by pingpong74** [comment]
This issue is still present in the latest git version of zed
