### ISSUE TITLE
Extensions fail to set language server environment variables

### ISSUE THREAD

**Issue by valentinegb** [zed-industries/zed#28609]
### Summary

If environment variables are set in [`zed_extension_api::process::Command::env`](https://docs.rs/zed_extension_api/latest/zed_extension_api/process/struct.Command.html#structfield.env), you will find that these environment variables do not end up being set from the perspective of the language server, however setting them in Zed's settings (`lsp.language-server.binary.env`) *does* work.

### Description

Steps to reproduce:
1. Download [valentinegb/zed-extension-env-bug-mre].
2. Install this extension (`zed: install dev extension`).
3. Open a text file or open any file and set the language to "Plain Text".
4. Click "Failed to run extension-env-bug-mre." in the bottom left corner.
5. Observe the absence of `THIS_IS` and `AND_THIS` test environment variables.
6. In your Zed settings, add the following:
   ```json
   {
     "lsp": {
       "extension-env-bug-mre": {
         "binary": {
           "env": {
             "SETTINGS_TEST": "hey there!"
           }
         }
       }
     }
   }
   ```
7. Repeat step 3.
8. Open the command palette and execute `editor: restart language server`.
9. Repeat step 4.
10. Observe the presence of a `SETTINGS_TEST` environment variable.

Please see [valentinegb/zed-extension-env-bug-mre] for an example of an extension which this bug affects.

Expected Behavior: environment variables set for a language server in an extension should actually be set.
Actual Behavior: environment variables set for a language server in an extension are not actually set.

[valentinegb/zed-extension-env-bug-mre]: https://github.com/valentinegb/zed-extension-env-bug-mre

### Zed Version and System Specs

Zed: v0.182.3 (Zed Preview) 
OS: macOS 15.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by valentinegb** [comment]
It looks like, to me, `zed_extension_api::process::Command` is turned into an `lsp::LanguageServerBinary`, just as `lsp.language-server.binary` is, I believe. I'm not sure why language server binary settings work but extensions don't if they both end up setting environment variables the same way...

**Comment by vitallium** [comment]
I think this was fixed in https://github.com/zed-industries/zed/pull/28173

**Comment by valentinegb** [comment]
Has that not been included in a preview release yet?

**Comment by soullifepan** [comment]
The issue remains in the latest stable and preview versions. I am currently unable to use JDTLS while coding.

**Comment by probably-neb** [comment]
Seems like it was, thanks @vitallium! @valentinegb it was released as part of [Release v0.183.0-pre · zed-industries/zed](https://github.com/zed-industries/zed/releases/tag/v0.183.0-pre), please make sure you're using that version or a newer version of Zed, and create a GitHub issue linking to #28173 if it is not working.
