### ISSUE TITLE
Pyright is broken with multiple sub-modules

### ISSUE THREAD

**Issue by orausch** [zed-industries/zed#29133]
### Summary

When using zed+pyright in a repository with multiple `pyproject.toml` sub-folders, the LSP becomes unusable. This seems like a regression at some point over the past few months (i.e. this used to work).

### Description
Given two  sub-modules `folder_a` and `folder_b`, I do:
1. open `folder_a/folder_a/file_a.py`
2. open `folder_b/folder_b/file_b.py`

Once I do this, the LSP is nigh-unusable (hover, jump-to-definition, etc. are all broken).

The LSP log then shows some sort of cyclic behavior (constantly re-adding the modules), and shows that we're constantly re-processing the same files (see the `Long operation` logs):
```python
Pyright language server 1.1.399 starting
Server root directory: file:///opt/homebrew/Caskroom/miniforge/base/envs/py311/lib/python3.11/site-packages/pyright/dist/dist
Starting service instance ""
Loading pyproject.toml file at /Users/oliver/code/<...>/folder_a/pyproject.toml
Setting pythonPath for service "": "<...>"
No include entries specified; assuming /Users/oliver/code/<...>/folder_a
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Found 404 source files
[FG] Long operation: checking: file:///Users/oliver/code/<...>/folder_a/folder_a/file_a.py (6775ms)
[FG] Long operation: analyzing: file:///Users/oliver/code/<...>/folder_a/folder_a/file_a.py (7397ms)
Starting service instance ""
Loading pyproject.toml file at /Users/oliver/code/<...>/folder_b/pyproject.toml
Setting pythonPath for service "": "<...>"
No include entries specified; assuming /Users/oliver/code/<...>/folder_b
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Found 196 source files
[FG] Long operation: checking: file:///Users/oliver/code/<...>/folder_b/folder_b/file_b.py (2209ms)
[FG] Long operation: analyzing: file:///Users/oliver/code/<...>/folder_b/folder_b/file_b.py (2209ms)
Loading pyproject.toml file at /Users/oliver/code/<...>/folder_a/pyproject.toml
Setting pythonPath for service "": "<...>"
No include entries specified; assuming /Users/oliver/code/<...>/folder_a
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Found 404 source files
Loading pyproject.toml file at /Users/oliver/code/<...>/folder_b/pyproject.toml
Setting pythonPath for service "": "<...>"
No include entries specified; assuming /Users/oliver/code/<...>/folder_b
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Found 196 source files
[FG] Long operation: checking: file:///Users/oliver/code/<...>/folder_a/folder_a/file_a.py (7009ms)
[FG] Long operation: analyzing: file:///Users/oliver/code/<...>/folder_a/folder_a/file_a.py (7439ms)
[FG] Long operation: checking: file:///Users/oliver/code/<...>/folder_b/folder_b/file_b.py (2025ms)
[FG] Long operation: analyzing: file:///Users/oliver/code/<...>/folder_b/folder_b/file_b.py (2232ms)
Loading pyproject.toml file at /Users/oliver/code/<...>/folder_a/pyproject.toml
Setting pythonPath for service "": "<...>"
No include entries specified; assuming /Users/oliver/code/<...>/folder_a
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Found 404 source files
Loading pyproject.toml file at /Users/oliver/code/<...>/folder_b/pyproject.toml
Setting pythonPath for service "": "<...>"
No include entries specified; assuming /Users/oliver/code/<...>/folder_b
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Found 196 source files
[FG] Long operation: checking: file:///Users/oliver/code/<...>/folder_a/folder_a/file_a.py (6541ms)
[FG] Long operation: analyzing: file:///Users/oliver/code/<...>/folder_a/folder_a/file_a.py (6944ms)
Loading pyproject.toml file at /Users/oliver/code/<...>/folder_a/pyproject.toml
Setting pythonPath for service "": "/opt/homebrew/Caskroom/miniforge/base/envs/py311/bin/python"
No include entries specified; assuming /Users/oliver/code/<...>/folder_a
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Found 404 source files
Loading pyproject.toml file at /Users/oliver/code/<...>/folder_b/pyproject.toml
Setting pythonPath for service "": "<...>"
No include entries specified; assuming /Users/oliver/code/<...>/folder_b
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Found 196 source files
```

Removing all `pyproject.toml` files avoids this bug.

Maybe it's suspicious that we're starting services with the same name `""`? `Starting service instance ""`

### Zed version
```
Zed: v0.183.6 (Zed Preview) 
OS: macOS 15.4.1
Memory: 16 GiB
Architecture: aarch64
```

**Comment by orausch** [comment]
(created with the "other" category because all the other templates were giving errors)

**Comment by osiewicz** [comment]
Can you check whether this is the case on with a release 0.179.x? I've merged https://github.com/zed-industries/zed/pull/28875 for 0.180 which changed how we select a project root for Python projects.

**Comment by orausch** [comment]
Hmm, I do still see it in 0.186.1, so possibly that revert didn't fix it?

**Comment by orausch** [comment]
@notpeter @osiewicz FYI https://github.com/zed-industries/zed/pull/33600 seems to resolve this for me
