### ISSUE TITLE
Debugger: <a short description of the Debugger bug>

### ISSUE THREAD

**Issue by helman44** [zed-industries/zed#32575]
### Summary

So, I have what I hope is a pretty elementary issue. My main concern is the performance of using the Zed debugger (dpbugpy) over remote development (SSH) on Zed. I am remoting into a RHEL machine from MacOS and have had no issues using Zed up until this point for remote development. I am simply trying to use the new debugger feature with a custom config I created (.zed/debug.json shown below). If I attempt to run the debugger using this config it simply results in an empty debugger pane with a loading circle spinning next to the label. If you have any insights that would be greatly appreciated.

e.g.

press F4
click Debug tab
click RunMyScript
Debug pane pops up and a tiny wheel churns next to RunMyScript infinitely

.zed/debug.json (below)
[
    {
        "label": "RunMyScript",
        "adapter": "Debugpy",
        "program": "path/to/my/script.py",
        "request": "launch",
        "args": [],
        "redirectOutput": true,
        "stopOnEntry": false,
        "subProcess": true,
        "cwd": "${ZED_WORKTREE_ROOT}",
        "pythonPath": "path/to/my/venv/bin/python"
    }
]

### Zed Version and System Specs

**LOCAL**
Zed: v0.190.4 (Zed) 
OS: macOS 15.5.0
Memory: 32 GiB
Architecture: aarch64

**REMOTE**
OS: RHEL 9.4
Memory: 512 GiB
Architecture: x86_64

**Comment by ConradIrwin** [comment]
It looks like we're not properly inheriting the environment over SSH. In 0.191, I think the infinite spinner should be fixed, but now you'll see an error instead of it just working.

Taking a look at wiring that up properly.

**Comment by idhelman** [comment]
I'm using 191.7 and still facing the same issues with the "infinite spinner". Is there something off with my debug.json that would cause this? I would appreciate some feedback. Thanks!

**Comment by ConradIrwin** [comment]
@helman44 The problems I fixed were two-fold:

1. The environment wasn't picked up properly leading to the app failing to boot. In this case there was a log about being unable to find "go".
2. There was a race between the SSH connection starting and the python debug adapter being ready to serve requests. Because SSH allowed Zed to "connect" to the debugger we assumed that it was working; but any send/recv would immediately fail because the other end of the SSH tunnel was not connected. In this case I just saw "debug adapter shutdown unexpectedly" in the console (but it now fails with "connection reset").

But if you're still seeing it in 0.191.7 it seems likely to be something else. Do you see anything in the Zed logs when this happens?

If helpful, I can debug with you over screenshare. Email conrad@zed.dev with some times that work for you (I'm in US Mountain Time).

**Comment by gmagostini** [comment]
Has this issue been resolved? Because I'm on version 0.202.2 and I'm still having this problem.

**Comment by SuperKenVery** [comment]
Me too, 0.201.5, still having an infinite spinner.
