### ISSUE TITLE
[SWAY] Zed window flashes rapidly on Sway/wlroots

### ISSUE THREAD

**Issue by gabvigano** [zed-industries/zed#32792]
### Summary

When launching Zed under Sway the window flashes rapidly. It works fine on Plasma Wayland.

### Description

I recently updated Sway, Vulkan and Zed. It was working fine until I suspended my system with 'systemctl suspend'. When I resumed, Zed's window started flashing. The issue persisted after reboot. I tried to downgrade Zed to 0.189.5 but it didn't solve the problem. I then downgraded Sway to 1.10.1 and now it works again.

Steps to reproduce:
1. Boot Arch.
2. Update Sway/wlroots to latest version.
3. Suspend ('systemctl suspend') and resume.
4. Launch Zed.
5. Observe flashing UI.

**Expected Behavior**:
Zed should open normally and be readable with a steady display.
**Actual Behavior**:
Zed's window flashes very quickly and it is unusable.

### Zed Version and System Specs

Zed: v0.190.6 (Zed) 
OS: Linux Wayland arch unknown
Memory: 15.5 GiB
Architecture: x86_64
GPU: Intel(R) HD Graphics 630 (KBL GT2) || Intel open-source Mesa driver || Mesa 25.1.3-arch1.3

**Update:** I just noticed #14101 which seems related. I hadn't seen it before opening this one. Someone with similar specs commented recently as well.

**Comment by prirai** [comment]
Same issue here with sway in wayland. Forcing Xwayland solves it.

Command for the same is: `env -u WAYLAND_DISPLAY zeditor`

**Comment by dbrgn** [comment]
I can confirm this, with Sway 1.11, both with Zed 0.190.4 and 0.190.6.

```
Zed: v0.190.6 (Zed) 
OS: Linux Wayland, Arch Linux
Memory: 30.9 GiB
Architecture: x86_64
GPU: Intel(R) Arc(tm) Graphics (MTL) || Intel open-source Mesa driver || Mesa 25.1.3-arch1.3
```

**Comment by dancek** [comment]
Same here. Installed Arch packages `extra/sway 1:1.11-1` + `extra/wlroots0.18 0.18.2-1` and rebooted, then Zed started flickering. I also have an Intel GPU, but a different one.

Suspend doesn't seem to be related to the issue. I haven't suspended the system recently.
```
Zed: v0.190.6 (Zed) 
OS: Linux Wayland arch unknown
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics (RPL-U) || Intel open-source Mesa driver || Mesa 25.1.3-arch1.3
```

**Comment by akrram09** [comment]
Same here

**Comment by akrram09** [comment]
Same issue

**Comment by tufo09** [comment]
I have the same issue, problem started after one of the later updates i did, seems to not happen if i force xwayland.
Specs for me are:
```
Zed: 0.190.6-1
OS: Arch Linux x86_64
Kernel: Linux 6.15.2-arch1-1
GPU: Intel Iris Xe Graphics
Mesa: 1:25.1.3-3
Memory: 7.55 GiB
```

**Comment by ossdesign** [comment]
I'm new at doing this issues thing on GitHub (so bare with me), but I started searching into because also have the same issue, seems like started with Sway 1.11 as for as well. Possibly an explicit sync related issue, I know that Sway 1.11 did something with this. More info on this Sway issue:

https://github.com/swaywm/sway/issues/8755

**Comment by npeeples** [comment]
i see it too, specs.

Zed: v0.199.6 (Zed) 
OS: Linux Wayland arch unknown
Memory: 15.6 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1060 6GB || NVIDIA || 575.64.05

**Comment by l-mb** [comment]
I'm seeing the same (on Intel Arrow Lake-P, or the Arc 140T as it is also known).

`xwayland force` did not fix the issue.

As noted on the sway issue, `export WLR_RENDER_NO_EXPLICIT_SYNC=1` before starting sway (in my case, via my `.profile`, which is loaded by `greetd/tuigreet` before starting sway) works.

Maybe this really is a sway issue more than a Zed one?

**Comment by SomeoneToIgnore** [comment]
> Maybe this really is a sway issue more than a Zed one?

Looks very much so, given https://github.com/zed-industries/zed/issues/32792#issuecomment-2993890415.
I'm not sure why this issue is open still.

**Comment by npeeples** [comment]
I flubbed the reading test, apologies.

https://github.com/zed-industries/zed/issues/32792#issuecomment-2993890415

`export WLR_RENDER_NO_EXPLICIT_SYNC=1` does indeed fix it for me as well. Sorry for the noise.

**Comment by bradlycarpenter** [comment]
> I flubbed the reading test, apologies.
> 
> [#32792 (comment)](https://github.com/zed-industries/zed/issues/32792#issuecomment-2993890415)
> 
> `export WLR_RENDER_NO_EXPLICIT_SYNC=1` does indeed fix it for me as well. Sorry for the noise.

Stupid question but where do you place this export?

**Comment by severindupouy** [comment]
I put it in the `/etc/environment` (no need to export, just add `WLR_RENDER_NO_EXPLICIT_SYNC=1` in the file).

**Comment by TIAcode** [comment]
Same problem, WLR_RENDER_NO_EXPLICIT_SYNC=1 didn't help. Intel Core Ultra 265k iGPU. `env -u WAYLAND_DISPLAY zeditor` did work.

**Comment by bool3max** [comment]
Same issue: 

```
Zed: 0.207.4
OS: Arch Linux x86_64
Kernel: Linux 6.17.1-arch1-1
GPU: AMD RX 6600
Mesa: 1:25.2.4-1
Sway: 1.11-1
Wlroots: 0.19-1
```

... but not caused by the suspend-resume cycle.

I'd been using Zed with an RX 580 without any issue up until recently, when I switched the graphics card to an RX 6600 the issue started manifesting. I run two displays, a 60Hz and a 160Hz one, and the green flickering is much more frantic on the high refresh-rate one, but present on both.

**Comment by Drive4Code** [comment]
Same issue here on fedora 43 sway spin, zed 0.213.3, on Lenovo X1. Installed zed both by the bash script and flatpak and both have the glitches. As suggested by @TIAcode `env -u WAYLAND_DISPLAY zed` does work as a temporary workaround.

**Comment by Schnurzel700** [comment]
using Hyprland and still having this issue

**Comment by mil-ad** [comment]
This has now been fixed in sway/wlroots: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4979#note_3385626

**Comment by Schnurzel700** [comment]
Still experiencing this issue on Hyprland. The wlroots/Sway fix does not help Hyprland users. Using `env -u WAYLAND_DISPLAY zeditor` (XWayland) resolves the flickering, but this is not ideal since I want to run Zed natively on Wayland. A Zed-side fix is still needed for Hyprland users.
