### ISSUE TITLE
Debugger: CodeLLDB doesn't use pretty formatters for C++ STL containers on macOS.

### ISSUE THREAD

**Issue by sr0lle** [zed-industries/zed#33116]
### Summary

The debugger fails to use the default pretty formatters for C++ STL types which are included in CodeLLDB/LLDB on macOS.

### Description
Steps to trigger the problem:
1. Compile the following minimal working example with Apple-Clang and debug flags, i.e. `clang++ -std=c++17 -g mwe.cpp -o mwe`

```cpp
#include <string>
#include <unordered_map>
#include <vector>

int main() {
  std::vector<int> values = {1, 2, 3, 4, 5};
  std::unordered_map<std::string, int> m;
  m["key1"] = 0;
  m["key2"] = 1;

  return 0;
}
```

and debug it using the CodeLLDB debugger.

**Expected Behavior**:

Use the default pretty formatters like when debugging with lldb:

![Image](https://github.com/user-attachments/assets/11618597-8631-42ff-91ca-181164987591)

**Actual Behavior**:

Only the implementation details of the linked C++ STL library (libc++) are visible inside the debugger. That's quite cumbersome for debugging purposes, in my opinion.

![Image](https://github.com/user-attachments/assets/5359f13e-ec6f-49e0-ac31-3cb9b183ba20)

![Image](https://github.com/user-attachments/assets/6b6a8659-e63f-46c2-81b1-1715cb72d280)

### Zed Version and System Specs

Zed: v0.191.7 (Zed) 
OS: macOS 15.4.0
Memory: 16 GiB
Architecture: aarch64

**Comment by BaumianerNiklas** [comment]
Doesn't seem to be macOS-exclusive, as I get the same behavior on Linux.

Zed: Zed 0.191.7
OS: Fedora Linux 42 (KDE Plasma Desktop Edition) x86_64
Memory: 32 GB
Architecture: x86_64

**Comment by feeiyu** [comment]
It's works after set the sourceLanguages to `cpp`.  

```xml
[
    {
        "label": "Build Binary",
        "adapter": "CodeLLDB",
        "program": "/home/feiyu/code/playground-cpp/build/main",
        "request": "launch",
        "sourceLanguages": ["cpp"]
    }
]
```
![Image](https://github.com/user-attachments/assets/4f66c7b1-5658-4c44-9a3a-e340d28595b9)


The default sourceLanguages:
https://github.com/zed-industries/zed/blob/3b9f504d757b7d8a00d0993ef4d6a78e6ea1a927/crates/dap_adapters/src/codelldb.rs#L369

**Comment by cole-miller** [comment]
Fixed by #33670

**Comment by redsigma** [comment]
this doesn't fixes `std::unordered_map` . For example doing this
```
  std::unordered_map<int, std::string> map4;
  map4.emplace(0, "key1");
  map4.emplace(1, "key2");
```

Still shows  `<not available>`

<img width="681" height="155" alt="Image" src="https://github.com/user-attachments/assets/f95c9193-36e2-4711-b1bb-5a3c43873ae7" />


Tested with latest   v0.210.4 428ef505984eb7dd6096cbe6ff4e07f293075d0d
