### ISSUE TITLE
file_scan_exclusions excludes files from git panel

### ISSUE THREAD

**Issue by v57** [zed-industries/zed#33167]
### Summary

Git panel should display all git changes

### Description
I have added bun.lock, package.json and other non code files to file_scan_exclusions, so they will not make up space in my files list. Problem is that when i think i have commited everything i saw that code not works when i download it from github. I checked if i clean up file_scan_exclusions, i will see code changes and i saw them! 
I don't think this is an expected behavior so i'm posting it as a bug

Steps to reproduce:
1. Create git repository
2. Create file.txt
3. Add file.txt to file_scan_exclusions
4. Check git panel

**Expected Behavior**:
Git changes should only exclude from .gitignore and .git
**Actual Behavior**:
Git changes excluded from both .gitignore/.git and file_scan_exclusions

### Zed Version and System Specs

Zed: v0.189.5 (Zed) 
OS: macOS 15.5.0
Memory: 18 GiB
Architecture: aarch64

**Comment by mattfbacon** [comment]
The problem is with the file change detection which ignores excluded files. But more than usual, because you would expect that if you change an ignored file and then a not-ignored file, Zed would notice the change to the ignored file, but that is not the case, because Zed (smartly) only passes the paths of the changed files to `git status`. However, if you restart zed, you should see that all the changes are there.

To fix this I guess we would need to track changes of all files, even excluded ones, at least for Git.

**Comment by SomeoneToIgnore** [comment]
>  I don't think this is an expected behavior so i'm posting it as a bug

This is an expected behavior, as it literally excludes the things from Zed's background scanner and was built with the idea "remove the files from everywhere".

So using it as 

> I have added bun.lock, package.json and other non code files to file_scan_exclusions, so they will not make up space in my files list.

is wrong and we should solve this issue instead of trying to bend the original intent of the `file_scan_exclusions`.

I have no good ideas except adding another "project panel exclusion" but maybe there's a better way?
Creating a feature request in https://github.com/zed-industries/zed/discussions with a particular proposal (that does not touch `file_scan_exclusions`) would be great.

**Comment by mattfbacon** [comment]
The issue is still not fixed as the excluded files actually do get shown in the Git changes list if you restart the editor.

**Comment by SomeoneToIgnore** [comment]
The issue is about something else and odd, but 

> excluded files actually do get shown in the Git changes list if you restart the editor

is a good issue worth fixing.
