### ISSUE TITLE
Git UI strips newline breaks from commit message description

### ISSUE THREAD

**Issue by valsoray-dev** [zed-industries/zed#33274]
### Summary

Git UI strips newline breaks from the commit message description after commiting.

### Description

In the built-in Git panel, typing a multi-line commit message description does not preserve those line breaks.
Instead, upon commit, Zed concatenates all text into a single line, making longer messages unreadable.

Steps to reproduce:
1. In the commit message input, put the following: 
```text
Test commit message

- first line
- second line
- third line
```
2. Commit changes
3. Check git log or GitHub commit history. 

**Expected Behavior**: Commit message description should look exactly as typed.
**Actual Behavior**: The description is collapsed into one line:
```text
Test commit message

- first line - second line - third line
```

<details><summary>Screenshots</summary>
1. lazygit's log output

![Image](https://github.com/user-attachments/assets/44b6f3c5-bc58-44fd-8e6b-6a6ac385b894)

2. GitHub commit history
![Image](https://github.com/user-attachments/assets/265c8fbc-75bd-492a-b98d-463390a94784)

</details>

### Zed Version and System Specs

Zed: v0.191.7 (Zed) 
OS: Linux Wayland arch unknown
Memory: 15.4 GiB
Architecture: x86_64
GPU: NVIDIA GeForce MX230 || NVIDIA || 575.64

**Comment by imumesh18** [comment]
This was fixed in this PR: https://github.com/zed-industries/zed/pull/32114 . Not sure what could be going wrong here.

**Comment by soukand** [comment]
Still happens to me aswell

**Comment by archaistvolts** [comment]
Still happening to me on 0.203.5.  Seems like this needs to be re-opened.
