### ISSUE TITLE
Zed doesn't show up in alt-tab switcher on GNOME until several seconds pass

### ISSUE THREAD

**Issue by NoTuxNoBux** [zed-industries/zed#33897]
### Summary

Zed doesn't show up in alt-tab switcher on GNOME 48 until several seconds pass.

### Description

This is very likely related to [`StartupNotify` being set to `true` in the desktop file](https://github.com/zed-industries/zed/blob/5253702200f4fb491b6608ac0a0c6df89b224b0f/crates/zed/resources/zed.desktop.in#L8). [Similar issues exist for VSCode](https://github.com/flathub/com.visualstudio.code/issues/388) and other applications. The VSCodium Flatpak has resolved this by setting `StartupNotify` to `false`.

Steps to reproduce:
1. Start Zed (Flatpak) on GNOME 48.
2. Press alt-tab to switch to another application than Zed.
3. Hold alt-tab to see the window list.

**Expected Behavior**: Zed shows up in the list and is the next application to switch back to.
**Actual Behavior**: Zed doesn't show up until several seconds have passed ([the timeout in mutter is reached](https://gitlab.gnome.org/GNOME/mutter/-/issues/2689)).

### Zed Version and System Specs

Zed: v0.193.3 (Zed) 
OS: Linux Wayland org.freedesktop.platform 24.08
Memory: 30.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 4090 Laptop GPU || NVIDIA || 575.64

**Comment by Lukas-Fletcher** [comment]
I’m also seeing this issue on NixOS using GNOME with Wayland. In addition to Alt+Tab failing to bring Zed back into focus, this also affects workflows that use the SUPER+number keys to switch to pinned applications on the dash.

**Comment by rupalbarman** [comment]
Can confirm this bug still persists. Linux 6.19 here on GNOME wayland (fedora). I noticed it takes about 5-7 seconds in my case for the zed icon to be visible in the app switcher (alt + tab)

Does anyone know if its the same on KDE as well?

**Comment by georgestafilidis** [comment]
Do you guys get a busy cursor when launching zed editor?

**Comment by voytxt** [comment]
fixed by #59995 in v1.10

**Comment by rupalbarman** [comment]
I'm afraid issue still persists for me. I guess the flatpak sandbox is causing this perhaps?
