### ISSUE TITLE
HTML tag vim text object doesn't work in HTML/ERB language mode

### ISSUE THREAD

**Issue by taylorthurlow** [zed-industries/zed#34837]
### Summary

The vim "tag" text object works in the HTML language mode, but not the HTML/ERB language mode.

### Description

When editing a file in HTML language mode, I can use, for example, `cit` to change the content of the HTML tag the cursor is in (or when the cursor is on top of the HTML tag itself). `cat`, plus the other variations like `dit/dat/yat/yit`. When using the HTML/ERB language mode, none of these text objects function.

The issue appears to be caused by the presence of any ERB tags in the file, which is always going to affect the HTML/ERB language mode, as that's the entire point of it.

The original issue/request is https://github.com/zed-industries/zed/issues/16722. Looks like a recent comment on that issue agrees that this is not working in an HTML/ERB context.

### Reproduction

```html
<!-- An HTML file containing only HTML, with Zed in the HTML/ERB language mode -->

<p>
  Text content
</p>
```

Placing the cursor inside the tag, then pressing `d`, `i`, `t`, deletes the content inside the tag:

```html
<p></p>
```

Starting instead from a file containing an ERB tag:

```html
<!-- An HTML file containing HTML _and_ ERB, with Zed in the HTML/ERB language mode -->

<% if some_condition %>
  <p>
    Text content
  </p>
<% end %>
```

Pressing `d`, `i`, then `t` has no effect on the text. It should have resulted in:

```html
<% if some_condition %>
  <p></p>
<% end %>
```

Not including a zed.log, as there are no logs written to the file when doing any of this testing.

### Zed Version and System Specs

Zed: v0.195.5 (Zed) 
OS: macOS 15.5.0
Memory: 24 GiB
Architecture: aarch64

Also tested with zed-preview v0.196.4 with the exact same results.

**Comment by brentd** [comment]
I noticed this today too and am having some success with this workaround: using the `workspace::SendKeyStrokes` action [documented here](https://zed.dev/docs/key-bindings#remapping-keys) we can simulate `c i t`, my most used tag operation.

```json
  {
    "context": "vim_operator == i && extension == erb",
    "bindings": {
      "t": ["workspace::SendKeystrokes", "f > l d t < i"]
    }
  },
```

This is a poor replacement though, because it doesn't work for blocks of HTML (only single lines), doesn't work if your cursor is already inside the tag, and really only useful if the tag has just one text node you're trying to replace.

**Comment by vitallium** [comment]
I think this should be fixed now that https://github.com/zed-industries/zed/pull/41111 has been merged. Can anyone confirm? Thanks!

![Image](https://github.com/user-attachments/assets/934481ad-1746-4c33-82ba-be9a7e1181cc)

**Comment by taylorthurlow** [comment]
This is mostly working for me in 0.212.6, but placing the cursor _inside_ the ERB tag and using a shortcut still does nothing. A lot better than before, though.

```html
<p>
  <%= some_variable <!-- cursor here --> %>
</p>
```

The the cursor in the above location means the shortcuts do nothing.

**Comment by taylorthurlow** [comment]
This is still an issue in 1.0.0, exactly as described in [my prior comment](https://github.com/zed-industries/zed/issues/34837#issuecomment-3542998855).
