### ISSUE TITLE
Open new terminal on Zed with folder have Spaces between its name

### ISSUE THREAD

**Issue by vuthanhtrung2010** [zed-industries/zed#35087]
### Summary

Hi I have a folder named "Code C"

It looks like it doesnt warp the path in quotes/double quotes so it like this

<img width="923" height="241" alt="Image" src="https://github.com/user-attachments/assets/e2b95f43-bda1-4138-ba78-fa09374c6abf" />

### Zed Version and System Specs

Zed: v0.196.6 (Zed) 
OS: Linux X11 arch unknown
Memory: 7.6 GiB
Architecture: x86_64
GPU: Intel(R) HD Graphics 520 (SKL GT2) || Intel open-source Mesa driver || Mesa 25.1.6-arch1.1

**Comment by osiewicz** [comment]
Is this with a remote project?

**Comment by vuthanhtrung2010** [comment]
> Is this with a remote project?

Yes it is.

**Comment by notpeter** [comment]
I was not able to reproduce.

These work for me:
```sh
ssh think21 mkdir "'foo bar'"
zed "ssh://think21/~/foo bar/"
```

Or via: 
`project: open remotes`
-> under my host `Open folder`
-> type `/home/peter/foo bar`

Can you provide explicit steps which trigger this behavior?

**Comment by osiewicz** [comment]
@notpeter I believe this might've been resolved with https://github.com/zed-industries/zed/pull/34844. Sorz for not tagging this issue as resolved.

**Comment by notpeter** [comment]
Wonderful. Thank you @osiewicz.
If you're still seeing this @vuthanhtrung2010 please comment with details and happy to reopen.
Thanks for reporting.

**Comment by Slipstream-Max** [comment]
> Wonderful. Thank you [@osiewicz](https://github.com/osiewicz). If you're still seeing this [@vuthanhtrung2010](https://github.com/vuthanhtrung2010) please comment with details and happy to reopen. Thanks for reporting.

Thanks for your hard work! But i still encounter simillar issue in https://github.com/zed-industries/zed/issues/33459.
Do you have any idea?
