### ISSUE TITLE
New windows open directly on top of each other on Mac

### ISSUE THREAD

**Issue by robinplace** [zed-industries/zed#36206]
### Summary

When opening new windows (with command-shift-n) they usually end up stacked directly on top of each other. This makes it difficult to tell that the window-open keystroke went through, and sometimes it appears that instead of a new window opening, all tabs in the current workspace closed.

Steps to reproduce:
1. Open Zed
2. Hit command-shift-n a few times
3. Observe that the windows stack directly on top of each other

**Expected Behavior**:

Here's my browser after hitting command-n, with a standard offset.

<img width="214" alt="Image" src="https://github.com/user-attachments/assets/a04a4b83-b2b1-431e-8050-54a104e4c3b4" />

This offset is always applied relative to the window currently in the foreground. It's something like 20 pixels and is really helpful at telegraphing the success of the new-window-open operation.

### Zed Version and System Specs

Zed: v0.196.6 (Zed) 
OS: macOS 15.4.0
Memory: 36 GiB
Architecture: aarch64

**Comment by robinplace** [comment]
Hm I'm working on a pull request for another issue and noticed this problem doesn't occur on a fresh build from current `main` branch. This issue may have been fixed somewhere between v0.196.6 and 4238e640fa.

@danilo-leal heads up, in case you've started any work on this.

**Comment by notpeter** [comment]
I can still reproduce this issue with v0.201.0 (Zed Nightly 9e8ec72bd5c697edc6b61f4e18542afc4e343a1b) and with current main.

Thanks for reporting.

**Comment by ghost** [comment]
Hi @notpeter is this issue available for me to contribute? I would love to take this

**Comment by hiradp** [comment]
Hello - I'm on commit 0a9f40787216f18ee2f4dc79211877d1af496284 (latest on main) and I think I'm getting the expected behavior

<img width="1033" height="876" alt="Image" src="https://github.com/user-attachments/assets/05ef5298-2eac-4b98-8c5b-8bbcea727aae" />

but I can reproduce on Zed 0.201.5

**Comment by ssaakaash** [comment]
I can still reproduce the bug on the latest commit [2790eb604a](https://github.com/zed-industries/zed/commit/2790eb604a1de04107f2412dadc06d4f75415380) on main

**Comment by arunn03** [comment]
Hi @notpeter is this bug open so that I can contribute to it?
