### ISSUE TITLE
pytest launch button not working on Windows

### ISSUE THREAD

**Issue by lunacd** [zed-industries/zed#39007]
### Summary

pytest launch button fails with:

```
ParserError:
Line |
   1 |  ". \"C:\\Users\\...\\.venv\\Scripts\\activat …
     |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unexpected token 'C:\\Users\\...\\.venv\\Scripts\\activate.ps1\";
     | &\"C:\\Users\\haowenl\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShell_8wekyb3d8bbwe\\pwsh.exe\" -C \"C:\\Users\\...\\.venv\\Scripts\\python.exe' in expression or statement.
```

### Description
Steps to trigger the problem:
1. Install Zed Nightly on Windows
2. Create `tests/test_foo.py` with:
```py
def test_foo():
    assert True
```
3. Create a venv with `uv venv`
4. Select the venv in zed
5. Click on the "play" button next to a test case to run test

**Expected Behavior**: Test runs
**Actual Behavior**: Test fails to run

### Zed Version and System Specs

Zed: v0.207.0 (Zed Nightly a55dff78342cff9a0cf18e283b3a5b78846c82de) 
OS: Windows 10.0.26100
Memory: 31.1 GiB
Architecture: x86_64
GPU: AMD Radeon RX 9070 || AMD Corporation || 25.9.1 (25.10.25.10-250825a-418637C-AMD-Software-Adrenalin-Edition)

**Comment by MrSubidubi** [comment]
Thanks for the report, that should definitely work out of the box!

Could you perhaps add a minimap snippet to the issue to reproduce this more easily? Not necessarily needed, but would definitely help and be appreciated. Thanks!

**Comment by lunacd** [comment]
> Could you perhaps add a minimap snippet to the issue to reproduce this more easily? Not necessarily needed, but would definitely help and be appreciated. Thanks!

Updated the reproduction instructions in the description :)

**Comment by MrSubidubi** [comment]
Nice, thank you very much!

**Comment by MrSubidubi** [comment]
Just checked back with the team and this should hopefully have been resolved by some fixes in the latest release! Is this fixed for you as well?

**Comment by lunacd** [comment]
Yes! I now got through the first error. But it still fails to run the test with:

```
============================================= no tests ran in 0.07s =============================================
ERROR: not found: C:\Users\...\tests\test_foo.py::test_foo\
(no match in any of [<Module test_foo.py>])
```

The trailing `\` looks suspicious

**Comment by MrSubidubi** [comment]
Definitely does, thanks for getting back!

**Comment by kubkon** [comment]
Some update from me that I have found the issue (it's todo with double-quoting strings when passing the invocation to the shell), and working on a fix.
