### ISSUE TITLE
Windows: Session restore not working when settings UI is open

### ISSUE THREAD

**Issue by mylvghb** [zed-industries/zed#40314]
### Summary

After opening the Settings UI, if you click to quit Zed directly, the settings window fails to close along with it; when you restart Zed, all previously opened projects are gone.

**Description**

Steps to reproduce:
1. Opening the Settings UI.
2. Close Zed IDE.
3. Close the Settings UI.
3. Reopen Zed IDE.

**Expected Behavior**:

Auto-close the Settings UI and restore previously opened projects on restart.

**Actual Behavior**:

<img width="1900" height="964" alt="Image" src="https://github.com/user-attachments/assets/31e625b0-b7c5-4529-b056-1b6f8f111bc3" />

<img width="1092" height="872" alt="Image" src="https://github.com/user-attachments/assets/0562ba15-1cd5-4ae5-bf79-3c51163492f4" />

<img width="1927" height="1003" alt="Image" src="https://github.com/user-attachments/assets/ac796556-70fe-43cf-a622-55f345357a16" />

### Zed Version and System Specs

Zed: v0.208.4 (Zed) 
OS: Windows 10.0.26100
Memory: 63.6 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 730 || Intel Corporation || 31.0.101.5522

**Comment by P1n3appl3** [comment]
Just to be sure: what is the `Restore On Startup` field set to in your settings? The default is to re-open the session so if you haven't changed that setting then that's indeed a bug.

Regarding auto-closing the settings UI when you've closed the last window. I'm not sure whether that's intentional or not. I've just checked and even when setting `On Last Window Close` is set to `Quit App`, it doesn't quit when all editor windows are closed but the settings UI is still open.

**Comment by mylvghb** [comment]
@P1n3appl3 I believe this is a bug—when Zed quits, all related UI windows should close as well.

**Comment by mylvghb** [comment]
@P1n3appl3 The value of `Restore On Startup` remains the default: `last_session`.

**Comment by ofetch** [comment]
Dupe #39786

**Comment by P1n3appl3** [comment]
Now that ^ is resolved, I think the remaining issue is session restore not working. Could you confirm that it's happening consistently (not just when you have settings UI open) and also share your settings file so we can try to reproduce.

**Comment by mylvghb** [comment]
Currently, this only happens under the circumstances mentioned above.

**settings file**

[settings.json](https://github.com/user-attachments/files/22961326/settings.json)

**Comment by franciskafyi** [comment]
Can you update to the latest version, please? Settings UI not closing should have been fixed. I do think we have an issue with restoring the last session though.

**Comment by maxbrunsfeld** [comment]
I can't reproduce this. The settings window does not prevent my session from restoring my previous windows on startup.

**Comment by mylvghb** [comment]
I've already updated to the latest version, but this issue still occurs.

**Zed Version and System Specs**

Zed: v0.208.6 (Zed) 
OS: Windows 10.0.26200
Memory: 63.6 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 730 || Intel Corporation || 31.0.101.5522

**Video**

https://github.com/user-attachments/assets/414deaf6-3bec-415b-90c8-97155a7286bd

**Comment by franciskafyi** [comment]
@miguelraz was this the issue we ran into together? You had the Settings window open I think 👀 Do you mind taking another look to see if you can repro this?

**Comment by miguelraz** [comment]
Same here, can't reproduce it.

https://github.com/user-attachments/assets/387fab5c-417f-43a4-8dca-59bf96aa2dd2

Will be closing as completed. Please comment if the issue is still there for you.
