### ISSUE TITLE
Python: ty goto definition not working

### ISSUE THREAD

**Issue by Liyixin95** [zed-industries/zed#40446]
### Summary

Ty's goto definition and inlay type hit not working.

### Description
here is my setting:
```
"languages": {
        "Python": {
            "language_servers": ["ty", "ruff", "!basedpyright", "!pyrefly"],
            "format_on_save": "on",
            "formatter": [
                {
                    "code_action": "source.organizeImports.ruff"
                }
            ]
        }
    }
```
and ty setting:
```
        "ty": {
            "binary": {
                "path": "/root/.local/bin/ty",
                "arguments": ["server"]
            }
        },
```
and server info:
```
* Server: ty (id 0)

* Binary: Unknown

* Registered workspace folders:


* Capabilities: {
  "positionEncoding": "utf-16",
  "textDocumentSync": {
    "openClose": true,
    "change": 2
  },
  "selectionRangeProvider": true,
  "hoverProvider": true,
  "completionProvider": {
    "triggerCharacters": [
      "."
    ]
  },
  "signatureHelpProvider": {
    "triggerCharacters": [
      "(",
      ","
    ],
    "retriggerCharacters": [
      ")"
    ]
  },
  "definitionProvider": true,
  "typeDefinitionProvider": true,
  "referencesProvider": true,
  "documentHighlightProvider": true,
  "documentSymbolProvider": true,
  "workspaceSymbolProvider": true,
  "declarationProvider": true,
  "executeCommandProvider": {
    "commands": [
      "ty.printDebugInformation"
    ],
    "workDoneProgress": false
  },
  "semanticTokensProvider": {
    "legend": {
      "tokenTypes": [
        "namespace",
        "class",
        "parameter",
        "selfParameter",
        "clsParameter",
        "variable",
        "property",
        "function",
        "method",
        "keyword",
        "string",
        "number",
        "decorator",
        "builtinConstant",
        "typeParameter"
      ],
      "tokenModifiers": [
        "definition",
        "readonly",
        "async"
      ]
    },
    "range": true,
    "full": true
  },
  "inlayHintProvider": {},
  "diagnosticProvider": {
    "identifier": "ty",
    "interFileDependencies": true,
    "workspaceDiagnostics": false,
    "workDoneProgress": false
  }
}

* Configuration: Unknown
```

### Zed Version and System Specs

Zed Preview 0.209.1 
bebf4b0497701adea820f69a8c55d68a2d1f4b86

**Comment by smitbarmase** [comment]
Thanks for the report. I'm curious if you are facing this in previous versions of Zed, or Zed Stable. Can you give it a try and let me know? Trying to figure out if it's a recent regression and when it might have been introduced.

**Comment by Liyixin95** [comment]
> Thanks for the report. I'm curious if you are facing this in previous versions of Zed, or Zed Stable. Can you give it a try and let me know? Trying to figure out if it's a recent regression and when it might have been introduced.

@smitbarmase  I remember that the last time Ty was still able to work in Zed was before Zed integrated Ty internally. Since Ty has now been removed from the plugin market, I may not be able to roll back to an earlier version to try.

Additionally, the hover is working properly.

**Comment by Liyixin95** [comment]
@smitbarmase I find my local zed work fine with ty. The remote zed still can't use ty's goto function.

And if I open a local python project, then the remote ty can work! It's so strange.

**Comment by janickm** [comment]
Same on my end, local zed with ty works fine (ty logs indicate files are parsed), but ty @ remote zed doesn't index any files / doesn't seem to start up

**Comment by Greg-Tarr** [comment]
Happening to me too, remote WSL on Windows Zed.

**Comment by Liyixin95** [comment]
fixed by #42723

**Comment by carlesoctav** [comment]
i still get this issue, :)

rpc without opening local project


```json
// Send:
{"jsonrpc":"2.0","id":18,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///mnt/carles/tunix3/tunix/rl/grpo/grpo_learner.py"},"range":{"start":{"line":522,"character":19},"end":{"line":522,"character":19}},"context":{"diagnostics":[],"only":["quickfix"]}}}

// Receive:
{"jsonrpc":"2.0","id":18,"result":null}
```



rpc with ty running both on local and remote (by opening local project that use ty)

```json
// Send:
{"jsonrpc":"2.0","id":108,"method":"textDocument/definition","params":{"textDocument":{"uri":"file:///mnt/carles/tunix3/tunix/rl/grpo/grpo_learner.py"},"position":{"line":522,"character":14}}}

// Receive:
{"jsonrpc":"2.0","id":108,"result":[{"originSelectionRange":{"end":{"character":25,"line":522},"start":{"character":14,"line":522}},"targetRange":{"end":{"character":46,"line":397},"start":{"character":0,"line":100}},"targetSelectionRange":{"end":{"character":17,"line":100},"start":{"character":6,"line":100}},"targetUri":"file:///mnt/carles/tunix3/tunix/rl/grpo/grpo_learner.py"}]}

// Send:
{"jsonrpc":"2.0","id":109,"method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///mnt/carles/tunix3/tunix/rl/grpo/grpo_learner.py"},"position":{"line":100,"character":6}}}

// Send:
{"jsonrpc":"2.0","id":110,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///mnt/carles/tunix3/tunix/rl/grpo/grpo_learner.py"},"range":{"start":{"line":100,"character":6},"end":{"line":100,"character":6}},"context":{"diagnostics":[],"only":["quickfix"]}}}

// Receive:
{"jsonrpc":"2.0","id":110,"result":null}

// Receive:
{"jsonrpc":"2.0","id":109,"result":[{"kind":1,"range":{"end":{"character":17,"line":100},"start":{"character":6,"line":100}}},{"kind":2,"range":{"end":{"character":25,"line":522},"start":{"character":14,"line":522}}}]}
```

zed 0.217.3 stable with ty 0.0.6

**Comment by hierr** [comment]
I am also having this issue on Zed 0.218.6 on WSL2. Same for "Rename Symbol".
