### ISSUE TITLE
Hover states are activated when positioned behind other windows

### ISSUE THREAD

**Issue by andykent** [zed-industries/zed#40691]
### Summary

On macOS hover states are activated even when Zed is not active and is positioned behind other windows, this can be quite distracting. I have included a video to illustrate the issue.

https://github.com/user-attachments/assets/be44cf77-c5ce-4047-8db2-a22d1a9a6384

Steps to reproduce:
1. Open zed on a screen that has hover states, e.g. the Review Changes screen
2. Open another window in front of Zed and partially obscuring it, e.g. Safari
3. Move your mouse over the frontmost window where the hover states are in Zed
4. Note that the hover states are visibly changing in the unfocussed Zed window

**Expected Behavior**:

Zed does not show hover states when it does not have focus

**Actual Behavior**:

Zed shows hover states when it doesn't have focus, even when the hover location is obscured by another window.

### Zed Version and System Specs

Zed: v0.208.5 (Zed) 
OS: macOS 26.1 (Build 25B5062e)
Memory: 32 GiB
Architecture: aarch64

**Comment by smitbarmase** [comment]
Yep, I can reproduce it too. Thanks for the report, we should fix this.

**Comment by yeskunall** [comment]
### Summary


When a Zed window is not focused, editor hover popovers still appear as the mouse moves over, which is distracting.

### Description


When a Zed window is not focused, hover popovers still appear as the mouse pointer moves over it. If the Zed window is partially obscured by the application in use, this can be very distracting.

I'm running macOS 15; I have also reproduced this behaviour on Kubuntu 24.04.

### settings.json
<details><summary>click to expand</summary>

```json
  "git": {
    "inline_blame": {
      "show_commit_summary": true
    }
  }

```
</details>

Steps to reproduce:
1. Open a Zed window on a project that uses git.
2. Place the cursor on a line of code; the git blame should be shown to the right of the line: 

<img width="833" height="26" alt="Image" src="https://github.com/user-attachments/assets/2910ac31-57ee-4e20-9a2f-13b7f10ba424" />

3. Switch to another application.
4. Move the mouse pointer over the line of code in the Zed window without focusing Zed. 

**Expected Behaviour**:

Either:

* No hover popover appears except when the Zed window is focused, _or_
* There is a setting under `Editor > Hover Popover` to control whether or not this should happen.

The current behaviour of always displaying it means I cannot switch to another window while leaving Zed on the screen, as I will see things that are not currently relevant to me popping up and down as I move the mouse pointer.

The only way around this is to hide Zed when I'm not using it; even then, if I _am_ using Zed, but not _that_ window, I can only avoid this by minimising the windows I'm not using and expanding them again afterwards.

Zed should not constrain the way I organise* my windows like this.

I accept that some (less easily distracted) people will find the current behaviour useful, so this would probably be better as a setting.

* For small values of "organise" 🙂 

**Actual Behaviour**:

The hover popover appears anyway. In this image, Vivaldi (on the left) is focused, but Zed still shows the hover popover when the mouse moves over the line of code where Zed's cursor is.

<img width="1045" height="388" alt="Image" src="https://github.com/user-attachments/assets/5a7b69b3-54a0-4ce3-bb06-8cb50ae06677" />




### Zed Version and System Specs

Zed: v0.213.3 (Zed) 
OS: macOS 15.7.2
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `Zed.log` file to this issue.

Doesn't appear to be anything relevant.

<details><summary>Zed.log</summary>


```log
2025-11-20T11:02:32+00:00 INFO  [auto_update] Auto Update: checking for updates
2025-11-20T12:02:32+00:00 INFO  [auto_update] Auto Update: checking for updates
```

</details>

---

###### _Originally posted by [@unikitty37](https://github.com/unikitty37)_
