### ISSUE TITLE
Windows: very flaky ssh handling

### ISSUE THREAD

**Issue by rmatte** [zed-industries/zed#40755]
### Summary

I'm seeing really strange behavior in the Windows version when trying to connect to a remote server in Zed via ssh.

**My Setup**

I have the following in the Zed json settings file...

"proxy": "socks5h://127.0.0.1:1111"

I also have the following in my `C:\Users\<user>\.ssh\config` file...

```
Host myhost.mydomain.com
  ProxyCommand "C:\Program Files (x86)\Nmap\ncat.exe" --proxy 127.0.0.1:1111 --proxy-type socks5 %h %p
  User <user>
  ConnectTimeout 30
  Compression yes
  TCPKeepAlive yes
  ServerAliveInterval 15
  ServerAliveCountMax 3
```

**Observed Behavior**

When I attempt to connect remotely via Zed it will spawn a process that looks like this...

```
"ssh" -N ssh://user@myhost.mydomain.com
```

And then it just sits there spinning on "Connecting..." seemingly forever. If I close Zed, kill the ssh process(es), then retry the connection repeatedly like this, and let it sit for many minutes each time I try, it will eventually randomly run into a state where it closes that ssh -N process and moves on to spawning other ssh processes which do connect, and I'm then able to interact with the files and open a terminal window within Zed that works.

Once that happens if I leave it sitting for another around 5 to 10 minutes the terminal window I opened in Zed will become disconnected with a message that the remote side terminated the connection (it's like it's not sending keepalives). The ssh connection for the code editor continues to work for a while longer but then it eventually becomes disconnected as well and is unable to reconnect afterwards without the same random retry song and dance with closing Zed, killing all ssh.exe processes, and killing the server side Zed stuff in between each attempt as needed.

I have tried using the ProxyJump option in the ssh config as well instead of ProxyCommand to go through a jumbox instead of the proxy, but that works even worse in Zed for whatever reason even though it works fine at the command line.

Another thing I have found is if I use an ssh key file for authentication instead of typing in a password this never works at all and I just get a message that the connection has failed about 5 seconds after starting it. If I ssh to the host manually from the command line using the same ssh.exe executable I'm able to get in fine with the key, so I'm not sure what's going on in Zed to cause this, seems like some sort of weird timing issue or something.

It's like ssh.exe is in fact working but Zed is doing some weird stuff with it that's making it fail most of the time inside of Zed and disconnect shortly after connecting when it does work. This seems very buggy and looks like it's going to require significant additional dev work and testing to smooth this out. In its present state it's totally unusable and I'll unfortunately have to look at other IDEs.

Another thing to note is that I use several other SSH based and web based apps on this system, all of which are connecting through the exact same socks5 proxy connection, and they all work flawlessly. Using the ssh.exe command works flawlessly outside of Zed as well. I'm only seeing these issues with Zed itself. I have also tried removing all ssh config options except the ProxyCommand and User ones, but that did not help either.

Also as an aside, I noticed that when I didn't specify User in the ssh config file, if I went to click to open an existing folder that I already had added through the remote connection it would try to use my windows username instead of the account username that I originally created the SSH connection for within Zed. Seems like another bug where the username should get auto-saved to the settings file on first create and it isn't being.

### Zed Version and System Specs

Zed: v0.208.6 (Zed) 
OS: Windows 10.0.26100 (I'm running Windows 11)
Memory: 31.7 GiB
Architecture: x86_64 (Intel i9-13900HK)
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || 32.0.101.6987

**Comment by rmatte** [comment]
Just an additional note that it would be nice to see live informational output while ssh connections are being made, or at least have the option to. It would be nice to be able to see verbose output of what it's doing at each step as it's connecting so that we can understand where this is getting hung up for the purposes of debugging things like this. Seeing "Connecting..." spinning seemingly endlessly isn't very helpful, and I can only see so much by looking for the ssh processes in task manager.

**Comment by franciskafyi** [comment]
Thank you for the thorough report. The team will take a closer look ASAP.

**Comment by anarchy89** [comment]
im not sure if this is the same but when I connect to my mac m1 max as the server using my zed on windows 11 as the client, it worked the first few times.

now when i try to connect i just get an endless trying to connect loop. not sure how do debug this or help as theres no error message or outputs of any kind.

i have no issue using my m3 air as the client when connecting to my m1 max as the server.

im connecting to 192.168.1.10 and i am 192.168.1.11 or .12 on the same lan network not using a proxy.

If i remove the server and restart it seems to work. 

also if i accidentally connect to the root directory it uses a crazy amount of cpu and hangs.

**Comment by rmatte** [comment]
> im not sure if this is the same but when I connect to my mac m1 max as the server using my zed on windows 11 as the client, it worked the first few times.
>
>now when i try to connect i just get an endless trying to connect loop. not sure how do debug this or help as theres no error message or outputs of any kind.

That does certainly sound similar to the behavior that I'm seeing, could be related to whatever is causing what I'm seeing in the Windows version.

**Comment by localcc** [comment]
Could you verify if this happens on the latest release? jumphosts/proxies should be fixed there

**Comment by ellafyi** [comment]
@localcc I am not the original poster, but I had the same issue and can confirm that it is still happening on 0.209.7. 
When attempting to connect to any ssh host, it asks for a password and then stays "Connecting" forever.

My hardware:
Ryzen 7735hs
16gb ddr5
Nvidia RTX 4060 laptop gpu
OS:
    Edition	        Windows 11 Pro
    Version	        25H2
    Installed on	‎10/‎7/‎2025
    OS build	        26200.6899
    Experience	        Windows Feature Experience Pack 1000.26100.253.0

**Comment by localcc** [comment]
is your ssh configuration for the host just a plain one or is there a jumphost in between?

**Comment by ellafyi** [comment]
Just a plain connection.

**Comment by rmatte** [comment]
> Could you verify if this happens on the latest release? jumphosts/proxies should be fixed there

I actually have some time right now so I'll give this a shot and report back.

**Comment by rmatte** [comment]
> Could you verify if this happens on the latest release? jumphosts/proxies should be fixed there

So I've been working with the new version of this for almost 2 hours now and so far it has been behaving perfectly. The initial connection is quick and always works, and the connections have been remaining stable. So whatever you changed in the latest version appears to have completely fixed the issues for me personally. I appreciate the quick resolution. Really loving this IDE, keep up the good work.

**Comment by franciskafyi** [comment]
Amazing to hear. We'll close this out then!
