### ISSUE TITLE
Debugger: (php) process exited before debugger attached

### ISSUE THREAD

**Issue by GuiEpi** [zed-industries/zed#40887]
### Summary
PHP Xdebug does not start with the error "process exited before debugger attached".

I'm aware of a [similar issue](https://github.com/zed-industries/zed/issues/36218) that was closed for Python, but that error was related to "pip not installed" whereas I'm experiencing this issue with PHP.

Just for your information, xdebug works well on vscode.

### Description
Steps to trigger the problem:
1. Create a debug.json with Xdebug configuration as shown in [the documentation](https://zed.dev/docs/languages/php#setting-up-xdebug)
```json
// Project-local debug tasks
//
// For more documentation on how to configure debug tasks,
// see: https://zed.dev/docs/debugger
[
  {
    "label": "PHP: Listen to Xdebug",
    "adapter": "Xdebug",
    "request": "launch",
    "initialize_args": {
      "port": 9003
    }
  }
]
```
2. Start debug session 

### Expected Behavior:

The debug session is successfully started.

### Actual Behavior:

The debug session is not started, and the following output appears in the console:
```
error: 
error: process exited before debugger attached.
```
Zed logs:
```
2025-10-22T14:08:40+02:00 INFO  [dap::transport] Debug adapter has connected to TCP server 127.0.0.1:33965
2025-10-22T14:08:40+02:00 ERROR [debugger_ui::debugger_panel] 
error: process exited before debugger attached.
```

### Zed Version and System Specs

Zed: 0.208.6
OS: Ubuntu 24.04.3 LTS
Memory: 64.0 GiB
Architecture: 64-bit
CPU: Intel® Core™ i5-10210U × 8
GPU: Intel® UHD Graphics (CML GT2)

**Comment by ConradIrwin** [comment]
Thanks for reporting.

Can you connect to that port via Xdebug from the command line?

If possible, can you see the difference between how VSCode configures this and how Zed does?

**Comment by GuiEpi** [comment]
> Can you connect to that port via Xdebug from the command line?

Yes, Xdebug works correctly when a listener is present.

### Test performed:

```bash
# Terminal 1
nc -l 9003

# Terminal 2  
php7.2 -dxdebug.mode=debug -dxdebug.start_with_request=yes -dxdebug.client_port=9003 test.php
```

**Result:** Xdebug successfully connects and sends the DBGp handshake:
```xml
<?xml version="1.0" encoding="iso-8859-1"?>
<init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" 
      ...
</init>
```

### Zed behavior:

1. Start debugger in Zed => Crashes immediately with `"process exited before debugger attached"`
2. `ss -tuln | grep 9003` => No listening socket (Zed never opens port 9003)

### VSCode comparison:

Identical configuration works perfectly in VSCode. It opens the socket on port 9003 and Xdebug connects successfully.

Here is my VSCode config:
```json
{
      "name": "Listen for Xdebug",
      "type": "php",
      "request": "launch",
      "port": 9003
},
```

**Comment by Anthony-Eid** [comment]
The Zed PHP docs seem to be out of date, we no longer support `initialize_args`. Could you please try the below configuration to make sure it works on your end before I close the issue?

```json
{
    "label": "PHP: Listen to Xdebug",
    "adapter": "Xdebug",
    "request": "launch",
    "port": 9003
  }
```

**Comment by Anthony-Eid** [comment]
Also, could you please add your DAP logs next time your debug session fails to attach? You can access them but clicking on one of the top right icons in the debug panel after the session fails.

**Comment by dahaupt** [comment]
I have the same issue using this configuration:
```json
{
    "label": "Listen to xdebug (PHP-Zed Config)",
    "adapter": "Xdebug",
    "request": "launch",
    "pathMappings": {
      "/var/www/html": "$ZED_WORKTREE_ROOT"
    }
}
```

The DAP log is empty showing _No adapter selected_ and I can't select any adapter.

**Comment by GuiEpi** [comment]
> The Zed PHP docs seem to be out of date, we no longer support `initialize_args`. Could you please try the below configuration to make sure it works on your end before I close the issue?
> 
> {
>     "label": "PHP: Listen to Xdebug",
>     "adapter": "Xdebug",
>     "request": "launch",
>     "port": 9003
>   }

I try with this one and same error.

> Also, could you please add your DAP logs next time your debug session fails to attach? You can access them but clicking on one of the top right icons in the debug panel after the session fails.

Like @dahaupt my DAP log is empty

**Comment by Anthony-Eid** [comment]
@GuiEpi Is there an open source PHP repo I could use to test this on? If not I could make my own repo

**Comment by GuiEpi** [comment]
> [@GuiEpi](https://github.com/GuiEpi) Is there an open source PHP repo I could use to test this on? If not I could make my own repo

I don't have one, sorry. Maybe @dahaupt does?

Alternatively, you could quickly scaffold a test project using API Platform:
1. Follow the setup: https://api-platform.com/docs/symfony/
2. Then see debugging tips: https://api-platform.com/docs/symfony/debugging/

**Comment by karatekaneen** [comment]
@Anthony-Eid I have the same issue with these settings (our repo have a bit of a strange structure)

```json
[
  {
    "adapter": "Xdebug",
    "label": "Listen for Xdebug",
    "request": "launch",
    "port": 9003,
    "pathMappings": {
      "/var/www/html/rw": "$ZED_WORKTREE_ROOT/src",
      "/var/www/composer": "$ZED_WORKTREE_ROOT",
       "/var/www/composer/src": "$ZED_WORKTREE_ROOT/src"
    },
    "log": true
  }
]

```

And like the others my DAP logs are empty as well. I am running this version:

```
Zed 0.211.4 
62ece18dfedd5fae028c8ab10f751652b7f814e6
```

**Comment by Anthony-Eid** [comment]
@GuiEpi @karatekaneen Are either of you free to get on a call with me next week? I'm having trouble reproducing this and it would be helpful for me if I could debug the issue with you guys

**Comment by tauitse** [comment]
@Anthony-Eid  I have the same issue and a am available for a call next week. I am in the CET timezone.

**Comment by GuiEpi** [comment]
> [@GuiEpi](https://github.com/GuiEpi) [@karatekaneen](https://github.com/karatekaneen) Are either of you free to get on a call with me next week? I'm having trouble reproducing this and it would be helpful for me if I could debug the issue with you guys

Yes, no problem. I am also in the CET time zone.

**Comment by GuiEpi** [comment]
Hello everyone, the debugger is working again on my end. How about yours? (I haven't changed anything)

Zed 0.211.6

**Comment by dahaupt** [comment]
@GuiEpi I can confirm that. Working again without changing my config. 🥳

**Comment by eduardotiny** [comment]
I'm no longer experiencing the `process exited before debugger attached` problem, but now I'm getting timeouts. VSCode still works.

Zed 0.212.6 

<img width="1895" height="1181" alt="Image" src="https://github.com/user-attachments/assets/48ca7589-5afa-4a61-aecc-62cc4618b273" />

**Comment by GuiEpi** [comment]
> I'm no longer experiencing the `process exited before debugger attached` problem, but now I'm getting timeouts. VSCode still works.
> 
> Zed 0.212.6
> <img alt="Image" width="1895" height="1181" src="https://private-user-images.githubusercontent.com/83721225/515470650-48ca7589-5afa-4a61-aecc-62cc4618b273.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM0NTg0MDgsIm5iZiI6MTc2MzQ1ODEwOCwicGF0aCI6Ii84MzcyMTIyNS81MTU0NzA2NTAtNDhjYTc1ODktNWFmYS00YTYxLWFlY2MtNjJjYzQ2MThiMjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE4VDA5MjgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMThmYzFlN2I4N2YzNGMzZjcxYTgyMTQ1OGQxMmJhOTJhMmQyNjA0NzU1ZjhjYmUyZTE3ZjljMTRlYWU3MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7TKxbUEzF_Ip-Cv1QB6UF-zqHJen-OGQWRMPM_EjR0M">

Have you tried with the minimal configuration?
```json
[
  {
    "label": "PHP: Listen to Xdebug",
    "adapter": "Xdebug",
    "request": "launch",
    "port": 9003
  }
]
```

**Comment by eduardotiny** [comment]
> > I'm no longer experiencing the `process exited before debugger attached` problem, but now I'm getting timeouts. VSCode still works.
> > Zed 0.212.6
> > <img alt="Image" width="1895" height="1181" src="https://private-user-images.githubusercontent.com/83721225/515470650-48ca7589-5afa-4a61-aecc-62cc4618b273.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM0NTg0MDgsIm5iZiI6MTc2MzQ1ODEwOCwicGF0aCI6Ii84MzcyMTIyNS81MTU0NzA2NTAtNDhjYTc1ODktNWFmYS00YTYxLWFlY2MtNjJjYzQ2MThiMjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE4VDA5MjgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMThmYzFlN2I4N2YzNGMzZjcxYTgyMTQ1OGQxMmJhOTJhMmQyNjA0NzU1ZjhjYmUyZTE3ZjljMTRlYWU3MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7TKxbUEzF_Ip-Cv1QB6UF-zqHJen-OGQWRMPM_EjR0M">
> 
> Have you tried with the minimal configuration?
> 
> [
>   {
>     "label": "PHP: Listen to Xdebug",
>     "adapter": "Xdebug",
>     "request": "launch",
>     "port": 9003
>   }
> ]

Yes, same problem.

**Comment by GuiEpi** [comment]
In my opinion, this error deserves a new issue.

There is also one point that raises my concern in your `debug.json`. The name is "PHP: Listen to Xdebug" but in your debug window, I see: "Debug ERP". Perhaps you are not pointing to the correct configuration file.

**Comment by audirs4** [comment]
@GuiEpi  I am on 0.214.7 and am seeing this error with the basic debug config in the guide. Has there been a regression and are you seeing this same error again?

**Comment by GuiEpi** [comment]
> [@GuiEpi](https://github.com/GuiEpi) I am on 0.214.7 and am seeing this error with the basic debug config in the guide. Has there been a regression and are you seeing this same error again?

Still working fine for me. I'm also on version 0.214.7

**Comment by audirs4** [comment]
@GuiEpi While I am running a derivative of Ubuntu 24.04, maybe there is something in there that causing this issue still for me. Maybe I haven't got the fix that you received and solved your initial issue?

I will install a fresh copy of Ubuntu 24.04 and see if that solves the issue.

Other than the settings.xml file, is there any files left behind between Zed installations? Like when switching from the Flatpak version to native installed via the standard script?

**Comment by audirs4** [comment]
@GuiEpi I setup Ubuntu 24.04 and still I am running into the same issue. Am I doing something wrong? Do I have something setup wrong? In my local environment I and using DDEV and have Xdebug enabled. It works when I tested it with PHPStorm so I know DDEV and Xdebug are working. But Zed fails to sit and listen on port 9003 for Xdebug to connect.

Any thoughts on what might be wrong with the setup?

**Comment by alexei-s-allsports** [comment]
I’m running into the exact same problem. I use WSL2 and DDEV, Xdebug works perfectly in VS Code, but Zed fails with this error:
error: Connection to TCP DAP timeout 127.0.0.1:9003

**Comment by GuiEpi** [comment]
> I’m running into the exact same problem. I use WSL2 and DDEV, Xdebug works perfectly in VS Code, but Zed fails with this error: error: Connection to TCP DAP timeout 127.0.0.1:9003

Hello, for me it's not the same problem and it deserves a new issue. Like I said here: https://github.com/zed-industries/zed/issues/40887#issuecomment-3547625194

**Comment by GuiEpi** [comment]
@audirs4 I don't think the issue is related to Ubuntu itself. Since Xdebug is working fine with PHPStorm on your system, it should work with Zed as well. The problem is likely with Zed's configuration or how it's trying to listen on port 9003. Would it be possible for you to share a screenshot or a short video?

**Comment by GuiEpi** [comment]
@Anthony-Eid, @ConradIrwin  I believe issue #41476 should be reopened and this one can be closed. The `Connection to TCP DAP timeout` error that some users are experiencing appears to be a different problem from my original issue.

**Comment by msarotti** [comment]
Hi all,
don't know if this could help but I was experiencing the same issue under WSL2 with xDebug (Connection to TCP DAP timeout 127.0.0.1:9003)

I've added this line to the .wslconfig file under %USERPROFILE%
```
[wsl2]
kernelCommandLine=ipv6.disable=1

```

and after a restart of the wsl the Zed debugger seems to be working now.

**Comment by eduardotiny** [comment]
> Hi all, don't know if this could help but I was experiencing the same issue under WSL2 with xDebug (Connection to TCP DAP timeout 127.0.0.1:9003)
> 
> I've added this line to the .wslconfig file under %USERPROFILE%
> 
> ```
> [wsl2]
> kernelCommandLine=ipv6.disable=1
> ```
> 
> and after a restart of the wsl the Zed debugger seems to be working now.

That solved the problem, thank you!

**Comment by Anthony-Eid** [comment]
@GuiEpi Are you on wsl?

**Comment by GuiEpi** [comment]
> [@GuiEpi](https://github.com/GuiEpi) Are you on wsl?

I don't understand the question. The issue `process exited before debugger attached` has been resolved (see: https://github.com/zed-industries/zed/issues/40887#issuecomment-3542417213).

Have you read my previous answers?

**Comment by audirs4** [comment]
@Anthony-Eid Seems I am the only one still experiencing the original error posted, while for @GuiEpi it just started working the one day. He was running on Ubuntu 24.04.3 LTS where I am running Pop!_OS 24.04 which is based on Ubuntu 24.04.

@GuiEpi How are you running Zed? Is it a Snap, Flatpak or installed via the script installer?

### debug.json
```
[
  {
    "label": "PHP: Listen to Xdebug",
    "adapter": "Xdebug",
    "request": "launch",
    "pathMappings": {
      "/var/www/html": "$ZED_WORKTREE_ROOT"
    },
    "port": 9003
  }
]
``` 

When I go to **Run -> Start Debugger** then click on "PHP: Listen to Xdebug".

<img width="547" height="229" alt="Image" src="https://github.com/user-attachments/assets/1861ccdb-5b99-4e8f-a28e-c1949d31d98c" />

I then receive the error shared by the original author.

<img width="914" height="181" alt="Image" src="https://github.com/user-attachments/assets/f2193c89-11cc-4090-a551-d0f217099883" />

Zed is not running the debugger. The port 9003 is open and available as I can run netcat to listen on the port, or run s`s -tuln | grep 9003` and it gives no results.

**Comment by GuiEpi** [comment]
> [@GuiEpi](https://github.com/GuiEpi) How are you running Zed? Is it a Snap, Flatpak or installed via the script installer?

I installed it using the script as recommended in [the documentation](https://zed.dev/docs/linux#standard-installation).

---

You have exactly the same problem I had at the beginning. Unfortunately, my issue was resolved "magically" without any clear explanation being provided in this thread. Without knowing what actually fixed it, I'm afraid I can't help you further.

**Comment by audirs4** [comment]
Strangely enough that error has gone away for me too, but I still can't get Zed to receive the connection with Xdebug from DDEV.

<img width="769" height="372" alt="Image" src="https://github.com/user-attachments/assets/f9c29dfc-efc7-485d-b8a3-2f938f04d80a" />

I can see that Zed does have the debugger listening on port 9003.

    $ ss -tuln | grep 9003
    tcp   LISTEN 0      511         127.0.0.1:9003       0.0.0.0:*

    $ lsof -i :9003 -sTCP:LISTEN
    COMMAND     PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
    MainThrea 58319 user   24u  IPv4 247070      0t0  TCP localhost:9003 (LISTEN)

I opened the 9003 port in ufw, and executing `telnet host.docker.internal 9003` from the ddev container does connect successfully to the Zed debugger. I just don't know why loading pages doesn't work between the two. It works with PHP Storm with its auto-detect feature, but I don't have a license and don't want to use that huge IDE anymore and want to get Zed working.

We still don't know why the original issue went away, but I still can't get Zed connected, though the issue I face now seems different, so this issue seems like it could be closed, if there is no way to determine what the source of the issue is.

**Comment by GuiEpi** [comment]
@audirs4 I may have found the issue. The [DDEV documentation for VS Code](https://docs.ddev.com/en/stable/users/debugging-profiling/step-debugging/#visual-studio-code-vs-code-debugging-setup) mentions an important step that's not in the PhpStorm instructions.

**Step 3** shows how to run `ddev xdebug on` before starting the debugger (PhpStorm likely handles this automatically). Even though Zed is listening on port 9003, Xdebug won't connect from the container unless it's explicitly enabled first.

Try running `ddev xdebug on` manually before starting the debugger to see if this resolves the issue. Zed has a [tasks system](https://zed.dev/docs/tasks) that might help automate this, though I'm not sure if it works the same way as VS Code's.

**Comment by audirs4** [comment]
@GuiEpi Thanks for the idea. Unfortunately, that did not fix it, and I am sure I had tried that order of events as well. You had a great idea to look further into VS Code. So I installed VSCodium, the version actual built from the open source code, unlike the VS Code binaries, which have extra telemetry from MS. After installing and performing the steps to a tee, it worked to pick up the debugging from DDEV's Xdebug. I cut out the tasks piece, and still it worked. Those tasks just setup automation to enable Xdebug, versus doing it manually.

Since it worked in VSCodium (VS Code), I know my DDEV Xdebug setup is good, and just a matter of a configuration in Zed. Looking over the configurations for VS Code, there are 2 it had that the PHP guide for the debugger did not have. Those are `hostname` and `pathMappings`. I had tried both of these before in Zed with no luck, but clearly had the wrong values. Using the value from the VS Code config for `hostname` and similar for `pathMappings` but changing the variable accordingly to `$ZED_WORKTREE_ROOT` for Zed, I successfully got the Zed debugger working.

My debug.json
```json
[
  {
    "label": "PHP: Listen to Xdebug",
    "adapter": "Xdebug",
    "request": "launch",
    "hostname": "0.0.0.0",
    "pathMappings": {
      "/var/www/html": "$ZED_WORKTREE_ROOT",
    },
    "port": 9003,
  },
]
``` 

I had previously tried using VSCodium, but it didn't get it working at that time, but I also didn't give it too much effort. This time, following the instructions I realize what I did wrong, as the instructions are not a perfect match as to what steps to perform and I was not super fluent with the the tool to know what to properly do.

Thanks so much for you help in getting this working. I can finally use Zed for debugging and am excited to use Zed as my default to get some work done.

**Comment by neutralord** [comment]
I just encountered an issue with the same symptoms (`process exited before debugger attached`). The reason was a broken package in the `node_modules` directory at `~/.local/share/zed/extensions/work/php/Xdebug/Xdebug_v1.40.1/extension`. So, if anyone encounters this issue again, try executing the extension file from the command line like `node ./out/phpDebug.js` and check for any errors.

**Comment by tuube** [comment]
I encountered this issue as well and the fix for me was to reinstall the php extension itself. After that the debugger started to work.
