### ISSUE TITLE
Windows: can't open WSL distro, `command 'uname' failed`

### ISSUE THREAD

**Issue by ion-elgreco** [zed-industries/zed#40892]
### Summary

Opening a WSL distro in Windows fails. `uname command failed`

### Description
When I open a WSL distro, it errors out and I see this in the logs:

`[recent_projects::remote_connections] Failed to open project: Command 'uname' failed: `

When I open WSL and run `uname` manually I see the output `Linux`

**Expected Behavior**:
Open WSL distro

**Actual Behavior**:
Fails on uname command

### Zed Version and System Specs

Zed: v0.208.6 (Zed)
Os: Windows 10.0.20348
Memory: 64GiB
Architecture: x86_64
GPU: Microsoft basic render driver

**Comment by mag1c1an1** [comment]
I also encountered this problem last week. My distribution is nixos-wsl and I have solved it by nix-ld.

**Comment by franciskafyi** [comment]
Thank you for the tip @mag1c1an1. Could you try that @ion-elgreco? 🙏

**Comment by ion-elgreco** [comment]
> Thank you for the tip @mag1c1an1. Could you try that @ion-elgreco? 🙏 

I'm using Ubuntu as WSL base image and not nixos

**Comment by franciskafyi** [comment]
Ah okay. I'll ask the team to take a closer look!

**Comment by Veykril** [comment]
What shell do you have configured as the default on your wsl distro? This should be fixed in the latest release

**Comment by localcc** [comment]
this was fixed in v0.209 please update your zed installation

**Comment by ion-elgreco** [comment]
Ok thanks, I will move over the newer version to our systems

**Comment by Serhii-the-Dev** [comment]
I still have this issue on the next version/env:

Zed: v0.210.4 (Zed) 
OS: Windows 10.0.18363
Memory: 31.8 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 630 || Intel Corporation || 27.20.100.8984

Here is a recording showing how it's reproducing:

https://github.com/user-attachments/assets/4f0aaec8-d370-4c62-9dfc-e3382b1d73f4

**Comment by Veykril** [comment]
Will be fixed by https://github.com/zed-industries/zed/pull/41547

**Comment by ion-elgreco** [comment]
@Veykril @localcc  can you please reopen the issue, I tried the preview version that includes the fix but it still gives that error message command `uname` failed.

My wsl image uses ubuntu:24.04

**Comment by Veykril** [comment]
Can you post the full error log? Also whatshell is set as the default on your ubuntu

**Comment by ion-elgreco** [comment]
@Veykril the default shell is `/bin/bash` and the error trace that I see in the logs is only:  `Command 'uname' failed: `

and nothing else

**Comment by Veykril** [comment]
I cannot reproduce this on either current preview 
```
Zed Preview 0.212.3 
f7dac91680bded8bd480ae98c97a0c5245805183
```
or latest nightly

`/bin/bash`, `/bin/sh` and `fish` all work just fine for me

**Comment by Veykril** [comment]
I'll add some more context to the logs here

**Comment by ion-elgreco** [comment]
@Veykril I will move the preview version over to my airgapped environment once that has landed.

**Comment by ion-elgreco** [comment]
@Veykril logs with latest release:

```
[remote::transport::wsl] Connecting to WSL distro mywsl with user None
[crates/remote/src/transport/wsl.rs:115] failed detected exec status

Caused by:
     Command '"wsl.exe" "--distribution" "mywsl" "--cd" "~" "uname" "-m"' failed:
[workspace::notifications] failed detected platform
```

If I open cmd, I can run `wsl --distribution mywsl uname -m` without a problemm but adding `--cd ~` in between it doesnt work and gives `the system cannot find the file specified`.

Is this requiring a specific version of WSL?

**Comment by Veykril** [comment]
Whats your shell on windows, and whats your default shell in your distro?

Running `wsl.exe --distribution ubuntu --cd ~ uname -m` works just fine for me in my terminal.

Also what is your distro and does it work if you use a different path than `~`?

**Comment by ion-elgreco** [comment]
@Veykril in windows it's `cmd` in the distro its `/bin/bash`

The distro is Ubuntu-24.04.

If I do `.` instead of `~`, so `wsl.exe --distribution ubuntu --cd . uname -m` it works and returns `x86_64`

**Comment by Veykril** [comment]
Okay I tihnk the issue is quoting related, `'~'` fails in cmd

**Comment by ion-elgreco** [comment]
@Veykril let me know if there is a fix I need to try :)

**Comment by Veykril** [comment]
Assuming you don't have powershell hidden on your system the next release should make things work again for you. Apparently we regressed and started trying to run things with cmd by accident, and our quoting logic for cmd is somewhat broken. So today's release in a couple hours might fix things for you here again

**Comment by ion-elgreco** [comment]
@Veykril Okay, I'll keep an eye on the release!

**Comment by Veykril** [comment]
Thanks, and sorry for the back and forth. Turns out this runs into a bunch of different issues at once here 😅

**Comment by ion-elgreco** [comment]
@Veykril ha no worries, just give me a ping if theres testable release :)

**Comment by Veykril** [comment]
We released again yesterday

**Comment by ion-elgreco** [comment]
@Veykril I tried the stable and preview but both still fail with: `failed detecting platform: Command '"wsl.exe" "--distribution" "wsl" "--cd" "~" "uname" "-m"' failed: . Please try again.`

**Comment by Veykril** [comment]
Can you show the logs?

**Comment by ion-elgreco** [comment]
> Can you show the logs?

Sorry I'm not behind that PC for a week, I'll check once I am back. But it was likely the same error as before, because I don't see a difference in the code line that was called in cmd

**Comment by Veykril** [comment]
No rush. The weird thing is we shouldn't be using cmd here anymore now, we should fallback to powershell again (unless you hid powershell from your path)

**Comment by ion-elgreco** [comment]
@Veykril It could be hidden, I hvae to check, the environment is not configured by me so will have to verify

**Comment by Veykril** [comment]
Gotcha, if it is, then this will have to wait on us fixing our shell quoting for cmd

**Comment by ion-elgreco** [comment]
@Veykril I checked but the Powershell shell isn't hidden from the path

**Comment by changchinlan** [comment]
Adding an extra edge case here.
I'm using **NixOS on WSL + Nushell** and encountered "The `uname` command doesn't have flag `-m`" error. Log:

```
2025-12-09T09:17:41+08:00 INFO  [remote::transport::wsl] Remote can exec: false
2025-12-09T09:17:42+08:00 ERROR [workspace::notifications] failed detecting platform: Command '"wsl.exe" "--distribution" "NixOS" "--cd" "~" "uname" "-m"' failed: Error: nu::parser::unknown_flag

  x The `uname` command doesn't have flag `-m`.
   ,-[source:1:8]
 1 | uname -m
   :        |
   :        `-- unknown flag
   `----
  help: Use `--help` to see available flags
```

The detected shell is the nixos-wsl wrapper (.../wrapped-nu/wrapper), which ultimately launches Nushell.
Since Nushell parses `uname` as a builtin keyword (which returns a structured table and does not accept -m), it crashes.

```
> getent passwd $env.USER 
user:x:1000:100:User:/home/kyaru:/nix/store/0yqkmw410csp9674n6i09km203v8va29-wrapped-nu/wrapper
```

I don't know why manually running `wsl --distribution NixOS sh -c 'echo $SHELL' ` gives the correct result, but Zed detects the wrapper.
The wrapper does set `$SHELL` variable:
https://github.com/nix-community/NixOS-WSL/blob/a16b061ec61831755df35fae916d19b0ac5a43cc/utils/src/shell_wrapper.rs#L45-L48

Possible solution:

* Use the fix suggested in #25613 (wrapping the uname command in sh -c "..."). This should be the universal fix regardless of the underlying shell.
* Detect if path of $SHELL contains something like `nu` or `powershell`?

**Comment by Veykril** [comment]
Zed gets confused here, it sees the shalle name `wrapper` which doesn't match any known ones, so it defaults back to thinking its a bash, not nu and thus things break.

**Comment by ion-elgreco** [comment]
It still fails:

```
failed detecting platform: Command '"wsl.exe" "--distribution" "distro" "--cd" "~" "--exec" "uname" "-sm"' failed: : Command '"wsl.exe" "--distribution" "distro" "--cd" "~" "uname" "-sm"' failed: . Please try again.
```

**Comment by ion-elgreco** [comment]
still relevant

**Comment by ion-elgreco** [comment]
@Veykril Just curious, was this ever fixed in later releases?
