### ISSUE TITLE
Windows：zed crashed when add python virtual environment

### ISSUE THREAD

**Issue by dDostalker** [zed-industries/zed#41249]
### Summary

zed crashed when I add python virtual environment ,. I entered "C:", and it would crash when I deleted it.

### Description

Steps to trigger the problem:
1. Open Zed
2. Click select Virtual Environments
3. Click Add Virtual Environments
4. Inputs "C:" (must "C:")
5. delete words "C:"

Actual Behavior:
crashed
Expected Behavior:
delete "C:"

Video
https://github.com/user-attachments/assets/e8b2f90e-4c9c-446a-9daa-ed3378457d87

### Zed Version and System Specs

Zed: v0.209.6 (Zed) 
OS: Windows 10.0.22621
Memory: 27.7 GiB
Architecture: x86_64
GPU: AMD Radeon(TM) Graphics || AMD Corporation || 24.10.1 (24.20.19.01-241011a-409016C-AMD-Software-Adrenalin-Edition)

### If applicable, attach your `Zed.log` file to this issue.

<details><summary>Zed.log</summary>

```log
2025-10-27T09:39:02+08:00 INFO  [project::lsp_store] language server 1: unregistered workspace/DidChangeWatchedFiles capability with id b97b29d6-5f62-4a61-9773-890730e9502a
2025-10-27T09:39:02+08:00 INFO  [project::lsp_store] language server 1: unregistered workspace/DidChangeWatchedFiles capability with id 44fcf4fd-dfa3-49ed-ac66-96896f447659
2025-10-27T09:40:41+08:00 INFO  [gpui::platform::windows::directx_renderer] Updating monochrome_sprite_pipeline buffer size from 512 to 2048
2025-10-27T09:40:41+08:00 INFO  [project::lsp_store] language server 1: unregistered workspace/DidChangeWatchedFiles capability with id 36e6b6ad-3655-4494-a672-383492160b9c
2025-10-27T09:40:41+08:00 INFO  [project::lsp_store] language server 1: unregistered workspace/DidChangeWatchedFiles capability with id 7d56ef6f-6d89-451d-a1d6-5d696aea8522
2025-10-27T09:41:56+08:00 WARN  [pet_windows_registry::environments] Failed to open HKLM\Software\Python\PythonCore\3.9\InstallPath, Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" }
2025-10-27T09:42:01+08:00 ERROR [crashes] triggering a crash to generate a minidump...
```
What is rather strange is that only when I input "C: " and delete" will the zed crash.
</details>

**Comment by dDostalker** [comment]
In order to better solve this problem, I compiled and saved the information at the moment of the crash on my computer. I hope it will be helpful. If I have time, I will try to fix it.
```
thread 'main' panicked at D:\GitHubPull\zed\crates\ui\src\components\label\highlighted_label.rs:20:13:
highlight index 9 is not a valid UTF-8 boundary
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library\std\src\panicking.rs:697
   1: core::panicking::panic_fmt
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588/library\core\src\panicking.rs:75
   2: ui::components::label::highlighted_label::HighlightedLabel::new<alloc::string::String>
             at .\crates\ui\src\components\label\highlighted_label.rs:20
   3: file_finder::open_path_prompt::impl$2::render_match
             at .\crates\file_finder\src\open_path_prompt.rs:733
   4: picker::Picker<file_finder::open_path_prompt::OpenPathDelegate>::render_element<file_finder::open_path_prompt::OpenPathDelegate>
             at .\crates\picker\src\picker.rs:732
   5: picker::impl$1::render_element_container::closure$0::closure$0<file_finder::open_path_prompt::OpenPathDelegate>
             at .\crates\picker\src\picker.rs:762
   6: core::iter::adapters::map::map_fold::closure$0<usize,gpui::elements::div::Stateful<gpui::elements::div::Div>,tuple$<>,picker::impl$1::render_element_container::closure$0::closure_env$0<file_finder::open_path_prompt::OpenPathDelegate>,core::iter::traits::it
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588\library\core\src\iter\adapters\map.rs:88
   7: core::iter::traits::iterator::Iterator::fold<core::ops::range::Range<usize>,tuple$<>,core::iter::adapters::map::map_fold::closure_env$0<usize,gpui::elements::div::Stateful<gpui::elements::div::Div>,tuple$<>,picker::impl$1::render_element_container::closure
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588\library\core\src\iter\traits\iterator.rs:2602
   8: core::iter::adapters::map::impl$2::fold<gpui::elements::div::Stateful<gpui::elements::div::Div>,core::ops::range::Range<usize>,picker::impl$1::render_element_container::closure$0::closure_env$0<file_finder::open_path_prompt::OpenPathDelegate>,tuple$<>,core
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588\library\core\src\iter\adapters\map.rs:128
   9: core::iter::traits::iterator::Iterator::for_each<core::iter::adapters::map::Map<core::ops::range::Range<usize>,picker::impl$1::render_element_container::closure$0::closure_env$0<file_finder::open_path_prompt::OpenPathDelegate> >,alloc::vec::impl$20::extend
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588\library\core\src\iter\traits\iterator.rs:827
  10: alloc::vec::Vec<gpui::elements::div::Stateful<gpui::elements::div::Div>,alloc::alloc::Global>::extend_trusted<gpui::elements::div::Stateful<gpui::elements::div::Div>,alloc::alloc::Global,core::iter::adapters::map::Map<core::ops::range::Range<usize>,picker:
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588\library\alloc\src\vec\mod.rs:3774
  11: alloc::vec::spec_extend::impl$1::spec_extend<gpui::elements::div::Stateful<gpui::elements::div::Div>,core::iter::adapters::map::Map<core::ops::range::Range<usize>,picker::impl$1::render_element_container::closure$0::closure_env$0<file_finder::open_path_pro
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588\library\alloc\src\vec\spec_extend.rs:29
  12: alloc::vec::spec_from_iter_nested::impl$1::from_iter<gpui::elements::div::Stateful<gpui::elements::div::Div>,core::iter::adapters::map::Map<core::ops::range::Range<usize>,picker::impl$1::render_element_container::closure$0::closure_env$0<file_finder::open_
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588\library\alloc\src\vec\spec_from_iter_nested.rs:62
  13: alloc::vec::spec_from_iter::impl$0::from_iter<gpui::elements::div::Stateful<gpui::elements::div::Div>,core::iter::adapters::map::Map<core::ops::range::Range<usize>,picker::impl$1::render_element_container::closure$0::closure_env$0<file_finder::open_path_pr
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588\library\alloc\src\vec\spec_from_iter.rs:34
  14: alloc::vec::impl$15::from_iter<gpui::elements::div::Stateful<gpui::elements::div::Div>,core::iter::adapters::map::Map<core::ops::range::Range<usize>,picker::impl$1::render_element_container::closure$0::closure_env$0<file_finder::open_path_prompt::OpenPathD
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588\library\alloc\src\vec\mod.rs:3633
  15: core::iter::traits::iterator::Iterator::collect<core::iter::adapters::map::Map<core::ops::range::Range<usize>,picker::impl$1::render_element_container::closure$0::closure_env$0<file_finder::open_path_prompt::OpenPathDelegate> >,alloc::vec::Vec<gpui::elemen
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588\library\core\src\iter\traits\iterator.rs:2027
  16: picker::impl$1::render_element_container::closure$0<file_finder::open_path_prompt::OpenPathDelegate>
             at .\crates\picker\src\picker.rs:763
  17: gpui::app::context::impl$2::processor::closure$0::closure$0<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate>,core::ops::range::Range<usize>,alloc::vec::Vec<gpui::elements::div::Stateful<gpui::elements::div::Div>,alloc::alloc::Global>,picker:
             at .\crates\gpui\src\app\context.rs:270
  18: gpui::app::impl$8::update_entity::closure$0<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate>,alloc::vec::Vec<gpui::elements::div::Stateful<gpui::elements::div::Div>,alloc::alloc::Global>,gpui::app::context::impl$2::processor::closure$0::clos
             at .\crates\gpui\src\app.rs:2155
  19: gpui::app::App::update<alloc::vec::Vec<gpui::elements::div::Stateful<gpui::elements::div::Div>,alloc::alloc::Global>,gpui::app::impl$8::update_entity::closure_env$0<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate>,alloc::vec::Vec<gpui::eleme
             at .\crates\gpui\src\app.rs:761
  20: gpui::app::impl$8::update_entity<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate>,alloc::vec::Vec<gpui::elements::div::Stateful<gpui::elements::div::Div>,alloc::alloc::Global>,gpui::app::context::impl$2::processor::closure$0::closure_env$0<p
             at .\crates\gpui\src\app.rs:2153
  21: gpui::app::entity_map::Entity<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate> >::update<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate>,alloc::vec::Vec<gpui::elements::div::Stateful<gpui::elements::div::Div>,alloc::alloc::Gl
             at .\crates\gpui\src\app\entity_map.rs:435
  22: gpui::app::context::impl$2::processor::closure$0<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate>,core::ops::range::Range<usize>,alloc::vec::Vec<gpui::elements::div::Stateful<gpui::elements::div::Div>,alloc::alloc::Global>,picker::impl$1::re
             at .\crates\gpui\src\app\context.rs:270
  23: gpui::elements::uniform_list::uniform_list::closure$0<gpui::elements::div::Stateful<gpui::elements::div::Div>,ref$<str$>,gpui::app::context::impl$2::processor::closure_env$0<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate>,core::ops::range::
             at .\crates\gpui\src\elements\uniform_list.rs:35
  24: alloc::boxed::impl$30::call<tuple$<core::ops::range::Range<usize>,ref_mut$<gpui::window::Window>,ref_mut$<gpui::app::App> >,dyn$<core::ops::function::Fn<tuple$<core::ops::range::Range<usize>,ref_mut$<gpui::window::Window>,ref_mut$<gpui::app::App> >,assoc$<
             at /rustc/1159e78c4747b02ef996e55082b704c09b970588\library\alloc\src\boxed.rs:1985
  25: gpui::elements::uniform_list::impl$2::prepaint::closure$1
             at .\crates\gpui\src\elements\uniform_list.rs:468
  26: gpui::elements::div::impl$8::prepaint::closure$1::closure$1::closure$0<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::uniform_list::impl$2::prepaint::closure_env$1>
             at .\crates\gpui\src\elements\div.rs:1697
  27: gpui::window::Window::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$8::prepaint::closure$1::closure$1::closure_env$0<enum
             at .\crates\gpui\src\window.rs:2413
  28: gpui::elements::div::impl$8::prepaint::closure$1::closure$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::uniform_list::impl$2::prepaint::closure_env$1>
             at .\crates\gpui\src\elements\div.rs:1686
  29: gpui::window::Window::with_text_style<gpui::elements::div::impl$8::prepaint::closure$1::closure_env$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::uniform_list::impl$2::prepaint::closure_env$1>,tuple$<enum2$<core::option::Option<gpui
             at .\crates\gpui\src\window.rs:2365
  30: gpui::elements::div::impl$8::prepaint::closure$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::uniform_list::impl$2::prepaint::closure_env$1>
             at .\crates\gpui\src\elements\div.rs:1685
  31: gpui::window::impl$24::with_optional_element_state::closure$0<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$8::prepaint::closure_env$1<enum2$<core::option::Option<gpui::window::Hi
             at .\crates\gpui\src\window.rs:2741
  32: gpui::window::Window::with_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::window::impl$24::with_optional_element_state::closure_env$0<gpui::elements::div::InteractiveElementState,enum2$<
             at .\crates\gpui\src\window.rs:2698
  33: gpui::window::Window::with_optional_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$8::prepaint::closure_env$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui
             at .\crates\gpui\src\window.rs:2740
  34: gpui::elements::div::Interactivity::prepaint<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::uniform_list::impl$2::prepaint::closure_env$1>
             at .\crates\gpui\src\elements\div.rs:1663
  35: gpui::elements::uniform_list::impl$2::prepaint
             at .\crates\gpui\src\elements\uniform_list.rs:360
  36: gpui::element::Drawable<gpui::elements::uniform_list::UniformList>::prepaint<gpui::elements::uniform_list::UniformList>
             at .\crates\gpui\src\element.rs:420
  37: gpui::element::impl$7::prepaint<gpui::elements::uniform_list::UniformList>
             at .\crates\gpui\src\element.rs:556
  38: gpui::element::AnyElement::prepaint
             at .\crates\gpui\src\element.rs:604
  39: gpui::element::impl$9::prepaint
             at .\crates\gpui\src\element.rs:685
  40: gpui::element::Drawable<gpui::element::AnyElement>::prepaint<gpui::element::AnyElement>
             at .\crates\gpui\src\element.rs:420
  41: gpui::element::impl$7::prepaint<gpui::element::AnyElement>
             at .\crates\gpui\src\element.rs:556
  42: gpui::element::AnyElement::prepaint
             at .\crates\gpui\src\element.rs:604
  43: gpui::elements::div::impl$6::prepaint::closure$0::closure$0::closure$0
             at .\crates\gpui\src\elements\div.rs:1427
  44: gpui::window::Window::with_element_offset<tuple$<>,gpui::elements::div::impl$6::prepaint::closure$0::closure$0::closure_env$0>
             at .\crates\gpui\src\window.rs:2431
  45: gpui::elements::div::impl$6::prepaint::closure$0::closure$0
             at .\crates\gpui\src\elements\div.rs:1425
  46: gpui::elements::div::impl$8::prepaint::closure$1::closure$1::closure$0<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure$0::closure_env$0>
             at .\crates\gpui\src\elements\div.rs:1697
  47: gpui::window::Window::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$8::prepaint::closure$1::closure$1::closure_env$0<enum
             at .\crates\gpui\src\window.rs:2413
  48: gpui::elements::div::impl$8::prepaint::closure$1::closure$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure$0::closure_env$0>
             at .\crates\gpui\src\elements\div.rs:1686
  49: gpui::window::Window::with_text_style<gpui::elements::div::impl$8::prepaint::closure$1::closure_env$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure$0::closure_env$0>,tuple$<enum2$<core::option::Option<gp
             at .\crates\gpui\src\window.rs:2365
  50: gpui::elements::div::impl$8::prepaint::closure$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure$0::closure_env$0>
             at .\crates\gpui\src\elements\div.rs:1685
  51: gpui::window::impl$24::with_optional_element_state::closure$0<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$8::prepaint::closure_env$1<enum2$<core::option::Option<gpui::window::Hi
             at .\crates\gpui\src\window.rs:2741
  52: gpui::window::Window::with_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::window::impl$24::with_optional_element_state::closure_env$0<gpui::elements::div::InteractiveElementState,enum2$<
             at .\crates\gpui\src\window.rs:2698
  53: gpui::window::Window::with_optional_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$8::prepaint::closure_env$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui
             at .\crates\gpui\src\window.rs:2740
  54: gpui::elements::div::Interactivity::prepaint<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure$0::closure_env$0>
             at .\crates\gpui\src\elements\div.rs:1663
  55: gpui::elements::div::impl$6::prepaint::closure$0
             at .\crates\gpui\src\elements\div.rs:1412
  56: stacksafe::internal::with_protected::closure$0<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure_env$0>
             at C:\Users\Admin\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-e791a3f93f26854f\stacksafe-0.1.4\src\internal.rs:29
  57: stacker::maybe_grow
             at C:\Users\Admin\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-e791a3f93f26854f\stacker-0.1.22\src\lib.rs:57
  58: gpui::elements::div::impl$6::prepaint
             at .\crates\gpui\src\elements\div.rs:1361
  59: gpui::elements::div::impl$15::prepaint<gpui::elements::div::Div>
             at .\crates\gpui\src\elements\div.rs:2987
  60: gpui::element::Drawable<gpui::elements::div::Stateful<gpui::elements::div::Div> >::prepaint<gpui::elements::div::Stateful<gpui::elements::div::Div> >
             at .\crates\gpui\src\element.rs:420
  61: gpui::element::impl$7::prepaint<gpui::elements::div::Stateful<gpui::elements::div::Div> >
             at .\crates\gpui\src\element.rs:556
  62: gpui::element::AnyElement::prepaint
             at .\crates\gpui\src\element.rs:604
  63: gpui::elements::div::impl$6::prepaint::closure$0::closure$0::closure$0
             at .\crates\gpui\src\elements\div.rs:1427
  64: gpui::window::Window::with_element_offset<tuple$<>,gpui::elements::div::impl$6::prepaint::closure$0::closure$0::closure_env$0>
             at .\crates\gpui\src\window.rs:2431
  65: gpui::elements::div::impl$6::prepaint::closure$0::closure$0
             at .\crates\gpui\src\elements\div.rs:1425
  66: gpui::elements::div::impl$8::prepaint::closure$1::closure$1::closure$0<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure$0::closure_env$0>
             at .\crates\gpui\src\elements\div.rs:1697
  67: gpui::window::Window::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$8::prepaint::closure$1::closure$1::closure_env$0<enum
             at .\crates\gpui\src\window.rs:2413
  68: gpui::elements::div::impl$8::prepaint::closure$1::closure$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure$0::closure_env$0>
             at .\crates\gpui\src\elements\div.rs:1686
  69: gpui::window::Window::with_text_style<gpui::elements::div::impl$8::prepaint::closure$1::closure_env$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure$0::closure_env$0>,tuple$<enum2$<core::option::Option<gp
             at .\crates\gpui\src\window.rs:2365
  70: gpui::elements::div::impl$8::prepaint::closure$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure$0::closure_env$0>
             at .\crates\gpui\src\elements\div.rs:1685
  71: gpui::window::Window::with_optional_element_state<gpui::elements::div::InteractiveElementState,enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$8::prepaint::closure_env$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui
             at .\crates\gpui\src\window.rs:2747
  72: gpui::elements::div::Interactivity::prepaint<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure$0::closure_env$0>
             at .\crates\gpui\src\elements\div.rs:1663
  73: gpui::elements::div::impl$6::prepaint::closure$0
             at .\crates\gpui\src\elements\div.rs:1412
  74: stacksafe::internal::with_protected::closure$0<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure_env$0>
             at C:\Users\Admin\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-e791a3f93f26854f\stacksafe-0.1.4\src\internal.rs:29
  75: stacker::maybe_grow
             at C:\Users\Admin\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-e791a3f93f26854f\stacker-0.1.22\src\lib.rs:57
  76: gpui::elements::div::impl$6::prepaint
             at .\crates\gpui\src\elements\div.rs:1361
  77: gpui::element::Drawable<gpui::elements::div::Div>::prepaint<gpui::elements::div::Div>
             at .\crates\gpui\src\element.rs:420
  78: gpui::element::impl$7::prepaint<gpui::elements::div::Div>
             at .\crates\gpui\src\element.rs:556
  79: gpui::element::AnyElement::prepaint
             at .\crates\gpui\src\element.rs:604
  80: gpui::view::impl$0::prepaint::closure$0<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate> >
             at .\crates\gpui\src\view.rs:64
  81: gpui::window::Window::with_rendered_view<enum2$<core::option::Option<gpui::window::FocusHandle> >,gpui::view::impl$0::prepaint::closure_env$0<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate> > >
             at .\crates\gpui\src\window.rs:3387
  82: gpui::view::impl$0::prepaint<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate> >
             at .\crates\gpui\src\view.rs:64
  83: gpui::element::Drawable<gpui::app::entity_map::Entity<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate> > >::prepaint<gpui::app::entity_map::Entity<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate> > >
             at .\crates\gpui\src\element.rs:420
  84: gpui::element::impl$7::prepaint<gpui::app::entity_map::Entity<picker::Picker<file_finder::open_path_prompt::OpenPathDelegate> > >
             at .\crates\gpui\src\element.rs:556
  85: gpui::element::AnyElement::prepaint
             at .\crates\gpui\src\element.rs:604
  86: gpui::elements::div::impl$6::prepaint::closure$0::closure$0::closure$0
             at .\crates\gpui\src\elements\div.rs:1427
  87: gpui::window::Window::with_element_offset<tuple$<>,gpui::elements::div::impl$6::prepaint::closure$0::closure$0::closure_env$0>
             at .\crates\gpui\src\window.rs:2431
  88: gpui::elements::div::impl$6::prepaint::closure$0::closure$0
             at .\crates\gpui\src\elements\div.rs:1425
  89: gpui::elements::div::impl$8::prepaint::closure$1::closure$1::closure$0<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure$0::closure_env$0>
             at .\crates\gpui\src\elements\div.rs:1697
  90: gpui::window::Window::with_content_mask<tuple$<enum2$<core::option::Option<gpui::window::Hitbox> >,enum2$<core::option::Option<gpui::elements::div::InteractiveElementState> > >,gpui::elements::div::impl$8::prepaint::closure$1::closure$1::closure_env$0<enum
             at .\crates\gpui\src\window.rs:2417
  91: gpui::elements::div::impl$8::prepaint::closure$1::closure$1<enum2$<core::option::Option<gpui::window::Hitbox> >,gpui::elements::div::impl$6::prepaint::closure$0::closure_env$0>
             at .\crates\gpui\src\elements\div.rs:1686
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\zed.exe` (exit code: 1)
```

**Comment by dDostalker** [comment]
I then conducted another test, and it seems that I have identified a more accurate cause.
At first, when I entered "C", the label and highlight_indics were like this:
```
[3]
"C:\\Config.Msi"
=====================
[3]
"C:\\Config.Msi"
=====================
[3]
"C:\\Config.Msi"
=====================
[9]                                                      <----------------------------- look at these lines , the vectors are 3 , 3, 9 
"C:\\$360Section"
=====================
[6]
"C:\\$Recycle.Bin"
=====================
```
And when I entered ":" ， the code highlighting was as expected, appearing small.
```
=====================
[]
"C:\\Config.Msi"
=====================
[]
"C:\\"
=====================
[]
"C:\\"
=====================
[]
"C:\\"
=====================
[]
"C:\\$360Section"
=====================
[]
"C:\\$Recycle.Bin"
=====================
```
Next step, I delete the ":" , zed crashed ,and the reason is that:
```
=====================
[3]
"C:\\Config.Msi"
=====================
[3]
"C:\\Config.Msi"
=====================
[3]
"C:\\Config.Msi"
=====================
[9]                                                             <---------------- the panic ,and the vectors also 3,3,9
"C:\\.\\"
```
I think the code might have mistakenly combined the previous highlighted position with the new display list, which is why this error occurred.

**Comment by dDostalker** [comment]
I managed to fix it.Now I have tested and confirmed that it is functioning properly.
#41356

**Comment by Veykril** [comment]
I believe this was fixed by https://github.com/zed-industries/zed/pull/40488, did you reproduce this on the latest commit?

**Comment by dDostalker** [comment]
> I believe this was fixed by [#40488](https://github.com/zed-industries/zed/pull/40488), did you reproduce this on the latest commit?

I clone  zed again and built it,but it,but it  still crashed.I have tried both of my computers and they have not been repaired.How can I help you solve the problem？I can provide more information

**Comment by dDostalker** [comment]
If necessary, you can tell me what information I need to obtain, and I can record the screen for you.I hope this can help you

**Comment by Veykril** [comment]
Thanks for double checking! I'll have a look  whether I can reproduce this myself later

**Comment by Veykril** [comment]
Yup this is not windows specific (it's just easier to run into on windows). I am looking into this and hopeful in fixing this for the next release next week

**Comment by Manezki** [comment]
I'm experiencing similar kind of crash on Linux.

Steps to produce:
1. Open Python file in Zed.
2. Bottom right, click Python version to trigger "Select virtual environment" (couldn't find a command for this 🤔 ).
3. Select "Add virtual environment".
4. In the `[directory/]filename.ext` input, try inputting "/home".
5. Observe crash.

## System details
Zed: v0.210.4 (Zed) 
OS: Linux Wayland ubuntu 24.04
Memory: 60.6 GiB
Architecture: x86_64
GPU: AMD Radeon 780M (RADV PHOENIX) || radv || Mesa 25.0.7-0ubuntu0.24.04.2

## Zed.log
```text
2025-11-02T09:25:12+01:00 INFO  [zed] ========== starting zed version 0.210.4, sha 428ef50 ==========
2025-11-02T09:25:12+01:00 INFO  [zed] Using git binary path: None
2025-11-02T09:25:12+01:00 INFO  [crashes] spawning crash handler process
2025-11-02T09:25:12+01:00 INFO  [extension_host] extensions updated. loading 1, reloading 0, unloading 0
2025-11-02T09:25:12+01:00 INFO  [gpui::platform::linux::platform] activate is not implemented on Linux, ignoring the call
2025-11-02T09:25:12+01:00 INFO  [auto_update] Auto Update: checking for updates
2025-11-02T09:25:12+01:00 INFO  [util] set environment variables from shell:/usr/bin/fish, path:/home/manezki/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
2025-11-02T09:25:12+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: PreMultiplied }
2025-11-02T09:25:12+01:00 INFO  [workspace] Rendered first frame
2025-11-02T09:25:12+01:00 INFO  [zed::zed] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "AMD Radeon 780M (RADV PHOENIX)", driver_name: "radv", driver_info: "Mesa 25.0.7-0ubuntu0.24.04.2" }
2025-11-02T09:25:12+01:00 INFO  [gpui::platform::blade::blade_renderer] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8Unorm, alpha: Ignored }
2025-11-02T09:25:12+01:00 INFO  [crashes] connected to crash handler process after 100ms
2025-11-02T09:25:12+01:00 INFO  [crashes] crash handler registered
2025-11-02T09:25:12+01:00 INFO  [zed::reliability] Uploaded minidump. event id: b122acab-2ff3-42a5-b19a-757f1349b5bf
2025-11-02T09:25:12+01:00 INFO  [project::environment] using project environment variables shell launched in "/home/manezki/Projects/CryptidSolver". PATH="/home/manezki/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin"
2025-11-02T09:25:12+01:00 INFO  [language] found user-installed language server for ruff. path: "/home/manezki/.local/bin/ruff", arguments: ["server"]
2025-11-02T09:25:12+01:00 INFO  [node_runtime] Node runtime install_if_needed
2025-11-02T09:25:12+01:00 INFO  [lsp] starting language server process. binary path: "/home/manezki/.local/bin/ruff", working directory: "/home/manezki/Projects/CryptidSolver", args: ["server"]
2025-11-02T09:25:12+01:00 INFO  [project::environment] using project environment variables shell launched in "/home/manezki/.local/share/zed/languages/basedpyright/node_modules/basedpyright/dist/typeshed-fallback/stdlib". PATH="/home/manezki/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin"
2025-11-02T09:25:12+01:00 INFO  [node_runtime] using Zed managed Node.js at /home/manezki/.local/share/zed/node/node-v22.5.1-linux-x64 since system Node.js wasn't found on PATH: cannot find binary path
2025-11-02T09:25:12+01:00 INFO  [lsp] starting language server process. binary path: "/home/manezki/.local/share/zed/node/node-v22.5.1-linux-x64/bin/node", working directory: "/home/manezki/Projects/CryptidSolver", args: ["/home/manezki/.local/share/zed/languages/basedpyright/node_modules/basedpyright/langserver.index.js", "--stdio"]
2025-11-02T09:25:12+01:00 INFO  [project::lsp_store] language server 3: unregistered workspace/DidChangeWatchedFiles capability with id db26dd96-7583-4aac-b105-1cd66a1c86ee
2025-11-02T09:27:49+01:00 ERROR [crashes] triggering a crash to generate a minidump...

```
