### ISSUE TITLE
Windows: Some terminal windows shortly pop up and closing again when opening a Python project.

### ISSUE THREAD

**Issue by Padi2312** [zed-industries/zed#41388]
### Summary

When opening a Python project with Zed, a few terminal windows pop up and close again instantly.

### Description
Steps to trigger the problem:
1. Create a python project with a venv. (I am using `uv venv` for this)
2. Opening Zed again with this Project

**Expected Behavior**: There should not randomly pop up terminal windows for a few milliseconds
**Actual Behavior**: They're poping up 

https://github.com/user-attachments/assets/09475927-af96-4885-9532-2e15b1a41cb6

In the video it's more often because it did not focus the window again, it stops after a few openings.

Additional:
Recognized similiar behaviour when clicking on "Select Virtual Environment" in bottom action bar.

https://github.com/user-attachments/assets/0d34ae16-08d2-4ce3-9c5c-b7c75b3c6527

### Zed Version and System Specs

Zed: v0.211.0 (Zed Nightly 9c2321d7f9584264267f0b1afd1856b5120aaf59) 
OS: Windows 10.0.26100
Memory: 47.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3060 || NVIDIA Corporation || 581.29 r581_07

**Comment by franciskafyi** [comment]
Wow that looks weird 😅 Thank you for the videos. We'll take a closer look at this asap!

**Comment by abhinath84** [comment]
I'm also facing the same issue on my windows os based system.

**Comment by Veykril** [comment]
Fixed by https://github.com/zed-industries/zed/pull/41737

**Comment by p-arndt** [comment]
I can confirm it's fixed. Thanks for this fast and good support!

**Comment by md-owes** [comment]
I counted 272 pop-ups opening in about 4 minutes after launching my simple Python project. This is incredibly frustrating. I love using Zed, but not when such disappointing issues arise.

**Comment by franciskafyi** [comment]
@md-owes this should have been fixed, can you check on the latest release?

**Comment by 4o3F** [comment]
I'm using 0.212.6 74924bc91865f111542ac6b1554231a0d3f66f89, but the issue still exists and with the same behaviour, seems not fixed?

**Comment by Veykril** [comment]
We might be missing the flags on some commands spawned, I'll have a look at this. Sorry for the annoyance. 

On that note, do you have an easy way to reproduce this for me? (assuming what OP posted is fixed)

**Comment by 4o3F** [comment]
For me step to reproduce is simple.
1. Use `uv init` to create a empty project.
2. Open the folder in Zed, then click to open `main.py`

There'll be a terminal windows flashed at the time when `main.py` is opened. And can be trigged when clicking the Python venv on bottom right. Note that even without a virtual environment, using global python will also trigger this.

**Comment by Veykril** [comment]
I can't seem to repro this on nightly at least, so maybe wwe didnt cherry pick the PR, either way https://github.com/zed-industries/zed/pull/42976 will help in reducing this further. Please let me know if tomorrows release fixes this or not. I'll close it until then

**Comment by md-owes** [comment]
@franciskafyi, it is still occurring in 0.212.6

**Comment by Veykril** [comment]
As per my comment, 

> Please let me know if tomorrows release fixes this or not. I'll close it until then

please wait until tomorrows release (0.213) and check again then

**Comment by 4o3F** [comment]
I've tried the latest 0.213 pre-release and the issue still exists. 
I found out this is caused by a broken python installation on my device, which caused the following log.
```
2025-11-19T20:25:34+08:00 ERROR [pet_python_utils::env] Python Execution for "C:\\ProgramData\\chocolatey\\bin\\python3.12.exe" produced an output "Cannot find file at 'c:\\python312\\python.exe' (c:\\python312\\python.exe). This usually indicates a missing or moved file." without a separator
```
And after removing the broken python, no more window showed up, maybe Zed can better handle this instead of keep trying and showing several flshing window?

**Comment by CypherpunkSamurai** [comment]
Ok. Nightly Fixes this. https://github.com/zed-industries/zed/actions/runs/19780564516

Waiting for proper release.

**Comment by Veykril** [comment]
Was fixed in https://github.com/zed-industries/zed/pull/43496, thanks for confirming that is indeed the case.
