### ISSUE TITLE
Pinned tab causes resize loop on tab to its right

### ISSUE THREAD

**Issue by teohhanhui** [zed-industries/zed#41467]
### Summary

Pinned tab causes resize loop on tab to its right

### Description

If I have a pinned tab (1st tab), then the tab immediately to its right (2nd tab) would be stuck in a resize loop / endless flickering. Seems to only happen when the 2nd tab is less than the max tab width or something like that.

Steps to reproduce:
1. Open first tab (e.g. `README.md`).
2. Pin first tab.
3. Open second tab (with a short filename, e.g. `.env`).

**Expected Behavior**: Second tab width is stable.
**Actual Behavior**: Second tab is stuck in a resize loop / constant flickering.

### Zed Version and System Specs

Zed: v0.209.7 (Zed) 
OS: Linux Wayland fedora-asahi-remix 42
Memory: 15.3 GiB
Architecture: aarch64
GPU: Apple M2 (G14G B0) || Honeykrisp || Mesa 25.2.4

**Comment by teohhanhui** [comment]
https://github.com/user-attachments/assets/3c1602b5-2e24-4574-9ebb-7821d1464b70

**Comment by MrSubidubi** [comment]
Yeah that doesn't look good, thanks for the report!

This might actually be depending on your scale factor, as I just now was unable to reproduce this. But we recently had changes around GPUI that might be causing this. IIRC we also style something there conditionally, which is most likely the cause of this.

Optimistically labeling as "good first issue" because this should be good to track down and not too hard to fix, hopefully someone is able to both reproduce and look into this. Thanks!

**Comment by bersace** [comment]
I confirm this.

https://github.com/user-attachments/assets/6b018aed-0a98-4d7f-bbc4-60268bfb9379

**Comment by Pieczasz** [comment]
I can reproduce the bug, and will try to fix this as my first issue!

**Comment by boobachad** [comment]
i belive this issue has been resolved as of zed stable release 0.211.4 although i didnt see any terminal tab related changes or pr's in the release notes(i might have missed) since i did encounter this previously but currently this is no longer the case

**Edit:** i observed this on **OS: Windows**

**Comment by boobachad** [comment]
but i still dont know what caused the issue and what fixed it.

i have read the pr https://github.com/zed-industries/zed/pull/41884 but i dont think that fixed it since its still not merged

**Comment by Pieczasz** [comment]
I also see that the issue is fixed. So this issue can be probably closed

**Comment by teohhanhui** [comment]
I'm on 0.211.6 and it's not fixed for me. The reproducer in the OP still produces the same buggy behaviour.

UPDATE: Looks like it only happens with certain fonts, e.g.:

```json
{
  "ui_font_family": "Noto Sans Mono"
}
```

And as has previously been pointed out, this also only happens with fractional scale factor.

**Comment by bersace** [comment]
Same, still reproducing it on Zed 0.211.6. Using fractionnal scale on Wayland and JetBrains Mono NF.
