### ISSUE TITLE
Code completion ordering is broken for Web Dev

### ISSUE THREAD

**Issue by fmarkulin** [zed-industries/zed#42007]
### Summary

Code completion ordering is not good for web development.

### Description
When I want to destructure an object, it's keys are at the bottom, first is offered comparison elements for some reason. Also, when trying to add className="" to an HTML element, it offers the plain text "className" instead of the prop first.

Steps to reproduce:
1. Start react/nextjs project
2. Create object with multiple keys
3. Try to destructure key.
4. Create HTML element
5. Try to access the className prop

**Expected Behavior**: offer object keys and props first
**Actual Behavior**: offers comparison elements and plain text results first

<details><summary>Video (click to expand)</summary>

https://github.com/user-attachments/assets/e9cba26b-27da-4a55-a179-574d717d1cf8

</details>

### Zed Version and System Specs

Zed: v0.210.4 (Zed) 
OS: macOS 26.0.1
Memory: 24 GiB
Architecture: aarch64

**Comment by smitbarmase** [comment]
This is probably fixed by https://github.com/zed-industries/zed/pull/42065. Can you try it on 0.211.5 onwards?

**Comment by victoremeka** [comment]
This is still broken on 0.214.5
It's the same behaviour regardless of language.
