### ISSUE TITLE
Node.js Typescript. Can't run Playwright tests

### ISSUE THREAD

**Issue by NeilRiver** [zed-industries/zed#42029]
### Summary

Playwright tests fail to run in Zed due to ERR_UNKNOWN_FILE_EXTENSION for .ts files

### Description
After installing Playwright using `npm init playwright@latest`, I tried running the default test file (`example.spec.ts`) directly from the Zed editor. When I click the "Play" button, nothing happens — the test doesn't run, and the following error appears in the terminal:

```
node:internal/modules/esm/get_format:218
  throw new ERR_UNKNOWN_FILE_EXTENSION(ext, filepath);
        ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\Users\user\Desktop\1\tests\example.spec.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:218:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:244:36)
    at defaultLoad (node:internal/modules/esm/load:122:22)
    at async ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:479:32)
    at async ModuleJob._link (node:internal/modules/esm/module_job:112:19) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v22.11.0
✖ C:\Users\user\Desktop\1\tests\example.spec.ts (52.2123ms)
  'test failed'
```

Steps to reproduce:
1. Run `npm init playwright@latest` to scaffold a new Playwright project
2. Open the project in Zed
3. Click the "Play" button on the default test file (`example.spec.ts`)
4. Observe the terminal output

**Expected Behavior**:
The test should execute successfully, just like when running via CLI (`npx playwright test`)

**Actual Behavior**:
Zed fails to run the test and throws an error about the `.ts` file extension

<details><summary>click to expand</summary>

```json
{
  "nodeVersion": "v22.11.0",
  "playwrightVersion": "latest",
  "file": "tests/example.spec.ts",
  "error": "ERR_UNKNOWN_FILE_EXTENSION"
}
```

</details>

### Zed Version and System Specs

Zed: v0.210.4 (Zed) 
OS: Windows 10.0.22631
Memory: 15.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2070 || NVIDIA Corporation || 576.88 r576_76
__
node -v -> v22.11.0
npm -v  -> 10.8.0

**Comment by versecafe** [comment]
@NeilRiver this should be fixed with https://github.com/zed-industries/zed/pull/41956 as strip types became the default behavior in 22.18.0

**Comment by NeilRiver** [comment]
Still an error... I should ask, is it even possible to run playwright tests via the "play" button? In vscode, we used to download an extension.
_
C:\Users\user\Desktop\1\node_modules\playwright\lib\common\testType.js:74
      throw new Error([
            ^

Error: Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.
    at TestTypeImpl._currentSuite (C:\Users\user\Desktop\1\node_modules\playwright\lib\common\testType.js:74:13)
    at TestTypeImpl._createTest (C:\Users\user\Desktop\1\node_modules\playwright\lib\common\testType.js:87:24)
    at C:\Users\user\Desktop\1\node_modules\playwright\lib\transform\transform.js:275:12
    at file:///C:/Users/user/Desktop/1/tests/example.spec.ts:3:1
    at ModuleJob.run (node:internal/modules/esm/module_job:377:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:671:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)

Node.js v25.1.0
✖ C:\Users\user\Desktop\1\tests\example.spec.ts (937.0231ms)
ℹ tests 1
ℹ suites 0
ℹ pass 0
ℹ fail 1
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 949.6146

✖ failing tests:

test at tests\example.spec.ts:1:1
✖ C:\Users\user\Desktop\1\tests\example.spec.ts (937.0231ms)
  'test failed'

**Comment by versecafe** [comment]
@NeilRiver it's running node test instead of playwright test which is causing the issue, I'll open up a PR today to add it to the detection list for test runners

**Comment by NeilRiver** [comment]
@versecafe Thanks a lot

If possible, please add a selenium test launcher

**Comment by NeilRiver** [comment]
@versecafe please tell me how to do this myself? or is everything bad there?

**Comment by NeilRiver** [comment]
up

**Comment by NeilRiver** [comment]
<img width="1600" height="898" alt="Image" src="https://github.com/user-attachments/assets/6c1494f5-67ed-4a2b-9e27-509317c30f7c" />

**Comment by miguelraz** [comment]
I'll try this out tomorrow @NeilRiver , thanks for the instructions!

**Comment by DronovasP** [comment]
Hey @miguelraz, any luck with this? A fix to this would greatly improve my test development flow 😄

**Comment by miguelraz** [comment]
@DronovasP sorry, I just triage and reproduce issues - thanks for your report! The concrete steps were trivial to follow.

**Comment by NeilRiver** [comment]
@miguelraz Is it possible to put it into some sprint ?

**Comment by NoahMenezes** [comment]
I am working on updating the Tree-sitter runnable test queries in crates/grammars/src/typescript/runnables.scm and crates/grammars/src/tsx/runnables.scm to support template_string test titles used by Playwright and Vitest. Will submit a PR shortly!
