### ISSUE TITLE
Bug: Opening a new Window and then opening a command palette (i.e. cmd+opt+n or cmd+p) closes it.

### ISSUE THREAD

**Issue by Blankeos** [zed-industries/zed#43297]
### Summary

When I open another window (via `⌘ ⇧ N`) and then immediately run command anything that opens a cmd dialog: i.e. `⌘ ⌥ N` or `⌘ P` it closes.

A workaround is I just wait like 1 second before running  `⌘⌥N` or `⌘P`.

### Description

Steps to reproduce:
1. Run `⌘ ⌥ N` - opens a new window
2. Run  `⌘ P` - opens a palette
3. Bug: Closes instantly.
4. Run `⌘ P` again (annoyingly).

**Expected Behavior**: (3) never happens
**Actual Behavior**: (3) happens

https://github.com/user-attachments/assets/6ccc085d-49a5-426c-b7ae-f1bb21afcd13

### Zed Version and System Specs

Zed: v0.213.3 (Zed) 
OS: macOS 15.5
Memory: 36 GiB
Architecture: aarch64

**Comment by dangh** [comment]
Thanks for reporting this. It's been driving me nuts.

**Comment by SomeoneToIgnore** [comment]
Should be fixed in https://github.com/zed-industries/zed/pull/43180

**Comment by Blankeos** [comment]
This is still happening again btw. Even in the vanilla Zed (no new settings/extensions)

I think the **terminal** is now the issue that's stealing focus. (Not the agent panel anymore)

**Comment by Blankeos** [comment]
Video demonstration of terminal stealing focus...

https://github.com/user-attachments/assets/e9505fd5-7f62-4b32-9162-90b814583bd9

**Comment by smitbarmase** [comment]
Closing this because the issue was fixed in https://github.com/zed-industries/zed/pull/43180.

@Blankeos, for the issue you mentioned in your comment, it would be great if you could create a new issue with the correct reproduction steps and your `settings.json`. That way, the community or someone from our team can verify the behavior and confirm how to reproduce it.
