### ISSUE TITLE
Compile messages from newly added packages in Elixir LSP gets added to top of currently opened file

### ISSUE THREAD

**Issue by bopm** [zed-industries/zed#4514]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open Phoenix project, add a new dependency, go to the console, and run `mix deps.get` after which get back to editing code. As soon as LSP triggers code compilation, its results will be added to the top of the current file:
```
==> ecto_ranked
Compiling 2 files (.ex)
Generated ecto_ranked app
==> req
Compiling 5 files (.ex)
Generated req app
==> meilisearch
Compiling 13 files (.ex)
Generated meilisearch app
```

### Environment

Zed: v0.100.1 (stable)
OS: macOS 13.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="850" alt="image" src="https://github.com/zed-industries/community/assets/95571/9225c0d6-344f-45d0-ba88-57a16a7ecd62">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

2023-08-28T17:20:12 [ERROR] failed to format via external command "mix"

Caused by:
    command failed with exit code Some(1):
    stdout: 
    stderr: Unchecked dependencies for environment dev:
    * ecto_ranked (Hex package)
      the dependency is not available, run "mix deps.get"
    ** (Mix) Can't continue due to errors on dependencies
    
2023-08-28T17:21:17 [ERROR] failed to format via external command "mix"

Caused by:
    command failed with exit code Some(1):
    stdout: 
    stderr: Unchecked dependencies for environment dev:
    * meilisearch (Hex package)
      the dependency is not available, run "mix deps.get"
    * ecto_ranked (Hex package)
      the dependency is not available, run "mix deps.get"
    ** (Mix) Can't continue due to errors on dependencies
    
2023-08-28T17:29:02 [ERROR] failed to format via external command "mix"

Caused by:
    command failed with exit code Some(1):
    stdout: 
    stderr: ** (SyntaxError) config/config.exs:1:1: syntax error before: '=='
        |
      1 | ==> ecto_ranked
        | ^
        (elixir 1.15.5) lib/code.ex:542: Code.validated_eval_string/3
        (elixir 1.15.5) lib/config.ex:290: Config.__eval__!/3
        (mix 1.15.5) lib/mix/tasks/loadconfig.ex:54: Mix.Tasks.Loadconfig.load_compile/1
        (mix 1.15.5) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
        (mix 1.15.5) lib/mix/cli.ex:91: Mix.CLI.run_task/2
        /opt/homebrew/bin/mix:2: (file)

**Comment by notpeter** [comment]
@bopm Is this something you are still experiencing in Zed with Elixer projects? I'm going through the backlog and am hoping we may have already fixed this. Thanks

**Comment by bopm** [comment]
@notpeter I saw it a few months ago, so not that far back in the past. Same flow as before, edit things while `mix deps.get` installing new versions of packages, the output of that `mix deps.get` will be added to the top of the current file.

**Comment by mrnugget** [comment]
Thing to investigate: is this probably a problem with `mix`, as external formatter, failing to format and us ignoring exit-code and putting stderr/stdout in file? 

(Maybe need to update docs to recommend how to fix it)

**Comment by bopm** [comment]
I am seeing it with every background compliation of Elixir now (Zed 0.211.6). Config for LSP is 
```
"Elixir": {
      "language_servers": [
        "expert",
        "!elixir-ls",
        "!next-ls",
        "!lexical",
        "..."
      ],
      "format_on_save": {
        "external": {
          "command": "mix",
          "arguments": ["format", "--stdin-filename", "{buffer_path}", "-"]
        }
      }
    }
```

**Comment by tomekowal** [comment]
Hey @bopm That is an old config. Use:
```
  "format_on_save": "on"
```
instead and that should fix the issue.

**Comment by bopm** [comment]
Yep, I noticed that, and changed to:
```json
"format_on_save": "on",
      "formatter": {
        "external": {
          "command": "mix",
          "arguments": ["format", "--stdin-filename", "{buffer_path}", "-"]
        }
      }
```
Unfortunately, the issue persists.

**Comment by tomekowal** [comment]
Sorry, I wasn't clear. Delete the entire formatter section. Zed knows to use mix format, but I think it wraps it somehow.

As long as you directly tell it to use mix format command, there will be those artifacts from compilation. If you delete it, it will use mix format correctly.

**Comment by bopm** [comment]
Unfortunately, it's not working as it's supposed to without `formatter/external`. 

Test case is simple: in the Phoenix project, go to the `lib/..._web/components/core_components.ex`, and for example, add a new line before `</dd>` in the list component. Format on save with `formatter/external` will remove that new line. Without it, it'll stay on the new line. 

I think it is somehow connected to the `.formatter.exs` being used/not used, but I do not know for sure.
