### ISSUE TITLE
Unexpected wrap?

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#4573]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```
def payload(slug, offset=0, length=15):
    return {
        "query": "query TagPageQuery($short: String, $slug: String!, $order: String, $offset: Int!, $length: Int!) {\n  locale(short: $short) {\n    tag(slug: $slug) {\n      cacheKey\n      id\n      slug\n      avatar\n      createdAt\n      updatedAt\n      redirectRelativeUrl\n      alternates {\n        cacheKey\n        short\n        domain\n        id\n        code\n        __typename\n      }\n      tagTranslates {\n        cacheKey\n        id\n        title\n        metaTitle\n        pageTitle\n        description\n        metaDescription\n        keywords\n        __typename\n      }\n      posts(order: $order, offset: $offset, length: $length) {\n        data {\n          cacheKey\n          id\n          slug\n          views\n          postTranslate {\n            cacheKey\n            id\n            title\n            avatar\n            published\n            publishedHumanFormat\n            leadText\n            author {\n              cacheKey\n              id\n              slug\n              authorTranslates {\n                cacheKey\n                id\n                name\n                __typename\n              }\n              __typename\n            }\n            __typename\n          }\n          category {\n            cacheKey\n            id\n            __typename\n          }\n          author {\n            cacheKey\n            id\n            slug\n            authorTranslates {\n              cacheKey\n              id\n              name\n              __typename\n            }\n            __typename\n          }\n          postBadge {\n            cacheKey\n            id\n            label\n            postBadgeTranslates {\n              cacheKey\n              id\n              title\n              __typename\n            }\n            __typename\n          }\n          showShares\n          showStats\n          __typename\n        }\n        postsCount\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}",
        "operationName": "TagPageQuery",
        "variables": {
            "slug": slug,
            "order": "postPublishedTime",
            "offset": offset,
            "length": length,
            "short": "en",
            "cacheTimeInMS": 300000,
        },
    }
```

If soft wrap is off, the text looks like (it wraps at about 500 chars)

<img width="948" alt="image" src="https://github.com/zed-industries/community/assets/5475262/31dbe830-862a-4aa7-b4b0-d8be3d77036d">

In Emacs it looks like

<img width="969" alt="image" src="https://github.com/zed-industries/community/assets/5475262/af2e1f31-6f0a-41ab-9cb0-c2a6370fea76">

If soft wrap is on, it looks like

<img width="935" alt="image" src="https://github.com/zed-industries/community/assets/5475262/bc6b006b-3c31-4508-80b4-067b7dc9f781">

Not sure if this is a bug...when soft wrap is off, why it looks like 'semi-soft wrap'?

### Environment

Zed: v0.97.5 (preview)
OS: macOS 13.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by failable** [comment]
Still happens in 

```
Zed: v0.154.1 (Zed Preview)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: x86_64
```

**Comment by fuzenco** [comment]
This appears fixed in Zed Preview 0.155.0. Thanks for following up on this issue.

**Comment by failable** [comment]
It still happens here 

<img width="962" alt="image" src="https://github.com/user-attachments/assets/24af3bee-798f-483e-a3c0-6cce38805791">

```
Zed: v0.155.1 (Zed Preview)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: x86_64
```

**Comment by fuzenco** [comment]
I see. But my post was in reference to Markdown or plain text files. In those, the matter seems fixed.

**Comment by avamsi** [comment]
Seeing this issue in txt files as well (but more importantly for me, in log files).

**Comment by kliu** [comment]
![Screenshot 2024-11-29 at 10 53 58](https://github.com/user-attachments/assets/b4d02711-a1da-4688-9753-5d95602d66cd)

![Screenshot 2024-11-29 at 10 53 45](https://github.com/user-attachments/assets/483188fe-94f6-40b7-a241-fe9ca2a145e2)

The issue is very easy to reproduce, in fact, when the text does not include spaces or other symbols (excluding whole word wrap), you'll find that with soft wrap turned off, there are only a maximum of 512 characters per line.

I believe this is intentional on Zed for issue https://github.com/zed-industries/zed/issues/834 and as a limit of MAX_LINE_LEN 512 in PR https://github.com/zed-industries/zed/pull/866.

This is make sense, but it makes it inconvenient for Zed to work with some files such as logs or CSVs.

**Comment by avamsi** [comment]
@as-cii @nathansobo could you please reconsider this decision to wrap at a certain point no matter user settings? This is almost the only thing that I need to go back to VS Code for.

**Comment by thomaseizinger** [comment]
> This is make sense, but it makes inconvenient for Zed to work with some files such as logs or CSVs.

Agreed. In my case, I want to edit log files with very long lines and multi-cursor. Selecting part of the text and using "shift+end" does not actually select the end of the line (as defined by the next newline character) but instead only selects text until the soft-wrap.

IMO, with soft-wrapping off, Zed should simply not soft-wrap at all.

**Comment by rmnilin** [comment]
The issue is relevant.

Zed wraps 513th character (column 514 in status bar) even with `"soft_wrap": "none"`:

<details>
<summary>Screenshot</summary>
<img width="738" height="471" alt="Image" src="https://github.com/user-attachments/assets/0eb57bee-29b7-43c1-b3cc-7108b479f5fa" />
</details>

It's hardcoded:
- https://github.com/zed-industries/zed/blob/v0.205.9/crates/editor/src/element.rs#L8438
- https://github.com/zed-industries/zed/blob/v0.205.9/crates/editor/src/editor.rs#L221

but inconvenient for the reasons described above.

**Comment by Veykril** [comment]
For context, the reason for this hardcoding right now is part perf, part stability. We don't handle super long non wrapped lines too well and on macOS this can even cause crashes in text shaping, so this hardcoded limit was introduced as a temporary bandaid.

**Comment by sylbru** [comment]
I can confirm this is an issue, for instance as I was working on Apache error logs. Some lines contained more than 2000 characters, resulting in being wrapped over 5 lines.

**Comment by sadiogo** [comment]
I'm seeing the same results in a json file. the lines wrap around 511 columns

**Comment by AFulgens** [comment]
I see it in a JSON file containing long base64 values where with soft-wrap disabled wrap still happens at `/` and `+` characters, repeating after each 500 characters, regardless of settings.
