### ISSUE TITLE
Autocomplete picking deletes characters after the cursor

### ISSUE THREAD

**Issue by msfeldstein** [zed-industries/zed#4816]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When i want to add a new function around `imageBytes` here you can see that it consumes and deletes the entire name `imageBytes` to replace the whole thing with the suggestion.  I think it should treat the cursor as the end of what you are suggesting on leave everything after the cursor so i can easily wrap something in another function.

https://user-images.githubusercontent.com/161135/230510995-70f769f9-e520-4dd5-b1b5-e66beeaaff8a.mov

### Environment

Zed: v0.80.5 (stable)
OS: macOS 13.3.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by jordanjones98** [comment]
Another bump here, this is very annoying.

**Comment by osiewicz** [comment]
Let's keep this issue open; the OP has been fixed, but I worry that it might break the workflow for people who preferred the old behavior (though I'm definitely not one of them :) ). We might want to preserve the old behavior with a key modifier (say, cmd+enter on completion list may replace the word following cursor position and enter would just append the selection)

**Comment by JosephTLyons** [comment]
We just shipped [v0.129.0-pre](https://zed.dev/releases/preview/0.129.0), which has a fix for this.

**Comment by Foxomat** [comment]
I am **still having this issue**. Is an option now somewhere thats off by default or what?

**Comment by marcospb19** [comment]
After https://github.com/zed-industries/zed/pull/27453, the new setting completions.lsp_insert_mode is set to the default replace_suffix option, which checks that the text after the cursor is not a suffix.

So this is now fixed by default.
