### ISSUE TITLE
Tab characters only count as a single column for column number display

### ISSUE THREAD

**Issue by j3h** [zed-industries/zed#5059]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed's column number display in the bottom right corner of the editor window is incremented by only one for each tab character, regardless of the configured tab width. It's hard to say what the correct behavior is here, since "column" could mean different things, but:
- VS code shows the display column (counting tabs as the configured number of spaces).
- Emacs does the same.
- Vim shows both the character number and the display column with a dash in between.

This suggests to me that the expected behavior would be to count tabs as the configured number of spaces for determining the column number rather than counting them as one column.

### Environment

Zed 0.67.5 – /Applications/Zed.app
macOS 13.1
architecture x86_64

**Comment by JosephTLyons** [comment]
I think this is fixed in current Zed, so I'm going to close this issue out. Feel free to reopen if you hit it again.

**Comment by nicolasbarbier** [comment]
This is still a problem in version 0.182.11 (I assume it was never fixed). I could not find a setting to configure this.

I have it when editing all my kinds of files (XML, .rs, .rnc, shell scripts), so it does not seem to de dependent on the file type/formatter/syntax highlighting.

Please reopen (I don't have the permission to reopen myself).
