### ISSUE TITLE
High refresh rate support

### ISSUE THREAD

**Issue by szlend** [zed-industries/zed#6427]
### Check for existing issues

- [X] Completed

### Describe the feature

Scrolling through text in Zed feels choppier compared to Visual Studio Code on a high refresh rate display (MacBook Pro M1). It would be great if Zed supported rendering at high (or variable) refresh rates.

I'm not really sure how to verify if this is the case but is rendering capped at 60 fps right now?

**Comment by as-cii** [comment]
Zed should adapt to the refresh rate of the screen it is being displayed on, so I think something weird is happening here. It would be great if you could enable the Metal Performance HUD:

```
/bin/launchctl setenv MTL_HUD_ENABLED 1
```

And then restart Zed. Something like this should appear on the top-right corner:

<img width="1674" alt="image" src="https://github.com/zed-industries/zed/assets/482957/509f75a4-c375-4e6f-8f88-e97292dbe655">

It would also be really helpful if you could capture a CPU Profile (via Instruments.app) of the `zed` process while you scroll around. Thank you!

**Comment by oliver-kriska** [comment]
Hello, I feel I have same issue. I recorded Metal Performance HUD:

https://github.com/zed-industries/zed/assets/39122854/cedc0afc-e5b1-4115-944b-aac6bfb49fc4

but I was not able to run CPU Profile, it crash every time when I select CPU Profiler in Instruments.app.

**Comment by szlend** [comment]
I opened Zed with `MTL_HUD_ENABLED=1`. I then kept scrolling to the bottom of the page, which took a few seconds as it was a large document. After the initial ramp up, the FPS settled averaging, around 70fps.

I'll see if I can get Instruments.app running to get a CPU profile. I need to set up Xcode first though.

**Comment by szlend** [comment]
Here's a trace of me scrolling in Zed: [zed-scrolling.trace.zip](https://github.com/zed-industries/zed/files/14057546/zed-scrolling.trace.zip)

FWIW, I also opened devtools and did some profiling in vscode. I can confirm that vscode scrolls at a consistent 120fps (~8.3ms per frame).

**Comment by mrnugget** [comment]
Hey @szlend and @oliver-kriska! Thanks for reporting. I've also seen some interesting FPS "problems" in past few days but I can't really track them down.

Me and @as-cii looked at your trace (thanks!) but nothing really stood out. We also couldn't reproduce it:

* I opened https://raw.githubusercontent.com/microsoft/TypeScript/main/src/compiler/types.ts in Zed and VS Code on my M3 Max display and scrolled with the MacBook touchpad as far as I could. I reached the same FPS numbers in both: ~110-120 depending on scroll speed.

Can you give us some more data points? All of the following might have an influence:

* **Zed configuration**: buffer font-family? UI font-family? Font-sizes? Line-height? Ligatures enabled or not? 
* **File you're scrolling through:** what file? How long is file? Do you use a language server? What's the configuration (inlay hints, diagnostics, hints) you use there? Lots of errors/diagnostics to show?
* **Display**: what's the resolution and refresh rate? Do you have an external display connected too?
* **How do you scroll?** Keyboard/trackpad/mouse wheel? Does it show up with another mouse? Do you use consistent as-fast-as-possible scrolling or do you use the "momentum" thing of the touchpad?

Maybe we can also turn this around: can you open the [`types.ts`](https://raw.githubusercontent.com/microsoft/TypeScript/main/src/compiler/types.ts) file and see how fast you can scroll in that one?

Also, I know this is asking too much, but if you're in the mood: a phone recording of the Zed on a display being scrolled would be ideal, becaues that way it's easy to see how fast the scroll is (because it's hard to capture on a screenrecording).

**Comment by szlend** [comment]
@mrnugget I think I might have figured out how to reproduce this. The scrolling is smooth as long as the editor is open in windowed mode. As soon as I fullscreen it (so it moves to another workspace) it stars lagging again. 

With the Metal HUD I can see that it switches from `Composited` to `Direct` when going fullscreen.

**Comment by mrnugget** [comment]
Okay, that's very interesting. From what I understand, `Direct` should be faster than `Composited`.

I still can't reproduce it, even in fullscreen mode.

**Comment by szlend** [comment]
- **Zed configuration:** Defaults. I disabled all customizations to test this.
- **File you're scrolling through:** [types.ts](https://raw.githubusercontent.com/microsoft/TypeScript/main/src/compiler/types.ts)
- **Display:** Just the MacBook Pro M1 display, 3456 × 2234 (scaled 1728 x 1117)
- **How do you scroll?** Macbook trackpad. Keep scrolling to the bottom without losing momentum. But it's the same effect if you just jiggle up and down repeatedly. Or if you use the mouse cursor to move the scrollbar. I don't think it's related to the input device.

**Comment by haze** [comment]
Another repro here:

**Zed configuration**
<details>
```json
{
  "theme": "Summercamp",
  "telemetry": {
    "diagnostics": false,
    "metrics": false
  },
  "vim_mode": true,
  "ui_font_size": 16,
  "buffer_font_size": 16
}
```
</details>

**File you're scrolling through**
https://github.com/haze/rehype-tree-sitter/blob/main/src/lib.rs

**Display**
Default 2023 14" Display (3024x1964 @ 120Hz (as 1512x982) [Built-in])

**How do you scroll**
Same as @szlend; scrolling all the way to the top and bottoms of file, jiggling, etc.

**Comment by szlend** [comment]
When I'm scrolling in `Direct` mode the Metal HUD shows the min FPS 60 and max FPS 120. To me it seems like variable refresh rate doesn't work in Direct mode and it alternates between 120fps and 60fps vsync. But that's just a guess.

**Comment by rev4324** [comment]
**File you're scrolling through:**
[types.ts](https://raw.githubusercontent.com/microsoft/TypeScript/main/src/compiler/types.ts)

**Display**
240Hz 1440p monitor rendering in scaled 5K - Gigabyte M27Q X, hooked up via Type-C to my M1 Air

**How do you scroll?**
MacBook trackpad. I tried to scroll fast without losing inertia. Zed is definitely scrolling faster using the trackpad, it's just less smooth. 

I have a VFR 240Hz, 1440p monitor set as fake HiDPI (macOS is rendering in 5K and scaling down to 1440p), so I figured I compare VSCode (Insiders) scrolling with Zed's (I have stable channel version installed).

Here's a screen recording with FPS meters in both VSCode and Zed. It doesn't really show the difference, but in person the difference is pretty apparent.
https://github.com/zed-industries/zed/assets/69842744/83373266-527d-495d-8944-9b50a9787f2f

The faster I scroll the slower it gets on both editors, but Zed's "baseline", normal speed scrolling is ~70-100fps, while VSCode's is 200-240fps.

**Comment by mikayla-maki** [comment]
Hmmm, I wonder if that means the issue is in our editor somewhere, rather than in the framework 🤔, thanks for the research @rev4324

**Comment by mrnugget** [comment]
Hey all! Thanks for the recordings and data everyone. We're still debugging this.

The problem is that this is _really_ hard to reliably reproduce. It's also hard to know which measurements are exact and which aren't. Example: Apple's Metal HUD seems like it has a life of its own and sometimes it shows the Hz of the external display on which it's displayed, sometimes it doesn't. VS Code's FPS meter constantly shows 120fps, even if nothing happens on screen.

I can say that I can get 120fps to show up on the MBP display when scrolling in Zed, BUT the `Pre` times that are on the Metal HUD (supposedly "time between presents" or "frame times" [according to Apple](https://developer.apple.com/videos/play/tech-talks/110339/)) don't match what we log as frame times. See here:

https://github.com/zed-industries/zed/assets/1185253/55663864-d5bd-41f4-9410-ead20aa1bf78

The `frame durations` we log (when `ZED_MEASUREMENTS=1` is set) are consistently <5ms, yet the Metal HUD shows `Pre` time as 18ms:

![screenshot-2024-01-29-14 03 59@2x](https://github.com/zed-industries/zed/assets/1185253/e07c37b5-5c5e-4a6e-adbb-80a3f0ed35ea)

That's one interesting thing I want to investigate.

The other is that it's really hard to reliably reproduce any consistent frame rates: sometimes I get ~60FPS on this external display, sometimes ~80fps, sometimes on the MBP it hovers around 80fps, sometimes around 120fps.

---

The other thing worth mentioning here is: does this maybe have something to do with the scrolling itself and not the FPS? VS Code has a very high scroll speed. It's really easy to just flick on the touchpad and scroll down 400-500 lines, vs. the 250 you get in Zed. So maybe scrolling is involved too. Investigating.

---

If anyone wants to help investigate this further:

1. Can you try running Zed with `ZED_MEASUREMENTS=1` and see what frame durations are reported and whether they match what's reported in the Metal HUD?
2. @as-cii and I have investigated a new approach for our main render loop, which is simplified and entirely based on macOS' display link. It _could_ be faster (it _feels_ faster but the HUD doesn't confirm, at least not consistently). So if you want to try this out, that'd be very interesting:
  * Check out `display-link` branch
  * Run `cargo run --release`
  * Scroll your heart out, see if this feels different

**Comment by oliver-kriska** [comment]
I tried that branch and it feels same. And hud shows lower FPS, max about 80. Preview shows max about 110 FPS. Frame duration in console is about 5-9 and a few 4, not a lot. So it's a little slower, that's my basic feelings.

**Comment by mrnugget** [comment]
Just dropping more data in here. I took profiles/traces of Zed in Instruments.app, only on the MBP, no external display attached.

And, well: we do hit the 8ms pretty consistently. There are some blocking wait times, but as far as I understand everything that's going on that's because the main thread is blocked on events. So these blocks also coincide with me hitting the touch pad to scroll (I have to admit: I learned in the past few days that I'm pretty bad at consistently scrolling fast through a 10k line file a touch pad...)

![screenshot-2024-01-29-16 14 50@2x](https://github.com/zed-industries/zed/assets/1185253/25c8cd2e-456b-4050-a105-03b92a541a5e)

**Comment by diocletiann** [comment]
I also had noticeable jitter a couple of days ago (gone now) and it reminded me of this https://github.com/neovide/neovide/pull/2102

**Comment by mrnugget** [comment]
> I also had noticeable jitter on the 120hz MBP display a couple of days ago (gone today) and it reminded me of [neovide/neovide#2102](https://github.com/neovide/neovide/pull/2102)

Yup, that's what we have implemented in the `display-link` branch. I'll try to make progress on that today as much as possible.

**Comment by mrnugget** [comment]
Little end-of-day-update:

* Made progress on the `display-link` branch, removed the blocking call, made it redraw on window resize and window launch. So now it should work as before.
* I still can't really say that we don't support high-refresh, because I can get it to render at ~120fps with and without that branch.
* @ConradIrwin, @bennetbo and I then investigated the scrolling more and pushed a commit to the branch that does the same thing that `winit` does: it uses the scale-factor when doing pixel-scrolling. https://github.com/zed-industries/zed/commit/229f7e44fe8ed3bdd988fa6cfd39cc1956997e14 That makes scrolling a lot faster. It still feels a bit off though. Maybe we need a logarithmic-scale here? But then again: VS Code does its own thing and has really fast and aggressive scroll. So maybe we need to lean into that direction completely?

**Comment by szlend** [comment]
- The `display-link` branch in `Direct` mode feels much smoother now. However the `Composited` mode is now the laggy one.
- In the Metal HUD I still see FPS alternating between 60fps and 120fps exactly. Is Zed running at vsync and Metal just throws the extra frames away? The M1+ laptops should support variable refresh rates so I would expect framerates in-between as well. I suspect this is what makes the scrolling actually feel choppy.
- I'm not sure if I like the new scrolling behavior. I thought the old one was fine (I didn't actually notice the difference to vscode until I compared the two side by side). But the new scrolling behavior immediately feels off - way too twitchy.

**Comment by mrnugget** [comment]
> In the Metal HUD I still see FPS alternating between 60fps and 120fps exactly. Is Zed running at vsync and Metal just throws the extra frames away? The M1+ laptops should support variable refresh rates so I would expect framerates in-between as well. I suspect this is what makes the scrolling actually feel choppy.

Whoa, that's really interesting. On my M3 I get variable FPS, up to 120fps, but it's never really exact. I'm going to later try this on the M1 I have here.

And yes, the `display-link` branch is essentially handing the reigns to the OS so it can request a frame when it needs to, which is how Neovide did it too: https://github.com/neovide/neovide/pull/2102 I'm still not 100% convinced of this approach here and what the HUD says.

So overall you would say the `display-link` branch is not an improvement because `Direct` is smoother but `composite` is laggy?

**Comment by szlend** [comment]
> Whoa, that's really interesting. On my M3 I get variable FPS, up to 120fps, but it's never really exact. I'm going to later try this on the M1 I have here.

Note that I'm ignoring the average FPS and only looking at `min`, `max` framerate and the `pre` chart.

<img width="283" alt="Screenshot 2024-01-31 at 09 10 03" src="https://github.com/zed-industries/zed/assets/7301807/7265e3c5-1075-4a63-8110-4bc3c6c1d83d">
<img width="311" alt="Screenshot 2024-01-31 at 09 12 06" src="https://github.com/zed-industries/zed/assets/7301807/1ffa2574-0514-4ead-a09c-8e4f8dce5711">

See the `pre` and `fps` times match vsync exactly. The `pre` chart shows the spikes over time and they always exactly double.

> So overall you would say the display-link branch is not an improvement because Direct is smoother but composite is laggy?

Side-grade yeah. I usually program in full screen so for me it's an improvement :)

**Comment by mrnugget** [comment]
That does look like it's working as intended though, right? FPS is variable between 60 and 120hz here.

**Comment by szlend** [comment]
> That does look like it's working as intended though, right? FPS is variable between 60 and 120hz here.

No, the FPS shown is average FPS. If I have one frame rendered at 60fps intervals and two frames rendered at 120fps intervals, then the average framerate is 80fps. 

Look at the blue spikes in the `Pre` chart. It's alternating between 8.33ms and 16.67ms.

**Comment by mrnugget** [comment]
Ah, I see what you're saying. It's not really variable, but only flipping between 60 and 120hz?

**Comment by szlend** [comment]
> Ah, I see what you're saying. It's not really variable, but only flipping between 60 and 120hz?

Yeah exactly. Afaik metal has an API for Adaptive Sync which is supposed to match the screen refresh rate to the content rendered by the GPU as opposed to the other way around. Right now when the renderer misses a 120hz frame interval, it has to wait for another (60hz).

That would explain the choppiness, as a sudden 50% framerate drop is pretty jarring. I'm not saying this is the main culprit though. If zed is able to consistently render at 120fps+, then vsync isn't really a problem.

**Comment by mrnugget** [comment]
Interesting. On my M3 Max I don't see the flip-flopping between 8ms/16ms. See screenshot above:

![screenshot-2024-01-31-15 40 27@2x](https://github.com/zed-industries/zed/assets/1185253/278b0925-3872-4b2d-8009-dbe61cb8bd93)

Also worth noting: according [to this documentation on Adaptive Sync](https://developer.apple.com/videos/play/wwdc2021/10147/) one requirement for adaptive sync is

> [And lastly, your app needs to be running in full-screen mode.](https://developer.apple.com/videos/play/wwdc2021/10147/?time=340)

So that wouldn't buy us much, since you said that in `Direct` rendering mode the `display-link` branch is already smoother and `Direct` is what's being used when you're fullscreen.

**Comment by mrnugget** [comment]
Just adding another puzzle piece: on the M3 Max display (no other display attached, attached to power), I can scroll through `types.ts` and hit 120fps pretty consistently. It only drops down to ~10ms frame time when I hit the touch pad. The drops in CPU/context-switches/... and spikes in frame time here happen every time my fingers hit the touch pad:

![screenshot-2024-01-31-16 12 41@2x](https://github.com/zed-industries/zed/assets/1185253/6b388935-375a-4f7e-8bed-76ca19bb51c2)

Yes, I recorded myself doing this and then saw these bumps show up in the HUD too.

**Comment by szlend** [comment]
It's interesting to me that your `max` FPS is going up to 575FPS. Is that right? For me it never goes above exactly my refresh rate (120fps with ProDisplay, or 60fps if I change to 60hz). This suggests that there's something different to our setups.

**Comment by diocletiann** [comment]
It's difficult to compare smoothness of the display-link branch with the trackpad input boosted. What should I edit so it matches main?

**Comment by mrnugget** [comment]
I just reverted that commit on the branch. You can try that again.

**Comment by diocletiann** [comment]
Still boosted

**Comment by mikayla-maki** [comment]
It's interesting that the frame drop happens as soon as you use the touch pad....

**Comment by rev4324** [comment]
> It's interesting to me that your `max` FPS is going up to 575FPS. Is that right? For me it never goes above exactly my refresh rate (120fps with ProDisplay, or 60fps if I change to 60hz). This suggests that there's something different to our setups.
> 
> 
> 
> > The drops in CPU/context-switches/... and spikes in frame time here happen every time my fingers hit the touch pad
> 
> 
> 
> Same here, but I don't think it's completely isolated to input.

I'd say it may be the fact that @mrnugget uses an M3 Max, which is much faster than my M1, or even your M1 Pro chip. Unless the issue isn't really related to rendering unable to keep up on "slower" machines. Anyhow, I think having a faster GPU almost always helps.

Personally my gut feeling is this is related both to VSync and raw performance. The renderer is able to keep up with 120+ fps *sometimes*, but when it can't, the framerate drops all the way down to 60. @mrnugget's machine is just much faster, so this likely doesn't happen at all there.

M1 series have still pretty fast GPUs though, and most programs can keep even up to my 240Hz monitor without dropping to 120 or 60 (with vsync), so Zed probably does some work somewhere that makes it slower at scrolling in particular.

**Comment by mrnugget** [comment]
> Still boosted, do you mind setting to raw pixel delta?

There's nothing boosted in that branch anymore. It's our normal scroll behaviour. (We also checked and it matches Sublime's or TextEdit's or Safari's.)

> It's interesting that the frame drop happens as soon as you use the touch pad....

Yeah, I think that's to be expected though: the OS essentially interrupts us to send us a new touch event, which we then turn into another scroll.

Take a look at these videos here. This is me scrolling on the M3 Max and the M1 Max, trying to "fling" as much as possible and touching the pad as little as possible. You can see that whenever the screen just scrolls (no touch), the blue line goes down to ~8ms, which means roughly 120hz. As soon as I touch, you see that little blip in the blue line.

M3 Max:
https://github.com/zed-industries/zed/assets/1185253/b99e382d-3891-4cff-ac10-eab97566bad5

M1 Max:
https://github.com/zed-industries/zed/assets/1185253/86b4e4b8-81f1-4e2a-9d6f-12ce75bc1029

> The renderer is able to keep up with 120+ fps sometimes, but when it can't, the framerate drops all the way down to 60. @mrnugget's machine is just much faster, so this likely doesn't happen at all there.

See the videos. On the M1 Max I get the exact frame rate as on the M3 Max.

It's also not like the OS constantly renders at 120fps. The OS _calls us_: it asks us to render a frame. And sometimes, when you do nothing, or another app takes control, or something else, it doesn't call us and FPS drop. That's normal. 

(You can also confirm this by scrolling with your keyboard! My keyboard repeat rate is such that when I hold down `arrow-down` I get ~60FPS, just because there aren't more lines showing up on screen fast enough.)

---

It's also worth nothing that I'm not saying any of you are wrong, but that we have a _really_ hard time even reproducing the issue. I've literally spend hours in the past few days scrolling in Zed 😄 But it doesn't feel laggy or jittery to me anymore. I'm writing this on an M1 Max, on which I've again compared VS Code and Zed and ... rendering looks the same? It's smooth in both, FPS are adjusted depending on what the program is doing. The difference is that VS Code's scrolling is aggressive and thus gets higher throughput of lines to render, so to say.

---

That being said: here's a new branch to try out! @as-cii came up with the idea of flipping our render loop around, so that we hit the vsync times more often. Branch name: `optimistic-draw`. 

@szlend can you give this a shot? `cargo run --release` (the `--release` is important!) in that branch and try scrolling a bit.

**Comment by diocletiann** [comment]
@mrnugget `optimistic-draw` feels great. I can't detect any jitter and trackpad sensitivity is consistent with other apps.

**Comment by diocletiann** [comment]
I think it would help provide consistent feedback if you added smooth scrolling to keyboard-activated scroll commands, that way everyone can hold up/down or pgup/pgdn and compare at the same speed.

**Comment by szlend** [comment]
@mrnugget  Whatever you did in `optimistic-draw`, `Composite` mode feels butter smooth! Constant 120fps.

Still feels laggy in fullscreen (`Direct` mode) though. @diocletiann could you check if that's the case for you as well?

**Comment by mrnugget** [comment]
Another update here: @as-cii @nathansobo @maxbrunsfeld found another fix/improvement here https://github.com/zed-industries/zed/pull/7253. It's already on `main`, so it would be very interesting to see if someone in here now notices differences when creating a `--release` build on `main`. (There also will be patch/preview release later today, I'm sure.)

**Comment by szlend** [comment]
`master` is perfectly smooth in `Composite` mode and pretty good in `Direct` as well. Most balanced so far. I don't get why `Direct` mode performs worse though. It alternates between 60 and 120fps even when not touching the input. It was very smooth in the `display-link` branch though. I checked out the branch again just to compare/confirm.

So for me these ones are smooth now:
- `Composit`: master, optimistic-draw
- `Direct`: display-link (and pretty good in master too)

**Comment by mrnugget** [comment]
Yup. I haven't talked to the others since the fix was merged, so I might be off, but I think we have to combine both approaches: `display-link` and what's on `main`.

**Comment by mrnugget** [comment]
@szlend I just rebased `display-link` onto `main`, if you want to give that a shot.

**Comment by szlend** [comment]
> @szlend I just rebased `display-link` onto `main`, if you want to give that a shot. (Edit: I also fixed an earlier mistake of mine when I reverted the wrong commit, not the boosted-scrolling commit 🤦 )

Tried `a0c10abe`. `Composite` is just as choppy as before on this branch. It's choppy while not touching any input (from scrolling intertia), so those input optimizations on main probably have no effect.

FWIW I rebased `optimistic-draw` on `main` and that one seems to be the smoothest one in both rendering modes.

**Comment by mrnugget** [comment]
Oookay, I probably have some very good news here: @as-cii made the latest fix on `main` work and it's just been released in the latest Preview version: [0.121.2-pre](https://zed.dev/releases/preview/0.121.2).

Can you all try that out and see if you still have the same problem?

@haze reported that scrolling is now much better on their M3 Max 14". Previously the blue line in the Metal HUD was jittery (wheras mine was flat with spikes), now it's a lot better.

**Comment by diocletiann** [comment]
Flat blue with spikes on my M1 Max, minus the quick judder when motion begins and ends. Feels great.

**Comment by rev4324** [comment]
Just tried latest preview, and I think the issue is solved. Blue line on mine is flat, with spikes appearing as I touch the trackpad, but I'm not able to feel anything. Pre is around 4ms when I scroll, while GPU is around 2ms. It feels as good as e.g. Finder now, much better than VS Code.

**Comment by szlend** [comment]
`0.121.2-pre` is perfectly smooth in `Composite` mode, but still laggy in `Direct` mode (a ton of blue spikes). So for me at least this is not 100% fixed. The `optimistic-draw` branch paired with the input optimizations on `main` is the only one that works well in both modes.

It would be great if anyone reporting this as fixed could double check their rendering mode with `MTL_HUD_ENABLED=1` and maybe try forcing it into `Direct` mode to compare. Usually using the MacOS fullscreen option forces it into Direct mode. Note that everything else (dock, menu bar, etc) has to be hidden for MacOS to switch to Direct rendering.

You can launch the Metal HUD from the terminal for any Zed app bundle like so:
```
$ MTL_HUD_ENABLED=1 <path_to_zed>.app/Contents/MacOS/zed
```

**Comment by mrnugget** [comment]
@szlend can you try out `main` again? This has been merged now too: #7347

**Comment by oliver-kriska** [comment]
For me it's much faster, FPS around 140, measurements log around 2-3ms, previously +5-7ms. 

https://github.com/zed-industries/zed/assets/39122854/29a07eee-ed19-4317-b3d9-c58b5d14fd53

**Comment by szlend** [comment]
> @szlend can you try out main again? This has been merged now too: https://github.com/zed-industries/zed/pull/7347

It's prefect now! I can't get it to drop a single frame in Direct mode. Great job on this, and thanks for bearing with me :)

**Comment by mrnugget** [comment]
Perfect! Then I'm going to close this issue, since everybody seems happy with current `main`. Thanks everybody for helping out here!

**Comment by activenode** [comment]
I cannot exactly tell what it is but on a super-high-end machine (Mac, M3 Max, 96gb ram) with 2 external monitors I do run zed vertically on an LG QHD (not sure if it's anything to do with the monitor here but it's the only monitor I code on so also the only one I experience this with, but next time this appears I'll move it to a different window to see if it makes a difference).

Anyway, what happens is an EXTREMELY laggy behaviour (unusably laggy) . But it doesn't happen always, but often.

I don't know what happens really, but I wanted to report that this happens .

I never had this problem with my M1 Pro Macbook which had 32gb ram. It seems that this high-end machine somehow does something different which causes ZED to fail.

**Comment by mrnugget** [comment]
Does it go away when you disable the scrollbar?

**Comment by activenode** [comment]
> Does it go away when you disable the scrollbar?

hard to tell. I'll try to reproduce it.

**Comment by R4zeel** [comment]
I think that i'm encountering the same issue: while in fullscreen scrolling feels laggy, definitely below 60 fps. When editor not in fullscreen mode - everything is fine.
Running zed on M3 Pro, 18gb RAM.

**Comment by activenode** [comment]
> I think that i'm encountering the same issue: while in fullscreen scrolling feels laggy, definitely below 60 fps. When editor not in fullscreen mode - everything is fine. Running zed on M3 Pro, 18gb RAM.

That relates.

**Comment by mrnugget** [comment]
Can you try it with `MTL_HUD_ENABLED=1`? Are there any messages in the logs? Can you try disabling the scrollbar?

**Comment by R4zeel** [comment]
> ```
> /bin/launchctl setenv MTL_HUD_ENABLED 1
> ```

Sure, i disabled the srollbar and turned on `MTL_HUD`, made a screen record but i'm afraid that for some reason on record there is no visual difference between fullscreen and windowed mode, hope i'm not imagining things

**Comment by mrnugget** [comment]
> but i'm afraid that for some reason on record there is no visual difference between fullscreen and windowed mode, hope i'm not imagining things

Hehe, we've all been there. What you can do is record with your phone or another camera — that's what I did in the past. It helps because it's not mucking with macOS' compositor.

**Comment by R4zeel** [comment]
> ```
> /bin/launchctl setenv MTL_HUD_ENABLED 1
> ```

Tried to record on my phone, had to reduce quality to upload here but i hope the difference can be seen

https://github.com/zed-industries/zed/assets/45760904/f9458e84-dce0-4d78-bcd9-55277e155e93

**Comment by mrnugget** [comment]
Hmmm, I don't see a difference, but I also don't think there's anything we can do here as long as macOS reports 120fps in both modes, which it does here, right?

**Comment by felixmpaulus** [comment]
Just downloaded zed today. And I encounter this problem as well. It feels kind of slow when scrolling.

<img width="259" alt="Screenshot 2024-09-07 at 9 41 39 AM" src="https://github.com/user-attachments/assets/bb4fd780-955c-4f51-b07f-663d1c7affd3">

**Comment by mrnugget** [comment]
> Just downloaded zed today. And I encounter this problem as well. It feels kind of slow when scrolling.

Do you mean the FPS, i.e. did you enable the Metal HUD as described above, or do you mean that scroll speed is different from other apps?
