### ISSUE TITLE
After updating to version `0.122.2`, the code scrolling is noticeably not smooth.

### ISSUE THREAD

**Issue by widersky** [zed-industries/zed#7671]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Both VSCode and IntelliJ IDEA scroll the same code perfectly smoothly, while in the case of Zed I see frequent clear micro-slowdowns. Unfortunately, it is difficult for me to record this on the video. I use a 100Hz monitor.

### Environment

Zed: v0.122.2 (Zed Preview)
OS: macOS 14.3.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by bennetbo** [comment]
Would be great to get more info on this, as there were numerous issues with this in the previous versions, but those should be fixed in v0.122.2.

Can you follow the directions from [this comment](https://github.com/zed-industries/zed/issues/6427#issuecomment-1910119125) and possibly upload a video showcasing the frame drops?

Is there something special about the file you are testing this on? (language, size, etc.)

**Comment by widersky** [comment]
@bennetbo When I launch Zed with HUD enabled, there is constant 100Hz here, but scrolling is still not 100% fluid.

![image](https://github.com/zed-industries/zed/assets/45122321/f859ef2b-8909-4275-b4b0-e7312a647a1b)

Referring to bullets:

- It's not related to file type or size
- I have only external monitor because I'm working on Mac Mini

I tried to record the screen with an iPhone and it seems to me that the problem is somewhat visible (was not visible when I used QuickTime). It would seem that the problem is not in the scrolling itself, but occurs especially when the scrolling is started.

https://github.com/zed-industries/zed/assets/45122321/8b33bfc0-db7e-452b-9482-9d1791823b50

I use MX Master for Mac. Scroll has two modes there - one when the scroll puts a slight resistance when scrolling and smooth where there is no resistance. Regardless of the mode, the problem occurs. Given that HUD does not report any FPS drops, the problem seems to lie somewhere else, but it is clearly visible to the naked eye. I use a 3440x1440px 100Hz monitor.

Given the visual experience, I feel as if the frames are not so much lost as slowing down, but it may have a strong relationship to the specifics of my mice work.

Final note: I'm not using Logitech's default software, I'm using [Mac Mouse Fix](https://github.com/noah-nuebling/mac-mouse-fix) version 3.0.1 instead.

**Comment by bennetbo** [comment]
Thanks for your detailed response. 
First off, I believe I can also notice a "smoothness" difference in your video.

Im not 100% sure, as im just trying to gather as much information for the zed team here, but whats confusing me about the metal hud screenshot you posted, is that zed seems to render at around 60 fps.

Here are the numbers i get when running zed on my setup:
- 60 fps on my external monitor (60 hz display)
- 120 fps on my macbook display (120hz display).

So i would expect zed to render at 100 fps on your 100 hz screen, right?

Can you try with the previous version of the zed, which you did not seem to have any issues with and see if there is a difference in framerate reported by the metal hud?

Unfortunately im not familiar with "mac mouse fix software" so i cant comment on that

**Comment by widersky** [comment]
@bennetbo I'm 100% sure that this problem did not occur in version `0.121.x` so it must be related to recent changes in terms of rendering under Metal.

**Comment by bennetbo** [comment]
There were a lot of changes in the rendering code, so it might be difficult to find the cause.
I think a video with Metal Hud enabled and a CPU profile recording should be helpful for further investigation.

**Comment by widersky** [comment]
@bennetbo Okay! I'll record a video tomorrow :)

**Comment by mrnugget** [comment]
Hey @widersky! We looked into this, but didn't make a lot of progress. It's hard to find out what's happening exactly.

But what we can say:
1. It seems like it's purely related to `Mac Mouse Fix` and use of scroll wheel - when scrolling on a 120hz/60hz display, with touchpad, it still feels smooth. With the `Mac Mouse Fix` enabled, it starts to feel jittery.
2. For me, when I have `Mac Mouse Fix` enabled, scrolling in Chrome also feels jittery. Really jittery.

So, here are some questions:

1. When you disable `Mac Mouse Fix`, the problem goes away? 
2. Do you have a trackpad by chance? Does scrolling compare?
3. Can you nail it down to an exact version with which it still worked? We had a lot of changes on the `0.121` branch.

**Comment by widersky** [comment]
@mrnugget thank you for this investigation! After some tests done it looks like this issue is heavily related to Mac Mouse Fix app - maybe it's related do MMF version 🤔 Unfortunately, I have no way to test it on the trackpad. I'll try other apps for mouse-tweak to see if there will be any differences.

**Comment by mrnugget** [comment]
@widersky I found that if you toggle the `Precision` setting in Mac Mouse Fix on/off it also changes things considerably.

**Comment by mrnugget** [comment]
I'm going to go ahead and close this since it doesn't seem reproducible and heavily related to the `Mac Mouse Fix` app. Happy to re-open if it comes up again.

**Comment by widersky** [comment]
@mrnugget thank you! It seems that the last update (`3.0.2`) of the `Mac Mouse Fix` app has improved the situation significantly and the problem no longer occurs :)

**Comment by beshubh** [comment]
this is happening for me even without Mac Mouse fix, when I scroll using touch pad everything's smooth but when I do the same with mouse it feels like refresh rate is back to 60fps

**Comment by widersky** [comment]
@beshubh I can confirm that scrolling with mouse is still not as smooth as by touchpad

**Comment by taburet** [comment]
@widersky I'm suffering from the same issue, did you find the solution? probably some other mouse software?

**Comment by taburet** [comment]
just noticed a strange thing, if Zed window is in background partially covered by some other window which is in foreground/focused, scrolling in Zed (without activating its window) is almost perfectly smooth, at least it's not dropping/skipping frames that frequently
