### ISSUE TITLE
Project-Wide Search not work

### ISSUE THREAD

**Issue by ThaddeusJiang** [zed-industries/zed#8419]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Project-Wide Search not work

I search `bigquery` in my terraform repository, zed returns `No results`.
But I have a lot of `bigquery` in my codes.

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

left: zed, right: vscode

![image](https://github.com/zed-industries/zed/assets/17308201/006faa0f-6571-4770-b5f7-8a69a78a3905)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by sumitparakh** [comment]
I would like to take this up

**Comment by JosephTLyons** [comment]
Hey @ThaddeusJiang, is your project in a similar structure as this?

- https://github.com/zed-industries/zed/issues/8187#issuecomment-1959425325

Specifically, are you nesting git repositories within git repositories?

**Comment by ThaddeusJiang** [comment]
@JosephTLyons Yes, my terraform project is sub directory in other git repository.

Thank you, I will tell you when I upgrade the new version.

**Comment by Moshyfawn** [comment]
It seems that #6998 has already described this exact behaviour. 

I'm not sure which one would be most appropriate to close in favour of the other. @JosephTLyons

**Comment by JosephTLyons** [comment]
@Moshyfawn - I think the fixes linked above are currently in preview and will ship to stable this upcoming week.  We should double check with these users that preview fixes their issues and if so, close everything out! :)

**Comment by JosephTLyons** [comment]
For anyone following this thread for this bug, can you try the latest preview version and see if the issue persists?

https://zed.dev/releases/preview

**Comment by notpeter** [comment]
I believe this has been fixed.  If you project-wide search is not functioning for you, please feel free to open a new issue. Thanks

**Comment by devKid88** [comment]
Still not fixed, whatever I search I am getting "no results"

**Comment by uriafranko** [comment]
still happens, with newest version

**Comment by micdoh** [comment]
project search not working
