### ISSUE TITLE
Vue-language-server is not working

### ISSUE THREAD

**Issue by klyuk88** [zed-industries/zed#9388]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Why is there a log with vue-language-server running, but no autocomplete or hints in the .vue files?

### Environment

Mac OS Ventura Apple M2.

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1856" alt="Снимок экрана 2024-03-15 в 12 34 44" src="https://github.com/zed-industries/zed/assets/48031577/10e2f767-0906-42b0-a5d8-c2f0894569d6">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

2024-03-15T12:14:54+03:00 [INFO] Language server with id 34 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/ba/Documents/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B/vue-project/src/main.ts",
  "state": 1
}
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [ERROR] crates/project/src/project.rs:5210: Request completionItem/resolve failed with message: Cannot read properties of undefined (reading 'file')
2024-03-15T12:14:54+03:00 [INFO] Language server with id 34 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/ba/Documents/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B/vue-project/src/main.ts",
  "state": 1
}
2024-03-15T12:16:02+03:00 [INFO] starting language server "json-language-server", path: "/Users/ba/Documents/Проекты/vue-project/", id: 36
2024-03-15T12:16:02+03:00 [INFO] starting language server. binary path: "/Users/ba/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/Users/ba/Documents/Проекты/vue-project/", args: ["/Users/ba/Library/Application Support/Zed/languages/json-language-server/node_modules/vscode-json-languageserver/bin/vscode-json-languageserver", "--stdio"]
2024-03-15T12:19:37+03:00 [ERROR] crates/terminal_view/src/terminal_view.rs:285: error upgrading view
2024-03-15T12:22:06+03:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-03-15T12:22:06+03:00 [INFO] Language server with id 31 sent unhandled notification workspace/diagnostic/refresh:
null
2024-03-15T12:22:06+03:00 [INFO] Language server with id 34 sent unhandled notification eslint/status:
{
  "uri": "file:///Users/ba/Documents/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B/vue-project/src/main.ts",
  "state": 1
}
2024-03-15T12:22:22+03:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-15T12:22:22+03:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-15T12:22:22+03:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-15T12:22:22+03:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-15T12:22:22+03:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-15T12:22:22+03:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-15T12:22:22+03:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-15T12:22:22+03:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-15T12:22:22+03:00 [ERROR] crates/gpui/src/window.rs:434: window not found
2024-03-15T12:22:22+03:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-15T12:22:22+03:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-15T12:22:22+03:00 [ERROR] crates/terminal_view/src/terminal_view.rs:285: error upgrading view
2024-03-15T12:22:22+03:00 [ERROR] crates/terminal_view/src/terminal_view.rs:285: error upgrading view
2024-03-15T12:23:50+03:00 [INFO] Initializing default prettier with plugins {}
2024-03-15T12:23:50+03:00 [INFO] starting language server "vue-language-server", path: "/Users/ba/Documents/Проекты/vite-project/", id: 37
2024-03-15T12:23:50+03:00 [WARN] Skipping path "/Users/ba/Documents/Проекты/vite-project" that has no prettier dependency and no workspaces section in its package.json
2024-03-15T12:23:50+03:00 [INFO] starting language server. binary path: "/Users/ba/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/Users/ba/Documents/Проекты/vite-project/", args: ["/Users/ba/Library/Application Support/Zed/languages/vue-language-server/node_modules/@vue/language-server/bin/vue-language-server.js", "--stdio"]
2024-03-15T12:23:59+03:00 [INFO] Initializing default prettier with plugins {}
2024-03-15T12:23:59+03:00 [INFO] starting language server "typescript-language-server", path: "/Users/ba/Documents/Проекты/vite-project/", id: 38
2024-03-15T12:23:59+03:00 [INFO] starting language server "eslint", path: "/Users/ba/Documents/Проекты/vite-project/", id: 39
2024-03-15T12:23:59+03:00 [WARN] Skipping path "/Users/ba/Documents/Проекты/vite-project" that has no prettier dependency and no workspaces section in its package.json
2024-03-15T12:23:59+03:00 [INFO] starting language server. binary path: "/Users/ba/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/Users/ba/Documents/Проекты/vite-project/", args: ["/Users/ba/Library/Application Support/Zed/languages/typescript-language-server/node_modules/typescript-language-server/lib/cli.mjs", "--stdio"]
2024-03-15T12:23:59+03:00 [INFO] starting language server. binary path: "/Users/ba/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/Users/ba/Documents/Проекты/vite-project/", args: ["/Users/ba/Library/Application Support/Zed/languages/eslint/vscode-eslint-release/2.2.20-Insider/vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-03-15T12:24:00+03:00 [INFO] Language server with id 39 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "ESLint server running in node v18.15.0"
}
2024-03-15T12:24:00+03:00 [INFO] Language server with id 38 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Using Typescript version (user-setting) 5.4.2 from path \"/Users/ba/Documents/Проекты/vite-project/node_modules/typescript/lib/tsserver.js\""
}
2024-03-15T12:24:00+03:00 [INFO] Language server with id 38 sent unhandled notification $/typescriptVersion:
{
  "version": "5.4.2",
  "source": "user-setting"
}
2024-03-15T12:24:00+03:00 [INFO] Language server with id 39 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/ba/Documents/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B/vite-project/src/main.ts"
  }
}

**Comment by klyuk88** [comment]
node js v20.11.0

**Comment by mstiles-grs** [comment]
I thought I was the only one! I have a M1 mac with node js v20.11.0 running vue3

I've also tried to add a local LSP with no luck or errors.

**Comment by mariagq777** [comment]
node js v20 and vue is not working. tested in m1 macbook and intel imac 2015 thanks

**Comment by WalkAlone0325** [comment]
m1 macbook, node 18.20.0, Zed 0.128.3。Vue-language-server is not working. RPC logs is working

**Comment by mrnugget** [comment]
https://github.com/zed-industries/zed/pull/9846 has been merged. Try using 0.129.x-preview release, which contains the fix.

**Comment by Moshyfawn** [comment]
Can anyone confirm that this has been resolved?

**Comment by fazulk** [comment]
Still having this issue with `0.131.7` vue language server looks like this 

```{
  "dependencies": {
    "@vue/language-server": "1.8.27",
    "typescript": "5.4.5"
  }
```

TS is working inside the .vue files, but i'm getting a error on any TS trying to import a .vue file. 
![image](https://github.com/zed-industries/zed/assets/21964900/2ce726b2-a5a2-43d8-bf60-3691bbf60a79)

**Comment by fazulk** [comment]
fyi- got this working by adding this to my tsconfig

```    
"plugins": [{ "name": "@vue/typescript-plugin" }],
```

**Comment by d1y** [comment]
Update(carry another #10871):

I use `monorepo` not work:

```bash
❯ tree -L 2
├── backend
├── frontend
│  ├── admin # vue project
│  ├── client # vue project
│  ├── types # vue project
```

Workaround:

> As @olrtg mentioned, typescript dependencies need to be installed manually

```bash
cd $root
npm init -y
npm i --save-dev typescript
```

**Comment by klyuk88** [comment]
<img width="1131" alt="Снимок экрана 2024-04-25 в 15 42 05" src="https://github.com/zed-industries/zed/assets/48031577/e3d4d30b-24f0-4412-a1e4-a0879ad5df8a">
In the current version of Zed, Vue support is included in the extension. After installing the extension, everything works out of the box.

**Comment by olrtg** [comment]
@mrnugget for this particular case OP seems to have fixed the problem by reinstalling the extension. But there are other cases (in nuxt projects for example) where typescript is not a dev dependency (and it shouldn't be) so the vue language server doesn't know where to look for the file to start the typescript server. I have a feeling that other editors are solving this by shipping their own version of typescript along with the language server. But that's only a theory.

There's also another problem why you guys decided to pin the vue version, but I couldn't understand the problem.

So those are the main problems with vue/zed integration. Just a quick summary.
Keep up the great work. Big fan of yours!

**Comment by joshuaia** [comment]
Fixed for me as well but not in workspace based repos, see https://github.com/zed-industries/zed/issues/12019
